/*
 * xHarbour Compiler, build 82.0 (SimpLex)
 * Generated C source code from </vclon/VZLL/BUTTON.prg>
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "/vclon/VZLL/BUTTON.prg"

HB_FUNC( TBUTTON );
HB_FUNC_STATIC( TBUTTON_NEW );
HB_FUNC_STATIC( TBUTTON_REDEFINE );
HB_FUNC_STATIC( TBUTTON_CLICK );
HB_FUNC_STATIC( TBUTTON_CGENPRG );
HB_FUNC_STATIC( TBUTTON_GOTFOCUS );
HB_FUNC_STATIC( TBUTTON_LOSTFOCUS );
HB_FUNC_STATIC( TBUTTON_KEYDOWN );
HB_FUNC_STATIC( TBUTTON_INITIATE );

static HARBOUR hb_INITSTATICS( void );

extern HB_FUNC( HBCLASS );
extern HB_FUNC( __CLS_PARAM );
extern HB_FUNC( __CLSINST );
extern HB_FUNC( PCOUNT );
extern HB_FUNC( HB_APARAMS );
extern HB_FUNC( GETWNDDEFAULT );
extern HB_FUNC( MAX );
extern HB_FUNC( LEN );
extern HB_FUNC( NOR );
extern HB_FUNC( VALTYPE );
extern HB_FUNC( EMPTY );
extern HB_FUNC( GETFOCUS );
extern HB_FUNC( STR );
extern HB_FUNC( POSTMESSAGE );
extern HB_FUNC( LAND );
extern HB_FUNC( GETWINDOWLONG );
extern HB_FUNC( SETWINDOWTEXT );
extern HB_FUNC( ERRORSYS );
extern HB_FUNC( TCONTROL );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 5

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_BUTTON )
{ "TBUTTON", HB_FS_PUBLIC | HB_FS_FIRST, HB_FUNCNAME( TBUTTON ), (PHB_DYNS) 1 },
{ "NEW", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "HBCLASS", HB_FS_PUBLIC, HB_FUNCNAME( HBCLASS ), NULL },
{ "__CLS_PARAM", HB_FS_PUBLIC, HB_FUNCNAME( __CLS_PARAM ), NULL },
{ "ADDMULTIDATA", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ADDMETHOD", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TBUTTON_NEW", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TBUTTON_NEW ), (PHB_DYNS) 1 },
{ "TBUTTON_REDEFINE", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TBUTTON_REDEFINE ), (PHB_DYNS) 1 },
{ "TBUTTON_CLICK", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TBUTTON_CLICK ), (PHB_DYNS) 1 },
{ "TBUTTON_CGENPRG", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TBUTTON_CGENPRG ), (PHB_DYNS) 1 },
{ "TBUTTON_GOTFOCUS", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TBUTTON_GOTFOCUS ), (PHB_DYNS) 1 },
{ "TBUTTON_LOSTFOCUS", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TBUTTON_LOSTFOCUS ), (PHB_DYNS) 1 },
{ "ADDINLINE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "MOUSEMOVE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TCONTROL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, HB_FUNCNAME( TCONTROL ), NULL },
{ "CTOCHAR", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TBUTTON_KEYDOWN", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TBUTTON_KEYDOWN ), (PHB_DYNS) 1 },
{ "TBUTTON_INITIATE", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TBUTTON_INITIATE ), (PHB_DYNS) 1 },
{ "CREATE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "HCLASS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "__CLSINST", HB_FS_PUBLIC, HB_FUNCNAME( __CLSINST ), NULL },
{ "PCOUNT", HB_FS_PUBLIC, HB_FUNCNAME( PCOUNT ), NULL },
{ "CONSTRUCTORCALL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "HB_APARAMS", HB_FS_PUBLIC, HB_FUNCNAME( HB_APARAMS ), NULL },
{ "GETWNDDEFAULT", HB_FS_PUBLIC, HB_FUNCNAME( GETWNDDEFAULT ), NULL },
{ "OFONT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "MAX", HB_FS_PUBLIC, HB_FUNCNAME( MAX ), NULL },
{ "LEN", HB_FS_PUBLIC, HB_FUNCNAME( LEN ), NULL },
{ "_CCAPTION", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NTOP", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NLEFT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NBOTTOM", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NTOP", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NRIGHT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NLEFT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NHELPID", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_BACTION", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_OWND", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_OFONT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NSTYLE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NOR", HB_FS_PUBLIC, HB_FUNCNAME( NOR ), NULL },
{ "VALTYPE", HB_FS_PUBLIC, HB_FUNCNAME( VALTYPE ), NULL },
{ "_NID", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "GETNEWID", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_LDRAG", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_LCAPTURED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_CMSG", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_LUPDATE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_BWHEN", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_BVALID", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_LDEFAULT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_LCANCEL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_LPROCESSING", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "EMPTY", HB_FS_PUBLIC, HB_FUNCNAME( EMPTY ), NULL },
{ "HWND", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ADDCONTROL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "SETFONT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "DEFCONTROL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "CHECKDOTS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_HWND", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "LPROCESSING", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BACTION", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "EVAL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "LCANCEL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OWND", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "CLICK", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "GETFOCUS", HB_FS_PUBLIC, HB_FUNCNAME( GETFOCUS ), NULL },
{ "POSTMSG", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "LDEFAULT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "COORSUPDATE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "STR", HB_FS_PUBLIC, HB_FUNCNAME( STR ), NULL },
{ "CCAPTION", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NRIGHT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NBOTTOM", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "GOTFOCUS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "LOSTFOCUS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NLASTKEY", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "GOPREVCTRL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "GONEXTCTRL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "POSTMESSAGE", HB_FS_PUBLIC, HB_FUNCNAME( POSTMESSAGE ), NULL },
{ "KEYDOWN", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "INITIATE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "LAND", HB_FS_PUBLIC, HB_FUNCNAME( LAND ), NULL },
{ "GETWINDOWLONG", HB_FS_PUBLIC, HB_FUNCNAME( GETWINDOWLONG ), NULL },
{ "SETWINDOWTEXT", HB_FS_PUBLIC, HB_FUNCNAME( SETWINDOWTEXT ), NULL },
{ "ERRORSYS", HB_FS_PUBLIC, HB_FUNCNAME( ERRORSYS ), NULL },
{ "(_INITSTATICS)", HB_FS_INIT | HB_FS_EXIT, hb_INITSTATICS, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_BUTTON )

#if defined(HB_STATIC_STARTUP)
   #pragma startup hb_vm_SymbolInit_BUTTON
#elif defined(_MSC_VER)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_BUTTON = hb_vm_SymbolInit_BUTTON;
   #pragma data_seg()
#elif ! defined(__GNUC__)
   #pragma startup hb_vm_SymbolInit_BUTTON
#endif

HB_FUNC( TBUTTON )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 2, 255,	/* locals, params */
	HB_P_SFRAME, 86, 0,	/* symbol (_INITSTATICS) */
	HB_P_LOCALNEARSETINT, 2, 1, 0,	/* NSCOPE 1*/
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSE, 8, 2,	/* 520 (abs: 00535) */
	HB_P_MESSAGE, 1, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 2,	/* HBCLASS */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'T', 'B', 'u', 't', 't', 'o', 'n', 0, 
	HB_P_PUSHSYMNEAR, 3,	/* __CLS_PARAM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'T', 'C', 'o', 'n', 't', 'r', 'o', 'l', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_SENDSHORT, 2,
	HB_P_POPSTATIC, 1, 0,	/* S_OCLASS */
/* 00057 */ HB_P_BASELINE, 26, 0,	/* 26 */
	HB_P_MESSAGE, 4, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'b', 'A', 'c', 't', 'i', 'o', 'n', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00088 */ HB_P_LINEOFFSET, 1,	/* 27 */
	HB_P_MESSAGE, 4, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'l', 'D', 'e', 'f', 'a', 'u', 'l', 't', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00119 */ HB_P_LINEOFFSET, 2,	/* 28 */
	HB_P_MESSAGE, 4, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'l', 'P', 'r', 'o', 'c', 'e', 's', 's', 'i', 'n', 'g', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00153 */ HB_P_LINEOFFSET, 6,	/* 32 */
	HB_P_MESSAGE, 5, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'N', 'e', 'w', 0, 
	HB_P_PUSHSYMNEAR, 6,	/* TBUTTON_NEW */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_ADDINT, 8, 0,	/* 8*/
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00179 */ HB_P_LINEOFFSET, 9,	/* 35 */
	HB_P_MESSAGE, 5, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'R', 'e', 'D', 'e', 'f', 'i', 'n', 'e', 0, 
	HB_P_PUSHSYMNEAR, 7,	/* TBUTTON_REDEFINE */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_ADDINT, 8, 0,	/* 8*/
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00210 */ HB_P_LINEOFFSET, 11,	/* 37 */
	HB_P_MESSAGE, 5, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'C', 'l', 'i', 'c', 'k', 0, 
	HB_P_PUSHSYMNEAR, 8,	/* TBUTTON_CLICK */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00235 */ HB_P_LINEOFFSET, 13,	/* 39 */
	HB_P_MESSAGE, 5, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'c', 'G', 'e', 'n', 'P', 'R', 'G', 0, 
	HB_P_PUSHSYMNEAR, 9,	/* TBUTTON_CGENPRG */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00262 */ HB_P_LINEOFFSET, 15,	/* 41 */
	HB_P_MESSAGE, 5, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'G', 'o', 't', 'F', 'o', 'c', 'u', 's', 0, 
	HB_P_PUSHSYMNEAR, 10,	/* TBUTTON_GOTFOCUS */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00290 */ HB_P_LINEOFFSET, 17,	/* 43 */
	HB_P_MESSAGE, 5, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'L', 'o', 's', 't', 'F', 'o', 'c', 'u', 's', 0, 
	HB_P_PUSHSYMNEAR, 11,	/* TBUTTON_LOSTFOCUS */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00319 */ HB_P_LINEOFFSET, 20,	/* 46 */
	HB_P_MESSAGE, 12, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'M', 'o', 'u', 's', 'e', 'M', 'o', 'v', 'e', 0, 
	HB_P_PUSHBLOCK, 28, 0,	/* 28 */
	4, 0,	/* number of local parameters (4) */
	0, 0,	/* number of local variables (0) */
	HB_P_MESSAGE, 13, 0,	/* MOUSEMOVE */
	HB_P_MESSAGE, 14, 0,	/* TCONTROL */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 2,	/* codeblockvar2 */
	HB_P_PUSHLOCALNEAR, 3,	/* codeblockvar3 */
	HB_P_PUSHLOCALNEAR, 4,	/* codeblockvar4 */
	HB_P_SENDSHORT, 3,
	HB_P_POP,
	HB_P_PUSHNIL,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00373 */ HB_P_LINEOFFSET, 22,	/* 48 */
	HB_P_MESSAGE, 12, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'c', 'T', 'o', 'C', 'h', 'a', 'r', 0, 
	HB_P_PUSHBLOCK, 29, 0,	/* 29 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_MESSAGE, 15, 0,	/* CTOCHAR */
	HB_P_MESSAGE, 14, 0,	/* TCONTROL */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'B', 'U', 'T', 'T', 'O', 'N', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00426 */ HB_P_LINEOFFSET, 24,	/* 50 */
	HB_P_MESSAGE, 12, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'C', 'o', 'l', 'o', 'r', 's', 0, 
	HB_P_PUSHBLOCK, 9, 0,	/* 9 */
	2, 0,	/* number of local parameters (2) */
	0, 0,	/* number of local variables (0) */
	HB_P_ZERO,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00458 */ HB_P_LINEOFFSET, 26,	/* 52 */
	HB_P_MESSAGE, 5, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'K', 'e', 'y', 'D', 'o', 'w', 'n', 0, 
	HB_P_PUSHSYMNEAR, 16,	/* TBUTTON_KEYDOWN */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00485 */ HB_P_LINEOFFSET, 28,	/* 54 */
	HB_P_MESSAGE, 5, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'I', 'n', 'i', 't', 'i', 'a', 't', 'e', 0, 
	HB_P_PUSHSYMNEAR, 17,	/* TBUTTON_INITIATE */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00513 */ HB_P_LINEOFFSET, 30,	/* 56 */
	HB_P_MESSAGE, 18, 0,	/* CREATE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_MESSAGE, 19, 0,	/* HCLASS */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_SENDSHORT, 0,
	HB_P_CLASSSETMODULE,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00535) */
	HB_P_PUSHSYMNEAR, 20,	/* __CLSINST */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 19, 0,	/* HCLASS */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 1,	/* OCLASSINSTANCE */
	HB_P_PUSHSYMNEAR, 21,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 20,	/* 20 (abs: 00577) */
	HB_P_MESSAGE, 22, 0,	/* CONSTRUCTORCALL */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHLOCALNEAR, 1,	/* OCLASSINSTANCE */
	HB_P_PUSHSYMNEAR, 23,	/* HB_APARAMS */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_SENDSHORT, 2,
	HB_P_POP,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00577) */
	HB_P_PUSHLOCALNEAR, 1,	/* OCLASSINSTANCE */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00581 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TBUTTON_NEW )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 3, 18,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 19,	/* SELF */
/* 00006 */ HB_P_BASELINE, 74, 0,	/* 74 */
	HB_P_PUSHLOCALNEAR, 1,	/* NROW */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00018) */
	HB_P_ZERO,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00020) */
	HB_P_PUSHLOCALNEAR, 1,	/* NROW */
	HB_P_POPLOCALNEAR, 1,	/* NROW */
	HB_P_PUSHLOCALNEAR, 2,	/* NCOL */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00031) */
	HB_P_ZERO,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00033) */
	HB_P_PUSHLOCALNEAR, 2,	/* NCOL */
	HB_P_POPLOCALNEAR, 2,	/* NCOL */
	HB_P_PUSHLOCALNEAR, 3,	/* CCAPTION */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 15,	/* 15 (abs: 00054) */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'&', 'B', 'u', 't', 't', 'o', 'n', 0, 
	HB_P_MACROTEXT,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00056) */
	HB_P_PUSHLOCALNEAR, 3,	/* CCAPTION */
	HB_P_POPLOCALNEAR, 3,	/* CCAPTION */
	HB_P_PUSHLOCALNEAR, 4,	/* OWND */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 9,	/* 9 (abs: 00071) */
	HB_P_PUSHSYMNEAR, 24,	/* GETWNDDEFAULT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00073) */
	HB_P_PUSHLOCALNEAR, 4,	/* OWND */
	HB_P_POPLOCALNEAR, 4,	/* OWND */
	HB_P_PUSHLOCALNEAR, 9,	/* OFONT */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 00090) */
	HB_P_MESSAGE, 25, 0,	/* OFONT */
	HB_P_PUSHLOCALNEAR, 4,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00092) */
	HB_P_PUSHLOCALNEAR, 9,	/* OFONT */
	HB_P_POPLOCALNEAR, 9,	/* OFONT */
	HB_P_PUSHLOCALNEAR, 8,	/* NHELPID */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00104) */
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00106) */
	HB_P_PUSHLOCALNEAR, 8,	/* NHELPID */
	HB_P_POPLOCALNEAR, 8,	/* NHELPID */
	HB_P_PUSHLOCALNEAR, 10,	/* LDEFAULT */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00117) */
	HB_P_FALSE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00119) */
	HB_P_PUSHLOCALNEAR, 10,	/* LDEFAULT */
	HB_P_POPLOCALNEAR, 10,	/* LDEFAULT */
	HB_P_PUSHLOCALNEAR, 11,	/* LPIXEL */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00130) */
	HB_P_FALSE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00132) */
	HB_P_PUSHLOCALNEAR, 11,	/* LPIXEL */
	HB_P_POPLOCALNEAR, 11,	/* LPIXEL */
	HB_P_PUSHLOCALNEAR, 12,	/* LDESIGN */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00143) */
	HB_P_FALSE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00145) */
	HB_P_PUSHLOCALNEAR, 12,	/* LDESIGN */
	HB_P_POPLOCALNEAR, 12,	/* LDESIGN */
	HB_P_PUSHLOCALNEAR, 14,	/* LUPDATE */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00156) */
	HB_P_FALSE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00158) */
	HB_P_PUSHLOCALNEAR, 14,	/* LUPDATE */
	HB_P_POPLOCALNEAR, 14,	/* LUPDATE */
	HB_P_PUSHLOCALNEAR, 17,	/* LCANCEL */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00169) */
	HB_P_FALSE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00171) */
	HB_P_PUSHLOCALNEAR, 17,	/* LCANCEL */
	HB_P_POPLOCALNEAR, 17,	/* LCANCEL */
	HB_P_PUSHLOCALNEAR, 6,	/* NWIDTH */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 21,	/* 21 (abs: 00198) */
	HB_P_PUSHSYMNEAR, 26,	/* MAX */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 27,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* CCAPTION */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_MULT,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00200) */
	HB_P_PUSHLOCALNEAR, 6,	/* NWIDTH */
	HB_P_POPLOCALNEAR, 6,	/* NWIDTH */
	HB_P_PUSHLOCALNEAR, 7,	/* NHEIGHT */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00212) */
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00214) */
	HB_P_PUSHLOCALNEAR, 7,	/* NHEIGHT */
	HB_P_POPLOCALNEAR, 7,	/* NHEIGHT */
	HB_P_MESSAGE, 28, 0,	/* _CCAPTION */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_PUSHLOCALNEAR, 3,	/* CCAPTION */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00226 */ HB_P_LINEOFFSET, 17,	/* 91 */
	HB_P_MESSAGE, 29, 0,	/* _NTOP */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_PUSHLOCALNEAR, 1,	/* NROW */
	HB_P_PUSHLOCALNEAR, 11,	/* LPIXEL */
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00244) */
	HB_P_PUSHBYTE, 18,	/* 18 */
	HB_P_JUMPNEAR, 3,	/* 3 (abs: 00245) */
	HB_P_ONE,
	HB_P_MULT,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00249 */ HB_P_LINEOFFSET, 18,	/* 92 */
	HB_P_MESSAGE, 30, 0,	/* _NLEFT */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_PUSHLOCALNEAR, 2,	/* NCOL */
	HB_P_PUSHLOCALNEAR, 11,	/* LPIXEL */
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00267) */
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_JUMPNEAR, 3,	/* 3 (abs: 00268) */
	HB_P_ONE,
	HB_P_MULT,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00272 */ HB_P_LINEOFFSET, 19,	/* 93 */
	HB_P_MESSAGE, 31, 0,	/* _NBOTTOM */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_MESSAGE, 32, 0,	/* NTOP */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 7,	/* NHEIGHT */
	HB_P_PLUS,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00292 */ HB_P_LINEOFFSET, 20,	/* 94 */
	HB_P_MESSAGE, 33, 0,	/* _NRIGHT */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_MESSAGE, 34, 0,	/* NLEFT */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 6,	/* NWIDTH */
	HB_P_PLUS,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00312 */ HB_P_LINEOFFSET, 23,	/* 97 */
	HB_P_MESSAGE, 35, 0,	/* _NHELPID */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_PUSHLOCALNEAR, 8,	/* NHELPID */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00324 */ HB_P_LINEOFFSET, 24,	/* 98 */
	HB_P_MESSAGE, 36, 0,	/* _BACTION */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_PUSHLOCALNEAR, 5,	/* BACTION */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00336 */ HB_P_LINEOFFSET, 25,	/* 99 */
	HB_P_MESSAGE, 37, 0,	/* _OWND */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_PUSHLOCALNEAR, 4,	/* OWND */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00348 */ HB_P_LINEOFFSET, 26,	/* 100 */
	HB_P_MESSAGE, 38, 0,	/* _OFONT */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_PUSHLOCALNEAR, 9,	/* OFONT */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00360 */ HB_P_LINEOFFSET, 29,	/* 103 */
	HB_P_MESSAGE, 39, 0,	/* _NSTYLE */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_PUSHSYMNEAR, 40,	/* NOR */
	HB_P_PUSHNIL,
	HB_P_PUSHLONG, 0, 0, 0, 64,	/* 1073741824 */
	HB_P_PUSHLONG, 0, 0, 0, 16,	/* 268435456 */
	HB_P_PUSHLONG, 0, 0, 1, 0,	/* 65536 */
	HB_P_PUSHLOCALNEAR, 10,	/* LDEFAULT */
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00392) */
	HB_P_ONE,
	HB_P_JUMPNEAR, 3,	/* 3 (abs: 00393) */
	HB_P_ZERO,
	HB_P_PUSHLOCALNEAR, 12,	/* LDESIGN */
	HB_P_JUMPFALSENEAR, 9,	/* 9 (abs: 00404) */
	HB_P_PUSHLONG, 0, 0, 0, 4,	/* 67108864 */
	HB_P_JUMPNEAR, 3,	/* 3 (abs: 00405) */
	HB_P_ZERO,
	HB_P_FUNCTIONSHORT, 5,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00410 */ HB_P_LINEOFFSET, 31,	/* 105 */
	HB_P_PUSHSYMNEAR, 41,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 18,	/* NID */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'U', 0, 
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 21,	/* 21 (abs: 00445) */
/* 00426 */ HB_P_LINEOFFSET, 32,	/* 106 */
	HB_P_MESSAGE, 42, 0,	/* _NID */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_MESSAGE, 43, 0,	/* GETNEWID */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 14,	/* 14 (abs: 00457) */
/* 00445 */ HB_P_LINEOFFSET, 35,	/* 109 */
	HB_P_MESSAGE, 42, 0,	/* _NID */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_PUSHLOCALNEAR, 18,	/* NID */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00457 */ HB_P_LINEOFFSET, 37,	/* 111 */
	HB_P_MESSAGE, 44, 0,	/* _LDRAG */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_PUSHLOCALNEAR, 12,	/* LDESIGN */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00469 */ HB_P_LINEOFFSET, 38,	/* 112 */
	HB_P_MESSAGE, 45, 0,	/* _LCAPTURED */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_FALSE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00480 */ HB_P_LINEOFFSET, 39,	/* 113 */
	HB_P_MESSAGE, 46, 0,	/* _CMSG */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_PUSHLOCALNEAR, 13,	/* CMSG */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00492 */ HB_P_LINEOFFSET, 40,	/* 114 */
	HB_P_MESSAGE, 47, 0,	/* _LUPDATE */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_PUSHLOCALNEAR, 14,	/* LUPDATE */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00504 */ HB_P_LINEOFFSET, 41,	/* 115 */
	HB_P_MESSAGE, 48, 0,	/* _BWHEN */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_PUSHLOCALNEAR, 15,	/* BWHEN */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00516 */ HB_P_LINEOFFSET, 42,	/* 116 */
	HB_P_MESSAGE, 49, 0,	/* _BVALID */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_PUSHLOCALNEAR, 16,	/* BVALID */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00528 */ HB_P_LINEOFFSET, 43,	/* 117 */
	HB_P_MESSAGE, 50, 0,	/* _LDEFAULT */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_PUSHLOCALNEAR, 10,	/* LDEFAULT */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00540 */ HB_P_LINEOFFSET, 44,	/* 118 */
	HB_P_MESSAGE, 51, 0,	/* _LCANCEL */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_PUSHLOCALNEAR, 17,	/* LCANCEL */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00552 */ HB_P_LINEOFFSET, 45,	/* 119 */
	HB_P_MESSAGE, 52, 0,	/* _LPROCESSING */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_FALSE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00563 */ HB_P_LINEOFFSET, 47,	/* 121 */
	HB_P_PUSHSYMNEAR, 53,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 54, 0,	/* HWND */
	HB_P_PUSHLOCALNEAR, 4,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 57,	/* 57 (abs: 00635) */
/* 00580 */ HB_P_LINEOFFSET, 48,	/* 122 */
	HB_P_MESSAGE, 18, 0,	/* CREATE */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'B', 'U', 'T', 'T', 'O', 'N', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00599 */ HB_P_LINEOFFSET, 49,	/* 123 */
	HB_P_MESSAGE, 55, 0,	/* ADDCONTROL */
	HB_P_PUSHLOCALNEAR, 4,	/* OWND */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00611 */ HB_P_LINEOFFSET, 50,	/* 124 */
	HB_P_PUSHLOCALNEAR, 9,	/* OFONT */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 16,	/* 16 (abs: 00633) */
/* 00619 */ HB_P_LINEOFFSET, 51,	/* 125 */
	HB_P_MESSAGE, 56, 0,	/* SETFONT */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_PUSHLOCALNEAR, 9,	/* OFONT */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00633) */
	HB_P_JUMPNEAR, 14,	/* 14 (abs: 00647) */
/* 00635 */ HB_P_LINEOFFSET, 54,	/* 128 */
	HB_P_MESSAGE, 57, 0,	/* DEFCONTROL */
	HB_P_PUSHLOCALNEAR, 4,	/* OWND */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00647 */ HB_P_LINEOFFSET, 57,	/* 131 */
	HB_P_PUSHLOCALNEAR, 12,	/* LDESIGN */
	HB_P_JUMPFALSENEAR, 14,	/* 14 (abs: 00665) */
/* 00653 */ HB_P_LINEOFFSET, 58,	/* 132 */
	HB_P_MESSAGE, 58, 0,	/* CHECKDOTS */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00665) */
/* 00665 */ HB_P_LINEOFFSET, 61,	/* 135 */
	HB_P_PUSHLOCALNEAR, 19,	/* SELF */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00671 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TBUTTON_REDEFINE )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 10,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 11,	/* SELF */
/* 00006 */ HB_P_BASELINE, 142, 0,	/* 142 */
	HB_P_PUSHLOCALNEAR, 3,	/* OWND */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 9,	/* 9 (abs: 00022) */
	HB_P_PUSHSYMNEAR, 24,	/* GETWNDDEFAULT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00024) */
	HB_P_PUSHLOCALNEAR, 3,	/* OWND */
	HB_P_POPLOCALNEAR, 3,	/* OWND */
	HB_P_PUSHLOCALNEAR, 10,	/* LCANCEL */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00035) */
	HB_P_FALSE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00037) */
	HB_P_PUSHLOCALNEAR, 10,	/* LCANCEL */
	HB_P_POPLOCALNEAR, 10,	/* LCANCEL */
	HB_P_MESSAGE, 42, 0,	/* _NID */
	HB_P_PUSHLOCALNEAR, 11,	/* SELF */
	HB_P_PUSHLOCALNEAR, 1,	/* NID */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00049 */ HB_P_LINEOFFSET, 3,	/* 145 */
	HB_P_MESSAGE, 36, 0,	/* _BACTION */
	HB_P_PUSHLOCALNEAR, 11,	/* SELF */
	HB_P_PUSHLOCALNEAR, 2,	/* BACTION */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00061 */ HB_P_LINEOFFSET, 4,	/* 146 */
	HB_P_MESSAGE, 59, 0,	/* _HWND */
	HB_P_PUSHLOCALNEAR, 11,	/* SELF */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00072 */ HB_P_LINEOFFSET, 5,	/* 147 */
	HB_P_MESSAGE, 35, 0,	/* _NHELPID */
	HB_P_PUSHLOCALNEAR, 11,	/* SELF */
	HB_P_PUSHLOCALNEAR, 4,	/* NHELPID */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00084 */ HB_P_LINEOFFSET, 6,	/* 148 */
	HB_P_MESSAGE, 37, 0,	/* _OWND */
	HB_P_PUSHLOCALNEAR, 11,	/* SELF */
	HB_P_PUSHLOCALNEAR, 3,	/* OWND */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00096 */ HB_P_LINEOFFSET, 7,	/* 149 */
	HB_P_MESSAGE, 45, 0,	/* _LCAPTURED */
	HB_P_PUSHLOCALNEAR, 11,	/* SELF */
	HB_P_FALSE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00107 */ HB_P_LINEOFFSET, 8,	/* 150 */
	HB_P_MESSAGE, 44, 0,	/* _LDRAG */
	HB_P_PUSHLOCALNEAR, 11,	/* SELF */
	HB_P_FALSE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00118 */ HB_P_LINEOFFSET, 9,	/* 151 */
	HB_P_MESSAGE, 46, 0,	/* _CMSG */
	HB_P_PUSHLOCALNEAR, 11,	/* SELF */
	HB_P_PUSHLOCALNEAR, 5,	/* CMSG */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00130 */ HB_P_LINEOFFSET, 10,	/* 152 */
	HB_P_MESSAGE, 47, 0,	/* _LUPDATE */
	HB_P_PUSHLOCALNEAR, 11,	/* SELF */
	HB_P_PUSHLOCALNEAR, 6,	/* LUPDATE */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00142 */ HB_P_LINEOFFSET, 11,	/* 153 */
	HB_P_MESSAGE, 48, 0,	/* _BWHEN */
	HB_P_PUSHLOCALNEAR, 11,	/* SELF */
	HB_P_PUSHLOCALNEAR, 7,	/* BWHEN */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00154 */ HB_P_LINEOFFSET, 12,	/* 154 */
	HB_P_MESSAGE, 49, 0,	/* _BVALID */
	HB_P_PUSHLOCALNEAR, 11,	/* SELF */
	HB_P_PUSHLOCALNEAR, 8,	/* BVALID */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00166 */ HB_P_LINEOFFSET, 13,	/* 155 */
	HB_P_MESSAGE, 28, 0,	/* _CCAPTION */
	HB_P_PUSHLOCALNEAR, 11,	/* SELF */
	HB_P_PUSHLOCALNEAR, 9,	/* CPROMPT */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00178 */ HB_P_LINEOFFSET, 14,	/* 156 */
	HB_P_MESSAGE, 51, 0,	/* _LCANCEL */
	HB_P_PUSHLOCALNEAR, 11,	/* SELF */
	HB_P_PUSHLOCALNEAR, 10,	/* LCANCEL */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00190 */ HB_P_LINEOFFSET, 16,	/* 158 */
	HB_P_MESSAGE, 57, 0,	/* DEFCONTROL */
	HB_P_PUSHLOCALNEAR, 3,	/* OWND */
	HB_P_PUSHLOCALNEAR, 11,	/* SELF */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00202 */ HB_P_LINEOFFSET, 18,	/* 160 */
	HB_P_PUSHLOCALNEAR, 11,	/* SELF */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00208 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TBUTTON_CLICK )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 0,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 1,	/* SELF */
/* 00006 */ HB_P_BASELINE, 166, 0,	/* 166 */
	HB_P_MESSAGE, 60, 0,	/* LPROCESSING */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_NOT,
	HB_P_JUMPFALSE, 167, 0,	/* 167 (abs: 00184) */
/* 00020 */ HB_P_LINEOFFSET, 1,	/* 167 */
	HB_P_MESSAGE, 52, 0,	/* _LPROCESSING */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_TRUE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00031 */ HB_P_LINEOFFSET, 3,	/* 169 */
	HB_P_MESSAGE, 61, 0,	/* BACTION */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 19,	/* 19 (abs: 00061) */
/* 00044 */ HB_P_LINEOFFSET, 4,	/* 170 */
	HB_P_MESSAGE, 62, 0,	/* EVAL */
	HB_P_MESSAGE, 61, 0,	/* BACTION */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00061) */
/* 00061 */ HB_P_LINEOFFSET, 7,	/* 173 */
	HB_P_MESSAGE, 63, 0,	/* LCANCEL */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_NOT,
	HB_P_DUPLICATE,
	HB_P_JUMPFALSENEAR, 17,	/* 17 (abs: 00089) */
	HB_P_MESSAGE, 54, 0,	/* HWND */
	HB_P_MESSAGE, 64, 0,	/* OWND */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_ZERO,
	HB_P_NOTEQUAL,
	HB_P_AND,
	HB_P_JUMPFALSENEAR, 19,	/* 19 (abs: 00108) */
/* 00091 */ HB_P_LINEOFFSET, 8,	/* 174 */
	HB_P_MESSAGE, 65, 0,	/* CLICK */
	HB_P_MESSAGE, 14, 0,	/* TCONTROL */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00108) */
/* 00108 */ HB_P_LINEOFFSET, 12,	/* 178 */
	HB_P_PUSHSYMNEAR, 66,	/* GETFOCUS */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_MESSAGE, 54, 0,	/* HWND */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 19,	/* 19 (abs: 00142) */
/* 00125 */ HB_P_LINEOFFSET, 13,	/* 179 */
	HB_P_MESSAGE, 67, 0,	/* POSTMSG */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_PUSHINT, 244, 0,	/* 244 */
	HB_P_ONE,
	HB_P_ONE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
	HB_P_JUMPNEAR, 31,	/* 31 (abs: 00171) */
/* 00142 */ HB_P_LINEOFFSET, 15,	/* 181 */
	HB_P_MESSAGE, 68, 0,	/* LDEFAULT */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 19,	/* 19 (abs: 00171) */
/* 00154 */ HB_P_LINEOFFSET, 16,	/* 182 */
	HB_P_MESSAGE, 67, 0,	/* POSTMSG */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_PUSHINT, 244, 0,	/* 244 */
	HB_P_ZERO,
	HB_P_ONE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00171) */
/* 00171 */ HB_P_LINEOFFSET, 21,	/* 187 */
	HB_P_MESSAGE, 52, 0,	/* _LPROCESSING */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_FALSE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00184) */
/* 00184 */ HB_P_LINEOFFSET, 24,	/* 190 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00189 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TBUTTON_CGENPRG )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 2, 0,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 1,	/* SELF */
/* 00006 */ HB_P_BASELINE, 196, 0,	/* 196 */
	HB_P_LOCALNEARSETSTR, 2, 1, 0,	/* CPRG 1*/
	0, 
/* 00014 */ HB_P_LINEOFFSET, 2,	/* 198 */
	HB_P_MESSAGE, 69, 0,	/* COORSUPDATE */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00024 */ HB_P_LINEOFFSET, 10,	/* 206 */
	HB_P_PUSHLOCALNEAR, 2,	/* CPRG */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	13, 10, ' ', ' ', ' ', '@', ' ', 0, 
	HB_P_PUSHSYMNEAR, 70,	/* STR */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 32, 0,	/* NTOP */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	',', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 70,	/* STR */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 34, 0,	/* NLEFT */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	' ', 'B', 'U', 'T', 'T', 'O', 'N', ' ', 34, 0, 
	HB_P_PLUS,
	HB_P_MESSAGE, 71, 0,	/* CCAPTION */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	34, ' ', 'S', 'I', 'Z', 'E', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 70,	/* STR */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 72, 0,	/* NRIGHT */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 34, 0,	/* NLEFT */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MINUS,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	',', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 70,	/* STR */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 73, 0,	/* NBOTTOM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 32, 0,	/* NTOP */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MINUS,
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 17,	/* 17 */
	' ', 'P', 'I', 'X', 'E', 'L', ' ', 'O', 'F', ' ', 'o', 'W', 'n', 'd', ' ', ';', 0, 
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	13, 0, 
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	10, 0, 
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 43,	/* 43 */
	' ', ' ', ' ', ' ', ' ', ' ', 'A', 'C', 'T', 'I', 'O', 'N', ' ', 'M', 's', 'g', 'I', 'n', 'f', 'o', '(', ' ', 34, 'N', 'o', 't', ' ', 'd', 'e', 'f', 'i', 'n', 'e', 'd', ' ', 'y', 'e', 't', '!', 34, ' ', ')', 0, 
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	13, 0, 
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	10, 0, 
	HB_P_PLUS,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* CPRG */
/* 00253 */ HB_P_LINEOFFSET, 12,	/* 208 */
	HB_P_PUSHLOCALNEAR, 2,	/* CPRG */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00259 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TBUTTON_GOTFOCUS )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 1,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 2,	/* SELF */
/* 00006 */ HB_P_BASELINE, 215, 0,	/* 215 */
	HB_P_MESSAGE, 67, 0,	/* POSTMSG */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_PUSHINT, 244, 0,	/* 244 */
	HB_P_ONE,
	HB_P_ONE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
/* 00022 */ HB_P_LINEOFFSET, 2,	/* 217 */
	HB_P_MESSAGE, 74, 0,	/* GOTFOCUS */
	HB_P_MESSAGE, 14, 0,	/* TCONTROL */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 1,	/* HCTLLOST */
	HB_P_SENDSHORT, 1,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00040 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TBUTTON_LOSTFOCUS )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 0,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 1,	/* SELF */
/* 00006 */ HB_P_BASELINE, 224, 0,	/* 224 */
	HB_P_MESSAGE, 68, 0,	/* LDEFAULT */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 19,	/* 19 (abs: 00036) */
/* 00019 */ HB_P_LINEOFFSET, 1,	/* 225 */
	HB_P_MESSAGE, 67, 0,	/* POSTMSG */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_PUSHINT, 244, 0,	/* 244 */
	HB_P_ZERO,
	HB_P_ONE,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00036) */
/* 00036 */ HB_P_LINEOFFSET, 4,	/* 228 */
	HB_P_MESSAGE, 75, 0,	/* LOSTFOCUS */
	HB_P_MESSAGE, 14, 0,	/* TCONTROL */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00052 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TBUTTON_KEYDOWN )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 2,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 3,	/* SELF */
/* 00006 */ HB_P_BASELINE, 234, 0,	/* 234 */
	HB_P_MESSAGE, 76, 0,	/* _NLASTKEY */
	HB_P_MESSAGE, 64, 0,	/* OWND */
	HB_P_PUSHLOCALNEAR, 3,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 1,	/* NKEY */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00024 */ HB_P_LINEOFFSET, 3,	/* 237 */
	HB_P_PUSHLOCALNEAR, 1,	/* NKEY */
	HB_P_PUSHBYTE, 38,	/* 38 */
	HB_P_EXACTLYEQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 8,	/* 8 (abs: 00040) */
	HB_P_PUSHLOCALNEAR, 1,	/* NKEY */
	HB_P_PUSHBYTE, 37,	/* 37 */
	HB_P_EXACTLYEQUAL,
	HB_P_OR,
	HB_P_JUMPFALSENEAR, 31,	/* 31 (abs: 00071) */
/* 00042 */ HB_P_LINEOFFSET, 4,	/* 238 */
	HB_P_MESSAGE, 77, 0,	/* GOPREVCTRL */
	HB_P_MESSAGE, 64, 0,	/* OWND */
	HB_P_PUSHLOCALNEAR, 3,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 54, 0,	/* HWND */
	HB_P_PUSHLOCALNEAR, 3,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00064 */ HB_P_LINEOFFSET, 5,	/* 239 */
	HB_P_ZERO,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 78,	/* 78 (abs: 00147) */
	HB_P_PUSHLOCALNEAR, 1,	/* NKEY */
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_EXACTLYEQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 8,	/* 8 (abs: 00085) */
	HB_P_PUSHLOCALNEAR, 1,	/* NKEY */
	HB_P_PUSHBYTE, 39,	/* 39 */
	HB_P_EXACTLYEQUAL,
	HB_P_OR,
	HB_P_JUMPFALSENEAR, 31,	/* 31 (abs: 00116) */
/* 00087 */ HB_P_LINEOFFSET, 8,	/* 242 */
	HB_P_MESSAGE, 78, 0,	/* GONEXTCTRL */
	HB_P_MESSAGE, 64, 0,	/* OWND */
	HB_P_PUSHLOCALNEAR, 3,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 54, 0,	/* HWND */
	HB_P_PUSHLOCALNEAR, 3,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00109 */ HB_P_LINEOFFSET, 9,	/* 243 */
	HB_P_ZERO,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 33,	/* 33 (abs: 00147) */
	HB_P_PUSHLOCALNEAR, 1,	/* NKEY */
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 26,	/* 26 (abs: 00147) */
/* 00123 */ HB_P_LINEOFFSET, 12,	/* 246 */
	HB_P_PUSHSYMNEAR, 79,	/* POSTMESSAGE */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 54, 0,	/* HWND */
	HB_P_PUSHLOCALNEAR, 3,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHINT, 0, 8,	/* 2048 */
	HB_P_DOSHORT, 2,
/* 00140 */ HB_P_LINEOFFSET, 13,	/* 247 */
	HB_P_ZERO,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00147) */
/* 00147 */ HB_P_LINEOFFSET, 16,	/* 250 */
	HB_P_MESSAGE, 80, 0,	/* KEYDOWN */
	HB_P_MESSAGE, 14, 0,	/* TCONTROL */
	HB_P_PUSHLOCALNEAR, 3,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 1,	/* NKEY */
	HB_P_PUSHLOCALNEAR, 2,	/* NFLAGS */
	HB_P_SENDSHORT, 2,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00167 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TBUTTON_INITIATE )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 1,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 2,	/* SELF */
/* 00006 */ HB_P_BASELINE, 0, 1,	/* 256 */
	HB_P_MESSAGE, 81, 0,	/* INITIATE */
	HB_P_MESSAGE, 14, 0,	/* TCONTROL */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 1,	/* HDLG */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00024 */ HB_P_LINEOFFSET, 3,	/* 259 */
	HB_P_MESSAGE, 50, 0,	/* _LDEFAULT */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_PUSHSYMNEAR, 82,	/* LAND */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 83,	/* GETWINDOWLONG */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 54, 0,	/* HWND */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 240,	/* -16 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_ONE,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00054 */ HB_P_LINEOFFSET, 4,	/* 260 */
	HB_P_MESSAGE, 52, 0,	/* _LPROCESSING */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_FALSE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00065 */ HB_P_LINEOFFSET, 6,	/* 262 */
	HB_P_PUSHSYMNEAR, 53,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 71, 0,	/* CCAPTION */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 25,	/* 25 (abs: 00105) */
/* 00082 */ HB_P_LINEOFFSET, 7,	/* 263 */
	HB_P_PUSHSYMNEAR, 84,	/* SETWINDOWTEXT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 54, 0,	/* HWND */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 71, 0,	/* CCAPTION */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_DOSHORT, 2,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00105) */
/* 00105 */ HB_P_LINEOFFSET, 10,	/* 266 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00110 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

static HARBOUR hb_INITSTATICS( void )
{
   static const BYTE pcode[] =
   {
	HB_P_STATICS, 86, 0, 1, 0,	/* symbol (_INITSTATICS), 1 statics */
	HB_P_ENDPROC
/* 00006 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

