/*
 * xHarbour Compiler, build 82.0 (SimpLex)
 * Generated C source code from <c:/EDUCAR/program/EJEMPLO.prg>
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "c:/EDUCAR/program/EJEMPLO.prg"

HB_FUNC( EJEMPLOS );
HB_FUNC( TEST07 );
HB_FUNC( TEST06 );
HB_FUNC( TEST05 );
HB_FUNC( TEST03 );
HB_FUNC( TEST04 );
HB_FUNC( CONFIGURACHART );
HB_FUNC( TEST02 );
HB_FUNC( TEST01 );
extern HB_FUNC( MSGLIST );
extern HB_FUNC( MSGINFO );
extern HB_FUNC( TWINDOW );
extern HB_FUNC( TRMCHARTX );
extern HB_FUNC( LEN );
extern HB_FUNC( AEVAL );
extern HB_FUNC( TDIALOG );
extern HB_FUNC( TFOLDER );
extern HB_FUNC( VERSION );
extern HB_FUNC( ERRORSYS );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 5

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_EJEMPLO )
{ "EJEMPLOS", HB_FS_PUBLIC | HB_FS_FIRST, HB_FUNCNAME( EJEMPLOS ), (PHB_DYNS) 1 },
{ "MSGLIST", HB_FS_PUBLIC, HB_FUNCNAME( MSGLIST ), NULL },
{ "TEST01", HB_FS_PUBLIC, HB_FUNCNAME( TEST01 ), (PHB_DYNS) 1 },
{ "TEST02", HB_FS_PUBLIC, HB_FUNCNAME( TEST02 ), (PHB_DYNS) 1 },
{ "MSGINFO", HB_FS_PUBLIC, HB_FUNCNAME( MSGINFO ), NULL },
{ "TEST03", HB_FS_PUBLIC, HB_FUNCNAME( TEST03 ), (PHB_DYNS) 1 },
{ "TEST04", HB_FS_PUBLIC, HB_FUNCNAME( TEST04 ), (PHB_DYNS) 1 },
{ "TEST05", HB_FS_PUBLIC, HB_FUNCNAME( TEST05 ), (PHB_DYNS) 1 },
{ "TEST06", HB_FS_PUBLIC, HB_FUNCNAME( TEST06 ), (PHB_DYNS) 1 },
{ "TEST07", HB_FS_PUBLIC, HB_FUNCNAME( TEST07 ), (PHB_DYNS) 1 },
{ "NEW", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TWINDOW", HB_FS_PUBLIC, HB_FUNCNAME( TWINDOW ), NULL },
{ "TRMCHARTX", HB_FS_PUBLIC, HB_FUNCNAME( TRMCHARTX ), NULL },
{ "RMCFILE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_DATASTRING", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "GRIDLESSSERIES", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "REGION", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ARRAYTOSTRING", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ADDLABELAXIS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_TICKCOUNT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "LABELAXIS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "LEN", HB_FS_PUBLIC, HB_FUNCNAME( LEN ), NULL },
{ "_LEGENDSTRING", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "LEGEND", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "AEVAL", HB_FS_PUBLIC, HB_FUNCNAME( AEVAL ), NULL },
{ "SETCOLORVALUE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_OCLIENT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OCONTROL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ACTIVATE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BLCLICKED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BRCLICKED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BMOVED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BRESIZED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BPAINTED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BKEYDOWN", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BINIT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BLBUTTONUP", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "VERIFICA", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TDIALOG", HB_FS_PUBLIC, HB_FUNCNAME( TDIALOG ), NULL },
{ "SETTEXT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "REDEFINE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TFOLDER", HB_FS_PUBLIC, HB_FUNCNAME( TFOLDER ), NULL },
{ "ADIALOGS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "CONFIGURACHART", HB_FS_PUBLIC, HB_FUNCNAME( CONFIGURACHART ), (PHB_DYNS) 1 },
{ "_RMCFILE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_TITEL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "CAPTION", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "VERSION", HB_FS_PUBLIC, HB_FUNCNAME( VERSION ), NULL },
{ "_NWIDTH", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NHEIGHT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "LOK", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "END", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BARSERIES", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "LINESERIES", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_LABELTEXT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ADDREGION", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_SHOWBORDER", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_FOOTER", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ADDCAPTION", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ADDGRID", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "GRID", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_ASGRADIENT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_LEFT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_TOP", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_WIDTH", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_HEIGHT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ADDDATAAXIS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "DATAAXIS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_ALIGNMENT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_MINVALUE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_MAXVALUE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_FONTSIZE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_TEXTCOLOR", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_LINECOLOR", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_LINESTYLE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_DECIMALDIGITS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_AXISUNIT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_AXISTEXT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_AXISCOUNT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_TEXTALIGNMENT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ADDBARSERIES", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_SERIESTYPE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_SERIESSTYLE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_LUCENT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_COLOR", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_HORIZONTAL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_WHICHDATAAXIS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_VALUELABELON", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_POINTSPERCOLUMN", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_HATCHMODE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ADDLINESERIES", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_SYMBOLSTYLE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ERRORSYS", HB_FS_PUBLIC, HB_FUNCNAME( ERRORSYS ), NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_EJEMPLO )

#if defined(HB_STATIC_STARTUP)
   #pragma startup hb_vm_SymbolInit_EJEMPLO
#elif defined(_MSC_VER)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_EJEMPLO = hb_vm_SymbolInit_EJEMPLO;
   #pragma data_seg()
#elif ! defined(__GNUC__)
   #pragma startup hb_vm_SymbolInit_EJEMPLO
#endif

HB_FUNC( EJEMPLOS )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 23, 0,	/* 23 */
	HB_P_PUSHSYMNEAR, 1,	/* MSGLIST */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 14,	/* 14 */
	'E', 'n', ' ', 'u', 'n', 'a', ' ', 'W', 'i', 'n', 'd', 'o', 'w', 0, 
	HB_P_PUSHSTRSHORT, 34,	/* 34 */
	'E', 'n', ' ', 'U', 'n', 'a', ' ', 'W', 'i', 'n', 'd', 'o', 'w', ' ', 'p', 'a', 'r', 't', 'i', 'e', 'n', 'd', 'o', ' ', 'd', 'e', ' ', 'u', 'n', ' ', 'R', 'M', 'C', 0, 
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'E', 'n', ' ', 'u', 'n', ' ', 'D', 'i', 'a', 'l', 'o', 'g', 0, 
	HB_P_PUSHSTRSHORT, 28,	/* 28 */
	'E', 'n', ' ', 'u', 'n', ' ', 'D', 'i', 'a', 'l', 'o', 'g', ' ', 'D', 'e', 's', 'd', 'e', ' ', 'R', 'e', 'c', 'u', 'r', 's', 'o', 's', 0, 
	HB_P_PUSHSTRSHORT, 26,	/* 26 */
	'E', 'n', ' ', 'u', 'n', ' ', 'F', 'o', 'l', 'd', 'e', 'r', ' ', 'd', 'e', 's', 'd', 'e', ' ', 'c', 'o', 'd', 'i', 'g', 'o', 0, 
	HB_P_PUSHSTRSHORT, 28,	/* 28 */
	'E', 'n', ' ', 'u', 'n', ' ', 'F', 'o', 'l', 'd', 'e', 'r', ' ', 'd', 'e', 's', 'd', 'e', ' ', 'R', 'e', 'c', 'u', 'r', 's', 'o', 's', 0, 
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	'P', 'i', 'e', ' ', 'G', 'r', 'a', 'p', 'h', ' ', 'F', 'r', 'o', 'm', ' ', 'R', 'M', 'C', 0, 
	HB_P_ARRAYGEN, 7, 0,	/* 7 */
	HB_P_PUSHSTRSHORT, 51,	/* 51 */
	'T', 'R', 'M', 'C', 'h', 'a', 'r', 't', 'X', ' ', 'b', 'y', ' ', 'o', 'S', 'k', 'A', 'r', ' ', '[', 'S', 'e', 'l', 'e', 'c', 'c', 'i', 'o', 'n', 'a', ' ', 'e', 'l', ' ', 'T', 'e', 's', 't', ' ', 'a', ' ', 'E', 'j', 'e', 'c', 'u', 't', 'a', 'r', ']', 0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 1,	/* NOP */
/* 00245 */ HB_P_LINEOFFSET, 3,	/* 26 */
	HB_P_PUSHLOCALNEAR, 1,	/* NOP */
	HB_P_ONE,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 12,	/* 12 (abs: 00263) */
/* 00253 */ HB_P_LINEOFFSET, 4,	/* 27 */
	HB_P_PUSHSYMNEAR, 2,	/* TEST01 */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMP, 210, 0,	/* 210 (abs: 00470) */
/* 00263 */ HB_P_LINEOFFSET, 5,	/* 28 */
	HB_P_PUSHLOCALNEAR, 1,	/* NOP */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 12,	/* 12 (abs: 00282) */
/* 00272 */ HB_P_LINEOFFSET, 6,	/* 29 */
	HB_P_PUSHSYMNEAR, 3,	/* TEST02 */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMP, 191, 0,	/* 191 (abs: 00470) */
/* 00282 */ HB_P_LINEOFFSET, 7,	/* 30 */
	HB_P_FALSE,
	HB_P_JUMPFALSENEAR, 95,	/* 95 (abs: 00380) */
/* 00287 */ HB_P_LINEOFFSET, 8,	/* 31 */
	HB_P_PUSHSYMNEAR, 4,	/* MSGINFO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 82,	/* 82 */
	'T', 'u', ' ', 'v', 'e', 'r', 's', 'i', 'o', 'n', ' ', 'd', 'e', ' ', 'F', 'W', 'H', 13, 10, 'F', 'W', 'H', ' ', '2', '.', '3', 'b', ' ', '-', ' ', 'J', 'u', 'l', 'y', ' ', '2', '0', '0', '2', 13, 10, 'N', 'o', ' ', 'p', 'e', 'r', 'm', 'i', 't', 'e', ' ', 'c', 'o', 'l', 'g', 'a', 'r', ' ', 'A', 'c', 't', 'i', 'v', 'e', 'X', ' ', 's', 'o', 'b', 'r', 'e', ' ', 'd', 'i', 'a', 'l', 'o', 'g', 'o', 's', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMPNEAR, 92,	/* 92 (abs: 00470) */
/* 00380 */ HB_P_LINEOFFSET, 9,	/* 32 */
	HB_P_PUSHLOCALNEAR, 1,	/* NOP */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 00398) */
/* 00389 */ HB_P_LINEOFFSET, 10,	/* 33 */
	HB_P_PUSHSYMNEAR, 5,	/* TEST03 */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMPNEAR, 74,	/* 74 (abs: 00470) */
/* 00398 */ HB_P_LINEOFFSET, 11,	/* 34 */
	HB_P_PUSHLOCALNEAR, 1,	/* NOP */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 00416) */
/* 00407 */ HB_P_LINEOFFSET, 12,	/* 35 */
	HB_P_PUSHSYMNEAR, 6,	/* TEST04 */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMPNEAR, 56,	/* 56 (abs: 00470) */
/* 00416 */ HB_P_LINEOFFSET, 13,	/* 36 */
	HB_P_PUSHLOCALNEAR, 1,	/* NOP */
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 00434) */
/* 00425 */ HB_P_LINEOFFSET, 14,	/* 37 */
	HB_P_PUSHSYMNEAR, 7,	/* TEST05 */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMPNEAR, 38,	/* 38 (abs: 00470) */
/* 00434 */ HB_P_LINEOFFSET, 15,	/* 38 */
	HB_P_PUSHLOCALNEAR, 1,	/* NOP */
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 00452) */
/* 00443 */ HB_P_LINEOFFSET, 16,	/* 39 */
	HB_P_PUSHSYMNEAR, 8,	/* TEST06 */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMPNEAR, 20,	/* 20 (abs: 00470) */
/* 00452 */ HB_P_LINEOFFSET, 17,	/* 40 */
	HB_P_PUSHLOCALNEAR, 1,	/* NOP */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 00470) */
/* 00461 */ HB_P_LINEOFFSET, 18,	/* 41 */
	HB_P_PUSHSYMNEAR, 9,	/* TEST07 */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00470) */
/* 00470 */ HB_P_LINEOFFSET, 20,	/* 43 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00475 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( TEST07 )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 4, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 48, 0,	/* 48 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'u', 'n', 'o', 0, 
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'd', 'o', 's', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	't', 'r', 'e', 's', 0, 
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'c', 'u', 'a', 't', 'r', 'o', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'c', 'i', 'n', 'c', 'o', 0, 
	HB_P_ARRAYGEN, 5, 0,	/* 5 */
	HB_P_POPLOCALNEAR, 4,	/* ALEYEND */
/* 00047 */ HB_P_LINEOFFSET, 1,	/* 49 */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_PUSHBYTE, 18,	/* 18 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_ARRAYGEN, 5, 0,	/* 5 */
	HB_P_POPLOCALNEAR, 3,	/* ADATPLZ */
/* 00064 */ HB_P_LINEOFFSET, 3,	/* 51 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 11,	/* TWINDOW */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 21,
	HB_P_POPLOCALNEAR, 1,	/* OWND */
/* 00099 */ HB_P_LINEOFFSET, 5,	/* 53 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 12,	/* TRMCHARTX */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 1,
	HB_P_POPLOCALNEAR, 2,	/* OCHART */
/* 00115 */ HB_P_LINEOFFSET, 6,	/* 54 */
	HB_P_MESSAGE, 13, 0,	/* RMCFILE */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'p', 'i', 'e', '.', 'r', 'm', 'c', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00135 */ HB_P_LINEOFFSET, 7,	/* 55 */
	HB_P_MESSAGE, 14, 0,	/* _DATASTRING */
	HB_P_MESSAGE, 15, 0,	/* GRIDLESSSERIES */
	HB_P_MESSAGE, 16, 0,	/* REGION */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 17, 0,	/* ARRAYTOSTRING */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_PUSHLOCALNEAR, 3,	/* ADATPLZ */
	HB_P_SENDSHORT, 1,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00165 */ HB_P_LINEOFFSET, 8,	/* 56 */
	HB_P_MESSAGE, 18, 0,	/* ADDLABELAXIS */
	HB_P_MESSAGE, 16, 0,	/* REGION */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00181 */ HB_P_LINEOFFSET, 9,	/* 57 */
	HB_P_MESSAGE, 19, 0,	/* _TICKCOUNT */
	HB_P_MESSAGE, 20, 0,	/* LABELAXIS */
	HB_P_MESSAGE, 16, 0,	/* REGION */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSYMNEAR, 21,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* ADATPLZ */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00209 */ HB_P_LINEOFFSET, 10,	/* 58 */
	HB_P_MESSAGE, 22, 0,	/* _LEGENDSTRING */
	HB_P_MESSAGE, 23, 0,	/* LEGEND */
	HB_P_MESSAGE, 16, 0,	/* REGION */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 17, 0,	/* ARRAYTOSTRING */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_PUSHLOCALNEAR, 4,	/* ALEYEND */
	HB_P_SENDSHORT, 1,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00239 */ HB_P_LINEOFFSET, 11,	/* 59 */
	HB_P_PUSHSYMNEAR, 24,	/* AEVAL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* ALEYEND */
	HB_P_PUSHBLOCK, 31, 0,	/* 31 */
	2, 0,	/* number of local parameters (2) */
	1, 0,	/* number of local variables (1) */
	2, 0,	/* OCHART */
	HB_P_MESSAGE, 25, 0,	/* SETCOLORVALUE */
	HB_P_MESSAGE, 15, 0,	/* GRIDLESSSERIES */
	HB_P_MESSAGE, 16, 0,	/* REGION */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 2,	/* codeblockvar2 */
	HB_P_ZERO,
	HB_P_SENDSHORT, 2,
	HB_P_ENDBLOCK,
	HB_P_DOSHORT, 2,
/* 00279 */ HB_P_LINEOFFSET, 20,	/* 68 */
	HB_P_MESSAGE, 26, 0,	/* _OCLIENT */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_MESSAGE, 27, 0,	/* OCONTROL */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00296 */ HB_P_LINEOFFSET, 22,	/* 70 */
	HB_P_MESSAGE, 28, 0,	/* ACTIVATE */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 29, 0,	/* BLCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 30, 0,	/* BRCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 31, 0,	/* BMOVED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 32, 0,	/* BRESIZED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 33, 0,	/* BPAINTED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 34, 0,	/* BKEYDOWN */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 35, 0,	/* BINIT */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 36, 0,	/* BLBUTTONUP */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 19,
	HB_P_POP,
/* 00373 */ HB_P_LINEOFFSET, 23,	/* 71 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00378 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( TEST06 )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 5, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 80, 0,	/* 80 */
	HB_P_MESSAGE, 37, 0,	/* VERIFICA */
	HB_P_PUSHSYMNEAR, 12,	/* TRMCHARTX */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 45,	/* 45 (abs: 00062) */
/* 00019 */ HB_P_LINEOFFSET, 1,	/* 81 */
	HB_P_PUSHSYMNEAR, 4,	/* MSGINFO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 27,	/* 27 */
	'N', 'o', ' ', 't', 'i', 'e', 'n', 'e', 's', ' ', 'i', 'n', 's', 't', 'a', 'l', 'a', 'd', 'o', ' ', 'e', 'l', ' ', 'O', 'C', 'X', 0, 
	HB_P_DOSHORT, 1,
/* 00055 */ HB_P_LINEOFFSET, 2,	/* 82 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00062) */
/* 00062 */ HB_P_LINEOFFSET, 5,	/* 85 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 38,	/* TDIALOG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'D', 'L', '_', 'F', 'O', 'L', 'D', 'E', 'R', 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 19,
	HB_P_POPLOCALNEAR, 1,	/* ODLG */
/* 00106 */ HB_P_LINEOFFSET, 6,	/* 86 */
	HB_P_MESSAGE, 39, 0,	/* SETTEXT */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_PUSHSTRSHORT, 34,	/* 34 */
	'R', 'M', 'C', 'h', 'a', 'r', 't', ' ', 'E', 'n', ' ', 'F', 'o', 'l', 'd', 'e', 'r', 's', ' ', 'd', 'e', 's', 'd', 'e', ' ', 'r', 'e', 'c', 'u', 'r', 's', 'o', 's', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00152 */ HB_P_LINEOFFSET, 8,	/* 88 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 41,	/* TFOLDER */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 101,	/* 101 */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'C', 'h', 'a', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'F', 'o', 'l', 'd', 'e', 'r', 0, 
	HB_P_ARRAYGEN, 2, 0,	/* 2 */
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'D', 'L', '_', 'F', 'L', 'D', 'C', 'H', 'A', 'R', 'T', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'D', 'L', '_', 'F', 'L', 'D', 'F', 'L', 'D', 0, 
	HB_P_ARRAYGEN, 2, 0,	/* 2 */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 9,
	HB_P_POPLOCALNEAR, 2,	/* OFLD */
/* 00224 */ HB_P_LINEOFFSET, 9,	/* 89 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 12,	/* TRMCHARTX */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_MESSAGE, 42, 0,	/* ADIALOGS */
	HB_P_PUSHLOCALNEAR, 2,	/* OFLD */
	HB_P_SENDSHORT, 0,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 101,	/* 101 */
	HB_P_SENDSHORT, 2,
	HB_P_POPLOCALNEAR, 3,	/* OCHART */
/* 00249 */ HB_P_LINEOFFSET, 11,	/* 91 */
	HB_P_MESSAGE, 40, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 41,	/* TFOLDER */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 101,	/* 101 */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'C', 'h', 'a', 'r', 't', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'O', 't', 'r', 'o', 0, 
	HB_P_ARRAYGEN, 2, 0,	/* 2 */
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'D', 'L', '_', 'F', 'L', 'D', 'C', 'H', 'A', 'R', 'T', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_MESSAGE, 42, 0,	/* ADIALOGS */
	HB_P_PUSHLOCALNEAR, 2,	/* OFLD */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 9,
	HB_P_POPLOCALNEAR, 4,	/* OFLD2 */
/* 00315 */ HB_P_LINEOFFSET, 12,	/* 92 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 12,	/* TRMCHARTX */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_MESSAGE, 42, 0,	/* ADIALOGS */
	HB_P_PUSHLOCALNEAR, 4,	/* OFLD2 */
	HB_P_SENDSHORT, 0,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHBYTE, 101,	/* 101 */
	HB_P_SENDSHORT, 2,
	HB_P_POPLOCALNEAR, 5,	/* OCHART2 */
/* 00340 */ HB_P_LINEOFFSET, 16,	/* 96 */
	HB_P_MESSAGE, 28, 0,	/* ACTIVATE */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_MESSAGE, 29, 0,	/* BLCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 31, 0,	/* BMOVED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 33, 0,	/* BPAINTED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 50, 0,	/* 50 */
	1, 0,	/* number of local parameters (1) */
	4, 0,	/* number of local variables (4) */
	3, 0,	/* OCHART */
	2, 0,	/* OFLD */
	5, 0,	/* OCHART2 */
	4, 0,	/* OFLD2 */
	HB_P_PUSHSYMNEAR, 43,	/* CONFIGURACHART */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_MESSAGE, 42, 0,	/* ADIALOGS */
	HB_P_PUSHLOCALNEAR, 254,	/* localvar2 */
	HB_P_SENDSHORT, 0,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_TRUE,
	HB_P_DOSHORT, 3,
	HB_P_PUSHSYMNEAR, 43,	/* CONFIGURACHART */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 253,	/* localvar3 */
	HB_P_MESSAGE, 42, 0,	/* ADIALOGS */
	HB_P_PUSHLOCALNEAR, 252,	/* localvar4 */
	HB_P_SENDSHORT, 0,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_TRUE,
	HB_P_FUNCTIONSHORT, 3,
	HB_P_ENDBLOCK,
	HB_P_MESSAGE, 30, 0,	/* BRCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 9,
	HB_P_POP,
/* 00432 */ HB_P_LINEOFFSET, 17,	/* 97 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00437 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( TEST05 )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 5, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 106, 0,	/* 106 */
	HB_P_MESSAGE, 37, 0,	/* VERIFICA */
	HB_P_PUSHSYMNEAR, 12,	/* TRMCHARTX */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 45,	/* 45 (abs: 00062) */
/* 00019 */ HB_P_LINEOFFSET, 1,	/* 107 */
	HB_P_PUSHSYMNEAR, 4,	/* MSGINFO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 27,	/* 27 */
	'N', 'o', ' ', 't', 'i', 'e', 'n', 'e', 's', ' ', 'i', 'n', 's', 't', 'a', 'l', 'a', 'd', 'o', ' ', 'e', 'l', ' ', 'O', 'C', 'X', 0, 
	HB_P_DOSHORT, 1,
/* 00055 */ HB_P_LINEOFFSET, 2,	/* 108 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00062) */
/* 00062 */ HB_P_LINEOFFSET, 5,	/* 111 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 38,	/* TDIALOG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHINT, 88, 2,	/* 600 */
	HB_P_PUSHINT, 144, 1,	/* 400 */
	HB_P_SENDSHORT, 19,
	HB_P_POPLOCALNEAR, 1,	/* ODLG */
/* 00099 */ HB_P_LINEOFFSET, 7,	/* 113 */
	HB_P_MESSAGE, 39, 0,	/* SETTEXT */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_PUSHSTRSHORT, 26,	/* 26 */
	'C', 'h', 'a', 'r', 't', ' ', 'C', 'r', 'e', 'a', 'd', 'o', ' ', 'e', 'n', ' ', 'u', 'n', ' ', 'f', 'o', 'l', 'd', 'e', 'r', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00137 */ HB_P_LINEOFFSET, 8,	/* 114 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 41,	/* TFOLDER */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_PUSHINT, 34, 1,	/* 290 */
	HB_P_PUSHINT, 190, 0,	/* 190 */
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 15,
	HB_P_POPLOCALNEAR, 2,	/* OFLD */
/* 00175 */ HB_P_LINEOFFSET, 9,	/* 115 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 12,	/* TRMCHARTX */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_MESSAGE, 42, 0,	/* ADIALOGS */
	HB_P_PUSHLOCALNEAR, 2,	/* OFLD */
	HB_P_SENDSHORT, 0,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_POPLOCALNEAR, 3,	/* OCHART */
/* 00198 */ HB_P_LINEOFFSET, 11,	/* 117 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 41,	/* TFOLDER */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_PUSHNIL,
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_MESSAGE, 42, 0,	/* ADIALOGS */
	HB_P_PUSHLOCALNEAR, 2,	/* OFLD */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHINT, 14, 1,	/* 270 */
	HB_P_PUSHINT, 190, 0,	/* 190 */
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 15,
	HB_P_POPLOCALNEAR, 4,	/* OFLD2 */
/* 00242 */ HB_P_LINEOFFSET, 12,	/* 118 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 12,	/* TRMCHARTX */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_MESSAGE, 42, 0,	/* ADIALOGS */
	HB_P_PUSHLOCALNEAR, 4,	/* OFLD2 */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_POPLOCALNEAR, 5,	/* OCHART2 */
/* 00266 */ HB_P_LINEOFFSET, 15,	/* 121 */
	HB_P_MESSAGE, 28, 0,	/* ACTIVATE */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_MESSAGE, 29, 0,	/* BLCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 31, 0,	/* BMOVED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 33, 0,	/* BPAINTED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 51, 0,	/* 51 */
	1, 0,	/* number of local parameters (1) */
	4, 0,	/* number of local variables (4) */
	3, 0,	/* OCHART */
	2, 0,	/* OFLD */
	5, 0,	/* OCHART2 */
	4, 0,	/* OFLD2 */
	HB_P_PUSHSYMNEAR, 43,	/* CONFIGURACHART */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_MESSAGE, 42, 0,	/* ADIALOGS */
	HB_P_PUSHLOCALNEAR, 254,	/* localvar2 */
	HB_P_SENDSHORT, 0,
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_TRUE,
	HB_P_DOSHORT, 3,
	HB_P_PUSHSYMNEAR, 43,	/* CONFIGURACHART */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 253,	/* localvar3 */
	HB_P_MESSAGE, 42, 0,	/* ADIALOGS */
	HB_P_PUSHLOCALNEAR, 252,	/* localvar4 */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_TRUE,
	HB_P_FUNCTIONSHORT, 3,
	HB_P_ENDBLOCK,
	HB_P_MESSAGE, 30, 0,	/* BRCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 9,
	HB_P_POP,
/* 00359 */ HB_P_LINEOFFSET, 16,	/* 122 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00364 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( TEST03 )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 2, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 131, 0,	/* 131 */
	HB_P_MESSAGE, 37, 0,	/* VERIFICA */
	HB_P_PUSHSYMNEAR, 12,	/* TRMCHARTX */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 45,	/* 45 (abs: 00062) */
/* 00019 */ HB_P_LINEOFFSET, 1,	/* 132 */
	HB_P_PUSHSYMNEAR, 4,	/* MSGINFO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 27,	/* 27 */
	'N', 'o', ' ', 't', 'i', 'e', 'n', 'e', 's', ' ', 'i', 'n', 's', 't', 'a', 'l', 'a', 'd', 'o', ' ', 'e', 'l', ' ', 'O', 'C', 'X', 0, 
	HB_P_DOSHORT, 1,
/* 00055 */ HB_P_LINEOFFSET, 2,	/* 133 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00062) */
/* 00062 */ HB_P_LINEOFFSET, 5,	/* 136 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 38,	/* TDIALOG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHINT, 88, 2,	/* 600 */
	HB_P_PUSHINT, 144, 1,	/* 400 */
	HB_P_SENDSHORT, 19,
	HB_P_POPLOCALNEAR, 1,	/* ODLG */
/* 00099 */ HB_P_LINEOFFSET, 7,	/* 138 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 12,	/* TRMCHARTX */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 1,
	HB_P_POPLOCALNEAR, 2,	/* OCHART */
/* 00115 */ HB_P_LINEOFFSET, 9,	/* 140 */
	HB_P_MESSAGE, 28, 0,	/* ACTIVATE */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_MESSAGE, 29, 0,	/* BLCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 31, 0,	/* BMOVED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 33, 0,	/* BPAINTED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 22, 0,	/* 22 */
	1, 0,	/* number of local parameters (1) */
	2, 0,	/* number of local variables (2) */
	2, 0,	/* OCHART */
	1, 0,	/* ODLG */
	HB_P_PUSHSYMNEAR, 43,	/* CONFIGURACHART */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_PUSHLOCALNEAR, 254,	/* localvar2 */
	HB_P_TRUE,
	HB_P_FUNCTIONSHORT, 3,
	HB_P_ENDBLOCK,
	HB_P_MESSAGE, 30, 0,	/* BRCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 9,
	HB_P_POP,
/* 00179 */ HB_P_LINEOFFSET, 10,	/* 141 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00184 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( TEST04 )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 2, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 152, 0,	/* 152 */
	HB_P_MESSAGE, 37, 0,	/* VERIFICA */
	HB_P_PUSHSYMNEAR, 12,	/* TRMCHARTX */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_TRUE,
	HB_P_SENDSHORT, 1,
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 45,	/* 45 (abs: 00063) */
/* 00020 */ HB_P_LINEOFFSET, 1,	/* 153 */
	HB_P_PUSHSYMNEAR, 4,	/* MSGINFO */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 27,	/* 27 */
	'N', 'o', ' ', 't', 'i', 'e', 'n', 'e', 's', ' ', 'i', 'n', 's', 't', 'a', 'l', 'a', 'd', 'o', ' ', 'e', 'l', ' ', 'O', 'C', 'X', 0, 
	HB_P_DOSHORT, 1,
/* 00056 */ HB_P_LINEOFFSET, 2,	/* 154 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00063) */
/* 00063 */ HB_P_LINEOFFSET, 5,	/* 157 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 38,	/* TDIALOG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'D', 'L', '_', 'R', 'M', 'C', 'H', 'A', 'R', 'T', 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 19,
	HB_P_POPLOCALNEAR, 1,	/* ODLG */
/* 00108 */ HB_P_LINEOFFSET, 7,	/* 159 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 12,	/* TRMCHARTX */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_PUSHBYTE, 101,	/* 101 */
	HB_P_SENDSHORT, 2,
	HB_P_POPLOCALNEAR, 2,	/* OCHART */
/* 00126 */ HB_P_LINEOFFSET, 9,	/* 161 */
	HB_P_MESSAGE, 28, 0,	/* ACTIVATE */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_MESSAGE, 29, 0,	/* BLCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 31, 0,	/* BMOVED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 33, 0,	/* BPAINTED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 22, 0,	/* 22 */
	1, 0,	/* number of local parameters (1) */
	2, 0,	/* number of local variables (2) */
	2, 0,	/* OCHART */
	1, 0,	/* ODLG */
	HB_P_PUSHSYMNEAR, 43,	/* CONFIGURACHART */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_PUSHLOCALNEAR, 254,	/* localvar2 */
	HB_P_FALSE,
	HB_P_FUNCTIONSHORT, 3,
	HB_P_ENDBLOCK,
	HB_P_MESSAGE, 30, 0,	/* BRCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 9,
	HB_P_POP,
/* 00190 */ HB_P_LINEOFFSET, 10,	/* 162 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00195 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( CONFIGURACHART )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 0, 3,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 167, 0,	/* 167 */
	HB_P_MESSAGE, 28, 0,	/* ACTIVATE */
	HB_P_PUSHLOCALNEAR, 1,	/* OCHART */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00014 */ HB_P_LINEOFFSET, 1,	/* 168 */
	HB_P_MESSAGE, 44, 0,	/* _RMCFILE */
	HB_P_PUSHLOCALNEAR, 1,	/* OCHART */
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'1', '0', 'B', 'i', 'g', 'c', 'o', 'm', '.', 'r', 'm', 'c', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00039 */ HB_P_LINEOFFSET, 2,	/* 169 */
	HB_P_MESSAGE, 45, 0,	/* _TITEL */
	HB_P_MESSAGE, 46, 0,	/* CAPTION */
	HB_P_MESSAGE, 16, 0,	/* REGION */
	HB_P_PUSHLOCALNEAR, 1,	/* OCHART */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSTRSHORT, 26,	/* 26 */
	'T', 'R', 'M', 'C', 'h', 'a', 'r', 't', 'X', ' ', 'T', 'e', 's', 't', ' ', 'B', 'y', ' ', 'o', 'S', 'k', 'A', 'r', ' ', '[', 0, 
	HB_P_PUSHSYMNEAR, 47,	/* VERSION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	']', 0, 
	HB_P_PLUS,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00099 */ HB_P_LINEOFFSET, 3,	/* 170 */
	HB_P_PUSHLOCALNEAR, 3,	/* LADJUST */
	HB_P_JUMPFALSENEAR, 40,	/* 40 (abs: 00143) */
/* 00105 */ HB_P_LINEOFFSET, 4,	/* 171 */
	HB_P_MESSAGE, 48, 0,	/* _NWIDTH */
	HB_P_MESSAGE, 27, 0,	/* OCONTROL */
	HB_P_PUSHLOCALNEAR, 1,	/* OCHART */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHINT, 68, 2,	/* 580 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00123 */ HB_P_LINEOFFSET, 5,	/* 172 */
	HB_P_MESSAGE, 49, 0,	/* _NHEIGHT */
	HB_P_MESSAGE, 27, 0,	/* OCONTROL */
	HB_P_PUSHLOCALNEAR, 1,	/* OCHART */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHINT, 124, 1,	/* 380 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00143) */
/* 00143 */ HB_P_LINEOFFSET, 7,	/* 174 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00148 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( TEST02 )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 2, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 179, 0,	/* 179 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 11,	/* TWINDOW */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 21,
	HB_P_POPLOCALNEAR, 1,	/* OWND */
/* 00039 */ HB_P_LINEOFFSET, 1,	/* 180 */
	HB_P_MESSAGE, 39, 0,	/* SETTEXT */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_PUSHSTRSHORT, 57,	/* 57 */
	'R', 'M', 'C', 'h', 'a', 'r', 't', 'X', ' ', 'T', 'e', 's', 't', ' ', 'B', 'y', ' ', 'o', 'S', 'k', 'A', 'r', ' ', '[', ' ', 'C', 'a', 'r', 'g', 'a', 'n', 'd', 'o', ' ', 'e', 'l', ' ', 'G', 'r', 'a', 'f', 'i', 'c', 'o', ' ', 'd', 'e', ' ', 'u', 'n', ' ', 'r', 'm', 'c', ' ', ']', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00108 */ HB_P_LINEOFFSET, 4,	/* 183 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 12,	/* TRMCHARTX */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 1,
	HB_P_POPLOCALNEAR, 2,	/* OCHART */
/* 00124 */ HB_P_LINEOFFSET, 7,	/* 186 */
	HB_P_MESSAGE, 50, 0,	/* LOK */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_SENDSHORT, 0,
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 19,	/* 19 (abs: 00153) */
/* 00136 */ HB_P_LINEOFFSET, 8,	/* 187 */
	HB_P_MESSAGE, 51, 0,	/* END */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00146 */ HB_P_LINEOFFSET, 9,	/* 188 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00153) */
/* 00153 */ HB_P_LINEOFFSET, 13,	/* 192 */
	HB_P_MESSAGE, 44, 0,	/* _RMCFILE */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'1', '0', 'B', 'i', 'g', 'c', 'o', 'm', '.', 'r', 'm', 'c', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00178 */ HB_P_LINEOFFSET, 16,	/* 195 */
	HB_P_MESSAGE, 45, 0,	/* _TITEL */
	HB_P_MESSAGE, 46, 0,	/* CAPTION */
	HB_P_MESSAGE, 16, 0,	/* REGION */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSTRSHORT, 26,	/* 26 */
	'T', 'R', 'M', 'C', 'h', 'a', 'r', 't', 'X', ' ', 'T', 'e', 's', 't', ' ', 'B', 'y', ' ', 'o', 'S', 'k', 'A', 'r', ' ', '[', 0, 
	HB_P_PUSHSYMNEAR, 47,	/* VERSION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	']', 0, 
	HB_P_PLUS,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00238 */ HB_P_LINEOFFSET, 19,	/* 198 */
	HB_P_MESSAGE, 14, 0,	/* _DATASTRING */
	HB_P_MESSAGE, 52, 0,	/* BARSERIES */
	HB_P_MESSAGE, 16, 0,	/* REGION */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_MESSAGE, 17, 0,	/* ARRAYTOSTRING */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_PUSHLONG, 168, 210, 2, 0,	/* 185000 */
	HB_P_PUSHLONG, 164, 44, 2, 0,	/* 142500 */
	HB_P_PUSHLONG, 48, 230, 2, 0,	/* 190000 */
	HB_P_PUSHLONG, 160, 253, 2, 0,	/* 196000 */
	HB_P_PUSHLONG, 192, 212, 1, 0,	/* 120000 */
	HB_P_PUSHLONG, 112, 130, 3, 0,	/* 230000 */
	HB_P_PUSHLONG, 224, 34, 2, 0,	/* 140000 */
	HB_P_PUSHLONG, 192, 206, 2, 0,	/* 184000 */
	HB_P_PUSHLONG, 156, 87, 2, 0,	/* 153500 */
	HB_P_PUSHLONG, 0, 113, 2, 0,	/* 160000 */
	HB_P_PUSHLONG, 224, 34, 2, 0,	/* 140000 */
	HB_P_PUSHLONG, 192, 81, 2, 0,	/* 152000 */
	HB_P_ARRAYGEN, 12, 0,	/* 12 */
	HB_P_SENDSHORT, 1,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00330 */ HB_P_LINEOFFSET, 22,	/* 201 */
	HB_P_MESSAGE, 14, 0,	/* _DATASTRING */
	HB_P_MESSAGE, 53, 0,	/* LINESERIES */
	HB_P_MESSAGE, 16, 0,	/* REGION */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_MESSAGE, 17, 0,	/* ARRAYTOSTRING */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_PUSHBYTE, 18,	/* 18 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_PUSHBYTE, 22,	/* 22 */
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_ARRAYGEN, 12, 0,	/* 12 */
	HB_P_SENDSHORT, 1,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00386 */ HB_P_LINEOFFSET, 25,	/* 204 */
	HB_P_MESSAGE, 19, 0,	/* _TICKCOUNT */
	HB_P_MESSAGE, 20, 0,	/* LABELAXIS */
	HB_P_MESSAGE, 16, 0,	/* REGION */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00409 */ HB_P_LINEOFFSET, 28,	/* 207 */
	HB_P_MESSAGE, 54, 0,	/* _LABELTEXT */
	HB_P_MESSAGE, 20, 0,	/* LABELAXIS */
	HB_P_MESSAGE, 16, 0,	/* REGION */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'U', 'n', 'o', ' ', 'M', 'a', 's', '*', 'O', 't', 'r', 'o', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00445 */ HB_P_LINEOFFSET, 31,	/* 210 */
	HB_P_MESSAGE, 26, 0,	/* _OCLIENT */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_MESSAGE, 27, 0,	/* OCONTROL */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00462 */ HB_P_LINEOFFSET, 44,	/* 223 */
	HB_P_MESSAGE, 28, 0,	/* ACTIVATE */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 29, 0,	/* BLCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 30, 0,	/* BRCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 31, 0,	/* BMOVED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 32, 0,	/* BRESIZED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 33, 0,	/* BPAINTED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 34, 0,	/* BKEYDOWN */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 35, 0,	/* BINIT */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 36, 0,	/* BLBUTTONUP */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 19,
	HB_P_POP,
/* 00539 */ HB_P_LINEOFFSET, 45,	/* 224 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00544 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( TEST01 )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 9, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 230, 0,	/* 230 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 11,	/* TWINDOW */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 21,
	HB_P_POPLOCALNEAR, 1,	/* OWND */
/* 00039 */ HB_P_LINEOFFSET, 2,	/* 232 */
	HB_P_MESSAGE, 39, 0,	/* SETTEXT */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_PUSHSTRSHORT, 70,	/* 70 */
	'R', 'M', 'C', 'h', 'a', 'r', 't', 'X', ' ', 'T', 'e', 's', 't', ' ', 'B', 'y', ' ', 'o', 'S', 'k', 'A', 'r', ' ', '[', ' ', 'C', 'r', 'e', 'a', 'n', 'd', 'o', ' ', 'e', 'l', ' ', 'g', 'r', 'a', 'f', 'i', 'c', 'o', ' ', 't', 'o', 't', 'a', 'l', 'm', 'e', 'n', 't', 'e', ' ', 'd', 'e', 's', 'd', 'e', ' ', 'c', 'o', 'd', 'i', 'g', 'o', ' ', ']', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00121 */ HB_P_LINEOFFSET, 4,	/* 234 */
	HB_P_MESSAGE, 10, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 12,	/* TRMCHARTX */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 1,
	HB_P_POPLOCALNEAR, 2,	/* OCHART */
/* 00137 */ HB_P_LINEOFFSET, 5,	/* 235 */
	HB_P_MESSAGE, 50, 0,	/* LOK */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_SENDSHORT, 0,
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 19,	/* 19 (abs: 00166) */
/* 00149 */ HB_P_LINEOFFSET, 6,	/* 236 */
	HB_P_MESSAGE, 51, 0,	/* END */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00159 */ HB_P_LINEOFFSET, 7,	/* 237 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00166) */
/* 00166 */ HB_P_LINEOFFSET, 10,	/* 240 */
	HB_P_MESSAGE, 55, 0,	/* ADDREGION */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00176 */ HB_P_LINEOFFSET, 11,	/* 241 */
	HB_P_MESSAGE, 16, 0,	/* REGION */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_POPLOCALNEAR, 3,	/* OREGION */
/* 00188 */ HB_P_LINEOFFSET, 12,	/* 242 */
	HB_P_MESSAGE, 56, 0,	/* _SHOWBORDER */
	HB_P_PUSHLOCALNEAR, 3,	/* OREGION */
	HB_P_TRUE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00199 */ HB_P_LINEOFFSET, 13,	/* 243 */
	HB_P_MESSAGE, 57, 0,	/* _FOOTER */
	HB_P_PUSHLOCALNEAR, 3,	/* OREGION */
	HB_P_PUSHSTRSHORT, 23,	/* 23 */
	'h', 't', 't', 'p', ':', '/', '/', 'o', 's', 'k', 'a', 'r', '.', 's', 'y', 't', 'e', 's', '.', 'n', 'e', 't', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00234 */ HB_P_LINEOFFSET, 14,	/* 244 */
	HB_P_MESSAGE, 58, 0,	/* ADDCAPTION */
	HB_P_PUSHLOCALNEAR, 3,	/* OREGION */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00244 */ HB_P_LINEOFFSET, 15,	/* 245 */
	HB_P_MESSAGE, 45, 0,	/* _TITEL */
	HB_P_MESSAGE, 46, 0,	/* CAPTION */
	HB_P_PUSHLOCALNEAR, 3,	/* OREGION */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSTRSHORT, 26,	/* 26 */
	'T', 'R', 'M', 'C', 'h', 'a', 'r', 't', 'X', ' ', 'T', 'e', 's', 't', ' ', 'B', 'y', ' ', 'o', 'S', 'k', 'A', 'r', ' ', '[', 0, 
	HB_P_PUSHSYMNEAR, 47,	/* VERSION */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	']', 0, 
	HB_P_PLUS,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00298 */ HB_P_LINEOFFSET, 17,	/* 247 */
	HB_P_MESSAGE, 59, 0,	/* ADDGRID */
	HB_P_PUSHLOCALNEAR, 3,	/* OREGION */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00308 */ HB_P_LINEOFFSET, 18,	/* 248 */
	HB_P_MESSAGE, 60, 0,	/* GRID */
	HB_P_PUSHLOCALNEAR, 3,	/* OREGION */
	HB_P_SENDSHORT, 0,
	HB_P_POPLOCALNEAR, 4,	/* OGRID */
/* 00319 */ HB_P_LINEOFFSET, 19,	/* 249 */
	HB_P_MESSAGE, 61, 0,	/* _ASGRADIENT */
	HB_P_PUSHLOCALNEAR, 4,	/* OGRID */
	HB_P_TRUE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00330 */ HB_P_LINEOFFSET, 20,	/* 250 */
	HB_P_MESSAGE, 62, 0,	/* _LEFT */
	HB_P_PUSHLOCALNEAR, 4,	/* OGRID */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00341 */ HB_P_LINEOFFSET, 21,	/* 251 */
	HB_P_MESSAGE, 63, 0,	/* _TOP */
	HB_P_PUSHLOCALNEAR, 4,	/* OGRID */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00352 */ HB_P_LINEOFFSET, 22,	/* 252 */
	HB_P_MESSAGE, 64, 0,	/* _WIDTH */
	HB_P_PUSHLOCALNEAR, 4,	/* OGRID */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00363 */ HB_P_LINEOFFSET, 23,	/* 253 */
	HB_P_MESSAGE, 65, 0,	/* _HEIGHT */
	HB_P_PUSHLOCALNEAR, 4,	/* OGRID */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00374 */ HB_P_LINEOFFSET, 25,	/* 255 */
	HB_P_MESSAGE, 66, 0,	/* ADDDATAAXIS */
	HB_P_PUSHLOCALNEAR, 3,	/* OREGION */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00384 */ HB_P_LINEOFFSET, 26,	/* 256 */
	HB_P_MESSAGE, 67, 0,	/* DATAAXIS */
	HB_P_PUSHLOCALNEAR, 3,	/* OREGION */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_POPLOCALNEAR, 5,	/* ODATAAXIS */
/* 00396 */ HB_P_LINEOFFSET, 27,	/* 257 */
	HB_P_MESSAGE, 68, 0,	/* _ALIGNMENT */
	HB_P_PUSHLOCALNEAR, 5,	/* ODATAAXIS */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00408 */ HB_P_LINEOFFSET, 28,	/* 258 */
	HB_P_MESSAGE, 69, 0,	/* _MINVALUE */
	HB_P_PUSHLOCALNEAR, 5,	/* ODATAAXIS */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00419 */ HB_P_LINEOFFSET, 29,	/* 259 */
	HB_P_MESSAGE, 70, 0,	/* _MAXVALUE */
	HB_P_PUSHLOCALNEAR, 5,	/* ODATAAXIS */
	HB_P_PUSHINT, 16, 39,	/* 10000 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00432 */ HB_P_LINEOFFSET, 30,	/* 260 */
	HB_P_MESSAGE, 19, 0,	/* _TICKCOUNT */
	HB_P_PUSHLOCALNEAR, 5,	/* ODATAAXIS */
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00444 */ HB_P_LINEOFFSET, 31,	/* 261 */
	HB_P_MESSAGE, 71, 0,	/* _FONTSIZE */
	HB_P_PUSHLOCALNEAR, 5,	/* ODATAAXIS */
	HB_P_PUSHBYTE, 8,	/* 8 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00456 */ HB_P_LINEOFFSET, 32,	/* 262 */
	HB_P_MESSAGE, 72, 0,	/* _TEXTCOLOR */
	HB_P_PUSHLOCALNEAR, 5,	/* ODATAAXIS */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00467 */ HB_P_LINEOFFSET, 33,	/* 263 */
	HB_P_MESSAGE, 73, 0,	/* _LINECOLOR */
	HB_P_PUSHLOCALNEAR, 5,	/* ODATAAXIS */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00478 */ HB_P_LINEOFFSET, 34,	/* 264 */
	HB_P_MESSAGE, 74, 0,	/* _LINESTYLE */
	HB_P_PUSHLOCALNEAR, 5,	/* ODATAAXIS */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00489 */ HB_P_LINEOFFSET, 35,	/* 265 */
	HB_P_MESSAGE, 75, 0,	/* _DECIMALDIGITS */
	HB_P_PUSHLOCALNEAR, 5,	/* ODATAAXIS */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00500 */ HB_P_LINEOFFSET, 36,	/* 266 */
	HB_P_MESSAGE, 76, 0,	/* _AXISUNIT */
	HB_P_PUSHLOCALNEAR, 5,	/* ODATAAXIS */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00513 */ HB_P_LINEOFFSET, 37,	/* 267 */
	HB_P_MESSAGE, 77, 0,	/* _AXISTEXT */
	HB_P_PUSHLOCALNEAR, 5,	/* ODATAAXIS */
	HB_P_PUSHSTRSHORT, 31,	/* 31 */
	'C', 'l', 'o', 's', 'i', 'n', 'g', ' ', 'I', 'n', 'd', 'e', 'x', ' ', '(', 'L', 'i', 'n', 'e', ' ', 's', 'e', 'r', 'i', 'e', 's', ')', 92, '1', '1', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00556 */ HB_P_LINEOFFSET, 39,	/* 269 */
	HB_P_MESSAGE, 66, 0,	/* ADDDATAAXIS */
	HB_P_PUSHLOCALNEAR, 3,	/* OREGION */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00566 */ HB_P_LINEOFFSET, 40,	/* 270 */
	HB_P_MESSAGE, 67, 0,	/* DATAAXIS */
	HB_P_PUSHLOCALNEAR, 3,	/* OREGION */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_SENDSHORT, 1,
	HB_P_POPLOCALNEAR, 6,	/* ODATAAXIS2 */
/* 00579 */ HB_P_LINEOFFSET, 41,	/* 271 */
	HB_P_MESSAGE, 68, 0,	/* _ALIGNMENT */
	HB_P_PUSHLOCALNEAR, 6,	/* ODATAAXIS2 */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00591 */ HB_P_LINEOFFSET, 42,	/* 272 */
	HB_P_MESSAGE, 69, 0,	/* _MINVALUE */
	HB_P_PUSHLOCALNEAR, 6,	/* ODATAAXIS2 */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00602 */ HB_P_LINEOFFSET, 43,	/* 273 */
	HB_P_MESSAGE, 70, 0,	/* _MAXVALUE */
	HB_P_PUSHLOCALNEAR, 6,	/* ODATAAXIS2 */
	HB_P_PUSHINT, 16, 39,	/* 10000 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00615 */ HB_P_LINEOFFSET, 44,	/* 274 */
	HB_P_MESSAGE, 75, 0,	/* _DECIMALDIGITS */
	HB_P_PUSHLOCALNEAR, 6,	/* ODATAAXIS2 */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00626 */ HB_P_LINEOFFSET, 45,	/* 275 */
	HB_P_MESSAGE, 76, 0,	/* _AXISUNIT */
	HB_P_PUSHLOCALNEAR, 6,	/* ODATAAXIS2 */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00639 */ HB_P_LINEOFFSET, 46,	/* 276 */
	HB_P_MESSAGE, 77, 0,	/* _AXISTEXT */
	HB_P_PUSHLOCALNEAR, 6,	/* ODATAAXIS2 */
	HB_P_PUSHSTRSHORT, 30,	/* 30 */
	'S', 'h', 'a', 'r', 'e', ' ', 'v', 'o', 'l', 'u', 'm', 'e', 's', ' ', '(', 'B', 'a', 'r', ' ', 's', 'e', 'r', 'i', 'e', 's', ')', 92, '1', '1', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00681 */ HB_P_LINEOFFSET, 48,	/* 278 */
	HB_P_MESSAGE, 18, 0,	/* ADDLABELAXIS */
	HB_P_PUSHLOCALNEAR, 3,	/* OREGION */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00691 */ HB_P_LINEOFFSET, 49,	/* 279 */
	HB_P_MESSAGE, 20, 0,	/* LABELAXIS */
	HB_P_PUSHLOCALNEAR, 3,	/* OREGION */
	HB_P_SENDSHORT, 0,
	HB_P_POPLOCALNEAR, 7,	/* OLABELAXIS */
/* 00702 */ HB_P_LINEOFFSET, 50,	/* 280 */
	HB_P_MESSAGE, 78, 0,	/* _AXISCOUNT */
	HB_P_PUSHLOCALNEAR, 7,	/* OLABELAXIS */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00713 */ HB_P_LINEOFFSET, 51,	/* 281 */
	HB_P_MESSAGE, 68, 0,	/* _ALIGNMENT */
	HB_P_PUSHLOCALNEAR, 7,	/* OLABELAXIS */
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00725 */ HB_P_LINEOFFSET, 52,	/* 282 */
	HB_P_MESSAGE, 71, 0,	/* _FONTSIZE */
	HB_P_PUSHLOCALNEAR, 7,	/* OLABELAXIS */
	HB_P_PUSHBYTE, 8,	/* 8 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00737 */ HB_P_LINEOFFSET, 53,	/* 283 */
	HB_P_MESSAGE, 72, 0,	/* _TEXTCOLOR */
	HB_P_PUSHLOCALNEAR, 7,	/* OLABELAXIS */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00748 */ HB_P_LINEOFFSET, 54,	/* 284 */
	HB_P_MESSAGE, 79, 0,	/* _TEXTALIGNMENT */
	HB_P_PUSHLOCALNEAR, 7,	/* OLABELAXIS */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00759 */ HB_P_LINEOFFSET, 55,	/* 285 */
	HB_P_MESSAGE, 73, 0,	/* _LINECOLOR */
	HB_P_PUSHLOCALNEAR, 7,	/* OLABELAXIS */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00770 */ HB_P_LINEOFFSET, 56,	/* 286 */
	HB_P_MESSAGE, 74, 0,	/* _LINESTYLE */
	HB_P_PUSHLOCALNEAR, 7,	/* OLABELAXIS */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00781 */ HB_P_LINEOFFSET, 58,	/* 288 */
	HB_P_MESSAGE, 80, 0,	/* ADDBARSERIES */
	HB_P_PUSHLOCALNEAR, 3,	/* OREGION */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00791 */ HB_P_LINEOFFSET, 59,	/* 289 */
	HB_P_MESSAGE, 52, 0,	/* BARSERIES */
	HB_P_PUSHLOCALNEAR, 3,	/* OREGION */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_POPLOCALNEAR, 8,	/* OBARSERIES */
/* 00803 */ HB_P_LINEOFFSET, 60,	/* 290 */
	HB_P_MESSAGE, 81, 0,	/* _SERIESTYPE */
	HB_P_PUSHLOCALNEAR, 8,	/* OBARSERIES */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00814 */ HB_P_LINEOFFSET, 61,	/* 291 */
	HB_P_MESSAGE, 82, 0,	/* _SERIESSTYLE */
	HB_P_PUSHLOCALNEAR, 8,	/* OBARSERIES */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00826 */ HB_P_LINEOFFSET, 62,	/* 292 */
	HB_P_MESSAGE, 83, 0,	/* _LUCENT */
	HB_P_PUSHLOCALNEAR, 8,	/* OBARSERIES */
	HB_P_FALSE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00837 */ HB_P_LINEOFFSET, 63,	/* 293 */
	HB_P_MESSAGE, 84, 0,	/* _COLOR */
	HB_P_PUSHLOCALNEAR, 8,	/* OBARSERIES */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'&', 'H', 'F', 'F', 'E', 'E', 'D', 'D', '8', '2', 0, 
	HB_P_MACROTEXT,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00861 */ HB_P_LINEOFFSET, 64,	/* 294 */
	HB_P_MESSAGE, 85, 0,	/* _HORIZONTAL */
	HB_P_PUSHLOCALNEAR, 8,	/* OBARSERIES */
	HB_P_FALSE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00872 */ HB_P_LINEOFFSET, 65,	/* 295 */
	HB_P_MESSAGE, 86, 0,	/* _WHICHDATAAXIS */
	HB_P_PUSHLOCALNEAR, 8,	/* OBARSERIES */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00884 */ HB_P_LINEOFFSET, 66,	/* 296 */
	HB_P_MESSAGE, 87, 0,	/* _VALUELABELON */
	HB_P_PUSHLOCALNEAR, 8,	/* OBARSERIES */
	HB_P_FALSE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00895 */ HB_P_LINEOFFSET, 67,	/* 297 */
	HB_P_MESSAGE, 88, 0,	/* _POINTSPERCOLUMN */
	HB_P_PUSHLOCALNEAR, 8,	/* OBARSERIES */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00906 */ HB_P_LINEOFFSET, 68,	/* 298 */
	HB_P_MESSAGE, 89, 0,	/* _HATCHMODE */
	HB_P_PUSHLOCALNEAR, 8,	/* OBARSERIES */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00917 */ HB_P_LINEOFFSET, 69,	/* 299 */
	HB_P_MESSAGE, 14, 0,	/* _DATASTRING */
	HB_P_PUSHLOCALNEAR, 8,	/* OBARSERIES */
	HB_P_PUSHSTRSHORT, 50,	/* 50 */
	'1', '0', '0', '0', '*', '2', '0', '0', '0', '*', '3', '0', '0', '0', '*', '4', '0', '0', '0', '*', '5', '0', '0', '0', '*', '6', '0', '0', '0', '*', '5', '0', '0', '0', '*', '4', '0', '0', '0', '*', '3', '0', '0', '0', '*', '2', '0', '0', '0', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00979 */ HB_P_LINEOFFSET, 71,	/* 301 */
	HB_P_MESSAGE, 90, 0,	/* ADDLINESERIES */
	HB_P_PUSHLOCALNEAR, 3,	/* OREGION */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00989 */ HB_P_LINEOFFSET, 72,	/* 302 */
	HB_P_MESSAGE, 53, 0,	/* LINESERIES */
	HB_P_PUSHLOCALNEAR, 3,	/* OREGION */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_POPLOCALNEAR, 9,	/* OLINESERIES */
/* 01001 */ HB_P_LINEOFFSET, 73,	/* 303 */
	HB_P_MESSAGE, 81, 0,	/* _SERIESTYPE */
	HB_P_PUSHLOCALNEAR, 9,	/* OLINESERIES */
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01013 */ HB_P_LINEOFFSET, 74,	/* 304 */
	HB_P_MESSAGE, 82, 0,	/* _SERIESSTYLE */
	HB_P_PUSHLOCALNEAR, 9,	/* OLINESERIES */
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01025 */ HB_P_LINEOFFSET, 75,	/* 305 */
	HB_P_MESSAGE, 74, 0,	/* _LINESTYLE */
	HB_P_PUSHLOCALNEAR, 9,	/* OLINESERIES */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01036 */ HB_P_LINEOFFSET, 76,	/* 306 */
	HB_P_MESSAGE, 83, 0,	/* _LUCENT */
	HB_P_PUSHLOCALNEAR, 9,	/* OLINESERIES */
	HB_P_TRUE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01047 */ HB_P_LINEOFFSET, 77,	/* 307 */
	HB_P_MESSAGE, 84, 0,	/* _COLOR */
	HB_P_PUSHLOCALNEAR, 9,	/* OLINESERIES */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'&', 'H', 'F', 'F', 'F', 'F', '0', '0', '0', '0', 0, 
	HB_P_MACROTEXT,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01071 */ HB_P_LINEOFFSET, 78,	/* 308 */
	HB_P_MESSAGE, 91, 0,	/* _SYMBOLSTYLE */
	HB_P_PUSHLOCALNEAR, 9,	/* OLINESERIES */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01083 */ HB_P_LINEOFFSET, 79,	/* 309 */
	HB_P_MESSAGE, 86, 0,	/* _WHICHDATAAXIS */
	HB_P_PUSHLOCALNEAR, 9,	/* OLINESERIES */
	HB_P_ONE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01094 */ HB_P_LINEOFFSET, 80,	/* 310 */
	HB_P_MESSAGE, 87, 0,	/* _VALUELABELON */
	HB_P_PUSHLOCALNEAR, 9,	/* OLINESERIES */
	HB_P_FALSE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01105 */ HB_P_LINEOFFSET, 81,	/* 311 */
	HB_P_MESSAGE, 89, 0,	/* _HATCHMODE */
	HB_P_PUSHLOCALNEAR, 9,	/* OLINESERIES */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01116 */ HB_P_LINEOFFSET, 82,	/* 312 */
	HB_P_MESSAGE, 14, 0,	/* _DATASTRING */
	HB_P_PUSHLOCALNEAR, 9,	/* OLINESERIES */
	HB_P_PUSHSTRSHORT, 50,	/* 50 */
	'1', '0', '0', '0', '*', '2', '0', '0', '0', '*', '3', '0', '0', '0', '*', '4', '0', '0', '0', '*', '5', '0', '0', '0', '*', '6', '0', '0', '0', '*', '5', '0', '0', '0', '*', '4', '0', '0', '0', '*', '3', '0', '0', '0', '*', '2', '0', '0', '0', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01178 */ HB_P_LINEOFFSET, 84,	/* 314 */
	HB_P_MESSAGE, 26, 0,	/* _OCLIENT */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_MESSAGE, 27, 0,	/* OCONTROL */
	HB_P_PUSHLOCALNEAR, 2,	/* OCHART */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 01195 */ HB_P_LINEOFFSET, 86,	/* 316 */
	HB_P_MESSAGE, 28, 0,	/* ACTIVATE */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 29, 0,	/* BLCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 30, 0,	/* BRCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 31, 0,	/* BMOVED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 32, 0,	/* BRESIZED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 33, 0,	/* BPAINTED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 34, 0,	/* BKEYDOWN */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 35, 0,	/* BINIT */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 36, 0,	/* BLBUTTONUP */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 19,
	HB_P_POP,
/* 01272 */ HB_P_LINEOFFSET, 87,	/* 317 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 01277 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

