/*
 * xHarbour Compiler, build 82.0 (SimpLex)
 * Generated C source code from <c:/SGMTO/program/emf.prg>
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "c:/SGMTO/program/emf.prg"

HB_FUNC( DIBUJO7 );
HB_FUNC_STATIC( CREATEEMF );
HB_FUNC_STATIC( DRAWEMF );
HB_FUNC_INIT( LOADGDI32 );
HB_FUNC_EXIT( FREEGDI32 );
HB_FUNC( CREATEENHMETAFILE );
HB_FUNC( CLOSEENHMETAFILE );
HB_FUNC( DELETEENHMETAFILE );
HB_FUNC( GETENHMETAFILE );
HB_FUNC( PLAYENHMETAFILE );
HB_FUNC( MOVETO32 );
HB_FUNC( LINETO32 );
HB_FUNC( GETDC32 );
HB_FUNC( RELEASEDC32 );

static HARBOUR hb_INITSTATICS( void );

extern HB_FUNC( TWINDOW );
extern HB_FUNC( GETDEVICECAPS );
extern HB_FUNC( GETCLIENTRECT );
extern HB_FUNC( THISSTRUCT );
extern HB_FUNC( TSTRUCT );
extern HB_FUNC( CREATEPEN );
extern HB_FUNC( DELETEOBJECT );
extern HB_FUNC( GETHWND32 );
extern HB_FUNC( LOADLIB32 );
extern HB_FUNC( FREELIB32 );
extern HB_FUNC( VALTYPE );
extern HB_FUNC( LOADLIBRARY );
extern HB_FUNC( ABS );
extern HB_FUNC( GETPROCADDRESS );
extern HB_FUNC( EMPTY );
extern HB_FUNC( CALLDLL );
extern HB_FUNC( FREELIBRARY );
extern HB_FUNC( MSGALERT );
extern HB_FUNC( LTRIM );
extern HB_FUNC( STR );
extern HB_FUNC( ERRORSYS );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 5

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_EMF )
{ "DIBUJO7", HB_FS_PUBLIC | HB_FS_FIRST, HB_FUNCNAME( DIBUJO7 ), (PHB_DYNS) 1 },
{ "NEW", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TWINDOW", HB_FS_PUBLIC, HB_FUNCNAME( TWINDOW ), NULL },
{ "ACTIVATE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BLCLICKED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BRCLICKED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BMOVED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BRESIZED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_BPAINTED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "DRAWEMF", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( DRAWEMF ), (PHB_DYNS) 1 },
{ "BKEYDOWN", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BINIT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BLBUTTONUP", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "CREATEEMF", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( CREATEEMF ), (PHB_DYNS) 1 },
{ "GETDEVICECAPS", HB_FS_PUBLIC, HB_FUNCNAME( GETDEVICECAPS ), NULL },
{ "GETCLIENTRECT", HB_FS_PUBLIC, HB_FUNCNAME( GETCLIENTRECT ), NULL },
{ "HWND", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "THISSTRUCT", HB_FS_PUBLIC, HB_FUNCNAME( THISSTRUCT ), NULL },
{ "TSTRUCT", HB_FS_PUBLIC, HB_FUNCNAME( TSTRUCT ), NULL },
{ "ADDMEMBER", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NLEFT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NTOP", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NRIGHT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NBOTTOM", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "CREATEENHMETAFILE", HB_FS_PUBLIC, HB_FUNCNAME( CREATEENHMETAFILE ), (PHB_DYNS) 1 },
{ "CBUFFER", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "CREATEPEN", HB_FS_PUBLIC, HB_FUNCNAME( CREATEPEN ), NULL },
{ "MOVETO32", HB_FS_PUBLIC, HB_FUNCNAME( MOVETO32 ), (PHB_DYNS) 1 },
{ "LINETO32", HB_FS_PUBLIC, HB_FUNCNAME( LINETO32 ), (PHB_DYNS) 1 },
{ "DELETEOBJECT", HB_FS_PUBLIC, HB_FUNCNAME( DELETEOBJECT ), NULL },
{ "CLOSEENHMETAFILE", HB_FS_PUBLIC, HB_FUNCNAME( CLOSEENHMETAFILE ), (PHB_DYNS) 1 },
{ "DELETEENHMETAFILE", HB_FS_PUBLIC, HB_FUNCNAME( DELETEENHMETAFILE ), (PHB_DYNS) 1 },
{ "GETDC32", HB_FS_PUBLIC, HB_FUNCNAME( GETDC32 ), (PHB_DYNS) 1 },
{ "GETHWND32", HB_FS_PUBLIC, HB_FUNCNAME( GETHWND32 ), NULL },
{ "GETENHMETAFILE", HB_FS_PUBLIC, HB_FUNCNAME( GETENHMETAFILE ), (PHB_DYNS) 1 },
{ "PLAYENHMETAFILE", HB_FS_PUBLIC, HB_FUNCNAME( PLAYENHMETAFILE ), (PHB_DYNS) 1 },
{ "RELEASEDC32", HB_FS_PUBLIC, HB_FUNCNAME( RELEASEDC32 ), (PHB_DYNS) 1 },
{ "LOADGDI32", HB_FS_INIT | HB_FS_PUBLIC, HB_FUNCNAME( LOADGDI32 ), (PHB_DYNS) 1 },
{ "LOADLIB32", HB_FS_PUBLIC, HB_FUNCNAME( LOADLIB32 ), NULL },
{ "FREEGDI32", HB_FS_EXIT | HB_FS_PUBLIC, HB_FUNCNAME( FREEGDI32 ), (PHB_DYNS) 1 },
{ "FREELIB32", HB_FS_PUBLIC, HB_FUNCNAME( FREELIB32 ), NULL },
{ "VALTYPE", HB_FS_PUBLIC, HB_FUNCNAME( VALTYPE ), NULL },
{ "LOADLIBRARY", HB_FS_PUBLIC, HB_FUNCNAME( LOADLIBRARY ), NULL },
{ "ABS", HB_FS_PUBLIC, HB_FUNCNAME( ABS ), NULL },
{ "GETPROCADDRESS", HB_FS_PUBLIC, HB_FUNCNAME( GETPROCADDRESS ), NULL },
{ "EMPTY", HB_FS_PUBLIC, HB_FUNCNAME( EMPTY ), NULL },
{ "CALLDLL", HB_FS_PUBLIC, HB_FUNCNAME( CALLDLL ), NULL },
{ "FREELIBRARY", HB_FS_PUBLIC, HB_FUNCNAME( FREELIBRARY ), NULL },
{ "MSGALERT", HB_FS_PUBLIC, HB_FUNCNAME( MSGALERT ), NULL },
{ "LTRIM", HB_FS_PUBLIC, HB_FUNCNAME( LTRIM ), NULL },
{ "STR", HB_FS_PUBLIC, HB_FUNCNAME( STR ), NULL },
{ "ERRORSYS", HB_FS_PUBLIC, HB_FUNCNAME( ERRORSYS ), NULL },
{ "(_INITSTATICS)", HB_FS_INIT | HB_FS_EXIT, hb_INITSTATICS, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_EMF )

#if defined(HB_STATIC_STARTUP)
   #pragma startup hb_vm_SymbolInit_EMF
#elif defined(_MSC_VER)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_EMF = hb_vm_SymbolInit_EMF;
   #pragma data_seg()
#elif ! defined(__GNUC__)
   #pragma startup hb_vm_SymbolInit_EMF
#endif

HB_FUNC( DIBUJO7 )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 2, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 10, 0,	/* 10 */
	HB_P_LOCALNEARSETSTR, 2, 9, 0,	/* CEMF 9*/
	'T', 'E', 'S', 'T', '.', 'E', 'M', 'F', 0, 
/* 00019 */ HB_P_LINEOFFSET, 2,	/* 12 */
	HB_P_MESSAGE, 1, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 2,	/* TWINDOW */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 21,
	HB_P_POPLOCALNEAR, 1,	/* OWND */
/* 00054 */ HB_P_LINEOFFSET, 6,	/* 16 */
	HB_P_MESSAGE, 3, 0,	/* ACTIVATE */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'M', 'A', 'X', 'I', 'M', 'I', 'Z', 'E', 'D', 0, 
	HB_P_MESSAGE, 4, 0,	/* BLCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 5, 0,	/* BRCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 6, 0,	/* BMOVED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 7, 0,	/* BRESIZED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 8, 0,	/* _BPAINTED */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_PUSHBLOCK, 21, 0,	/* 21 */
	2, 0,	/* number of local parameters (2) */
	2, 0,	/* number of local variables (2) */
	1, 0,	/* OWND */
	2, 0,	/* CEMF */
	HB_P_PUSHSYMNEAR, 9,	/* DRAWEMF */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_PUSHLOCALNEAR, 254,	/* localvar2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_ENDBLOCK,
	HB_P_SENDSHORT, 1,
	HB_P_MESSAGE, 10, 0,	/* BKEYDOWN */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 11, 0,	/* BINIT */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 12, 0,	/* BLBUTTONUP */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 19,
	HB_P_POP,
/* 00163 */ HB_P_LINEOFFSET, 8,	/* 18 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00168 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( CREATEEMF )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 11, 3,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 29, 0,	/* 29 */
	HB_P_PUSHSYMNEAR, 14,	/* GETDEVICECAPS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDCREF */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 4,	/* NHORZSIZE */
/* 00017 */ HB_P_LINEOFFSET, 1,	/* 30 */
	HB_P_PUSHSYMNEAR, 14,	/* GETDEVICECAPS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDCREF */
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 5,	/* NVERTSIZE */
/* 00030 */ HB_P_LINEOFFSET, 3,	/* 32 */
	HB_P_PUSHSYMNEAR, 14,	/* GETDEVICECAPS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDCREF */
	HB_P_PUSHBYTE, 8,	/* 8 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 6,	/* NHORZRES */
/* 00043 */ HB_P_LINEOFFSET, 4,	/* 33 */
	HB_P_PUSHSYMNEAR, 14,	/* GETDEVICECAPS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDCREF */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 7,	/* NVERTRES */
/* 00056 */ HB_P_LINEOFFSET, 6,	/* 35 */
	HB_P_PUSHLOCALNEAR, 4,	/* NHORZSIZE */
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_MULT,
	HB_P_PUSHLOCALNEAR, 6,	/* NHORZRES */
	HB_P_DIVIDE,
	HB_P_POPLOCALNEAR, 8,	/* NMMPIXELX */
/* 00068 */ HB_P_LINEOFFSET, 7,	/* 36 */
	HB_P_PUSHLOCALNEAR, 5,	/* NVERTSIZE */
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_MULT,
	HB_P_PUSHLOCALNEAR, 7,	/* NVERTRES */
	HB_P_DIVIDE,
	HB_P_POPLOCALNEAR, 9,	/* NMMPIXELY */
/* 00080 */ HB_P_LINEOFFSET, 9,	/* 38 */
	HB_P_PUSHSYMNEAR, 15,	/* GETCLIENTRECT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 16, 0,	/* HWND */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 10,	/* ARECT */
/* 00096 */ HB_P_LINEOFFSET, 15,	/* 44 */
	HB_P_PUSHLOCALNEAR, 10,	/* ARECT */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_PUSHLOCALNEAR, 9,	/* NMMPIXELY */
	HB_P_MULT,
	HB_P_PUSHLOCALREF, 10, 0,	/* ARECT */
	HB_P_ONE,
	HB_P_ARRAYPOP,
/* 00110 */ HB_P_LINEOFFSET, 16,	/* 45 */
	HB_P_PUSHLOCALNEAR, 10,	/* ARECT */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHLOCALNEAR, 8,	/* NMMPIXELX */
	HB_P_MULT,
	HB_P_PUSHLOCALREF, 10, 0,	/* ARECT */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPOP,
/* 00126 */ HB_P_LINEOFFSET, 17,	/* 46 */
	HB_P_PUSHLOCALNEAR, 10,	/* ARECT */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHLOCALNEAR, 9,	/* NMMPIXELY */
	HB_P_MULT,
	HB_P_PUSHLOCALREF, 10, 0,	/* ARECT */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPOP,
/* 00142 */ HB_P_LINEOFFSET, 18,	/* 47 */
	HB_P_PUSHLOCALNEAR, 10,	/* ARECT */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHLOCALNEAR, 8,	/* NMMPIXELX */
	HB_P_MULT,
	HB_P_PUSHLOCALREF, 10, 0,	/* ARECT */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ARRAYPOP,
/* 00158 */ HB_P_LINEOFFSET, 20,	/* 49 */
	HB_P_PUSHSYMNEAR, 17,	/* THISSTRUCT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 1, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 18,	/* TSTRUCT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 14,	/* ORECT */
/* 00177 */ HB_P_LINEOFFSET, 21,	/* 50 */
	HB_P_MESSAGE, 19, 0,	/* ADDMEMBER */
	HB_P_PUSHSYMNEAR, 17,	/* THISSTRUCT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'n', 'L', 'e', 'f', 't', 0, 
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
	HB_P_MESSAGE, 19, 0,	/* ADDMEMBER */
	HB_P_PUSHSYMNEAR, 17,	/* THISSTRUCT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'n', 'T', 'o', 'p', 0, 
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
	HB_P_MESSAGE, 19, 0,	/* ADDMEMBER */
	HB_P_PUSHSYMNEAR, 17,	/* THISSTRUCT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'n', 'R', 'i', 'g', 'h', 't', 0, 
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
	HB_P_MESSAGE, 19, 0,	/* ADDMEMBER */
	HB_P_PUSHSYMNEAR, 17,	/* THISSTRUCT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'n', 'B', 'o', 't', 't', 'o', 'm', 0, 
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
	HB_P_PUSHSYMNEAR, 17,	/* THISSTRUCT */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 1,
/* 00275 */ HB_P_LINEOFFSET, 27,	/* 56 */
	HB_P_MESSAGE, 20, 0,	/* _NLEFT */
	HB_P_PUSHLOCALNEAR, 14,	/* ORECT */
	HB_P_PUSHLOCALNEAR, 10,	/* ARECT */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00290 */ HB_P_LINEOFFSET, 28,	/* 57 */
	HB_P_MESSAGE, 21, 0,	/* _NTOP */
	HB_P_PUSHLOCALNEAR, 14,	/* ORECT */
	HB_P_PUSHLOCALNEAR, 10,	/* ARECT */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00304 */ HB_P_LINEOFFSET, 29,	/* 58 */
	HB_P_MESSAGE, 22, 0,	/* _NRIGHT */
	HB_P_PUSHLOCALNEAR, 14,	/* ORECT */
	HB_P_PUSHLOCALNEAR, 10,	/* ARECT */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00319 */ HB_P_LINEOFFSET, 30,	/* 59 */
	HB_P_MESSAGE, 23, 0,	/* _NBOTTOM */
	HB_P_PUSHLOCALNEAR, 14,	/* ORECT */
	HB_P_PUSHLOCALNEAR, 10,	/* ARECT */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00334 */ HB_P_LINEOFFSET, 32,	/* 61 */
	HB_P_PUSHSYMNEAR, 24,	/* CREATEENHMETAFILE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDCREF */
	HB_P_PUSHLOCALNEAR, 3,	/* CEMF */
	HB_P_MESSAGE, 25, 0,	/* CBUFFER */
	HB_P_PUSHLOCALNEAR, 14,	/* ORECT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSTRSHORT, 24,	/* 24 */
	'T', 'e', 's', 't', 0, 'C', 'r', 'e', 'a', 't', 'i', 'n', 'g', ' ', 'E', 'M', 'F', 's', '.', '.', '.', 0, 0, 0, 
	HB_P_FUNCTIONSHORT, 4,
	HB_P_POPLOCALNEAR, 11,	/* HDC */
/* 00380 */ HB_P_LINEOFFSET, 34,	/* 63 */
	HB_P_PUSHSYMNEAR, 26,	/* CREATEPEN */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ONE,
	HB_P_PUSHINT, 128, 0,	/* 128 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPLOCALNEAR, 13,	/* HPEN */
/* 00394 */ HB_P_LINEOFFSET, 36,	/* 65 */
	HB_P_PUSHSYMNEAR, 27,	/* MOVETO32 */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 11,	/* HDC */
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_DOSHORT, 4,
/* 00406 */ HB_P_LINEOFFSET, 38,	/* 67 */
	HB_P_PUSHSYMNEAR, 15,	/* GETCLIENTRECT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 16, 0,	/* HWND */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 10,	/* ARECT */
/* 00422 */ HB_P_LINEOFFSET, 40,	/* 69 */
	HB_P_PUSHSYMNEAR, 28,	/* LINETO32 */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 11,	/* HDC */
	HB_P_PUSHLOCALNEAR, 10,	/* ARECT */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHLOCALNEAR, 10,	/* ARECT */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPUSH,
	HB_P_DOSHORT, 3,
/* 00441 */ HB_P_LINEOFFSET, 42,	/* 71 */
	HB_P_PUSHSYMNEAR, 29,	/* DELETEOBJECT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 13,	/* HPEN */
	HB_P_DOSHORT, 1,
/* 00450 */ HB_P_LINEOFFSET, 44,	/* 73 */
	HB_P_PUSHSYMNEAR, 30,	/* CLOSEENHMETAFILE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 11,	/* HDC */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 12,	/* HEMF */
/* 00461 */ HB_P_LINEOFFSET, 46,	/* 75 */
	HB_P_PUSHSYMNEAR, 31,	/* DELETEENHMETAFILE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 12,	/* HEMF */
	HB_P_DOSHORT, 1,
/* 00470 */ HB_P_LINEOFFSET, 48,	/* 77 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00475 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( DRAWEMF )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 4, 2,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 82, 0,	/* 82 */
	HB_P_PUSHSYMNEAR, 32,	/* GETDC32 */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 33,	/* GETHWND32 */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 16, 0,	/* HWND */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 3,	/* HDC */
/* 00025 */ HB_P_LINEOFFSET, 6,	/* 88 */
	HB_P_PUSHSYMNEAR, 13,	/* CREATEEMF */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_PUSHLOCALNEAR, 3,	/* HDC */
	HB_P_PUSHLOCALNEAR, 2,	/* CEMF */
	HB_P_DOSHORT, 3,
/* 00038 */ HB_P_LINEOFFSET, 8,	/* 90 */
	HB_P_PUSHSYMNEAR, 34,	/* GETENHMETAFILE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* CEMF */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 6,	/* HEMF */
/* 00049 */ HB_P_LINEOFFSET, 10,	/* 92 */
	HB_P_PUSHSYMNEAR, 17,	/* THISSTRUCT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 1, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 18,	/* TSTRUCT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 4,	/* ORECT */
/* 00068 */ HB_P_LINEOFFSET, 11,	/* 93 */
	HB_P_MESSAGE, 19, 0,	/* ADDMEMBER */
	HB_P_PUSHSYMNEAR, 17,	/* THISSTRUCT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'n', 'L', 'e', 'f', 't', 0, 
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
	HB_P_MESSAGE, 19, 0,	/* ADDMEMBER */
	HB_P_PUSHSYMNEAR, 17,	/* THISSTRUCT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'n', 'T', 'o', 'p', 0, 
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
	HB_P_MESSAGE, 19, 0,	/* ADDMEMBER */
	HB_P_PUSHSYMNEAR, 17,	/* THISSTRUCT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'n', 'R', 'i', 'g', 'h', 't', 0, 
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
	HB_P_MESSAGE, 19, 0,	/* ADDMEMBER */
	HB_P_PUSHSYMNEAR, 17,	/* THISSTRUCT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'n', 'B', 'o', 't', 't', 'o', 'm', 0, 
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 3,
	HB_P_POP,
	HB_P_PUSHSYMNEAR, 17,	/* THISSTRUCT */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 1,
/* 00166 */ HB_P_LINEOFFSET, 17,	/* 99 */
	HB_P_PUSHSYMNEAR, 15,	/* GETCLIENTRECT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 16, 0,	/* HWND */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 5,	/* ARECT */
/* 00182 */ HB_P_LINEOFFSET, 19,	/* 101 */
	HB_P_MESSAGE, 20, 0,	/* _NLEFT */
	HB_P_PUSHLOCALNEAR, 4,	/* ORECT */
	HB_P_PUSHLOCALNEAR, 5,	/* ARECT */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00197 */ HB_P_LINEOFFSET, 20,	/* 102 */
	HB_P_MESSAGE, 21, 0,	/* _NTOP */
	HB_P_PUSHLOCALNEAR, 4,	/* ORECT */
	HB_P_PUSHLOCALNEAR, 5,	/* ARECT */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00211 */ HB_P_LINEOFFSET, 21,	/* 103 */
	HB_P_MESSAGE, 22, 0,	/* _NRIGHT */
	HB_P_PUSHLOCALNEAR, 4,	/* ORECT */
	HB_P_PUSHLOCALNEAR, 5,	/* ARECT */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00226 */ HB_P_LINEOFFSET, 22,	/* 104 */
	HB_P_MESSAGE, 23, 0,	/* _NBOTTOM */
	HB_P_PUSHLOCALNEAR, 4,	/* ORECT */
	HB_P_PUSHLOCALNEAR, 5,	/* ARECT */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPUSH,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00241 */ HB_P_LINEOFFSET, 24,	/* 106 */
	HB_P_PUSHSYMNEAR, 35,	/* PLAYENHMETAFILE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* HDC */
	HB_P_PUSHLOCALNEAR, 6,	/* HEMF */
	HB_P_MESSAGE, 25, 0,	/* CBUFFER */
	HB_P_PUSHLOCALNEAR, 4,	/* ORECT */
	HB_P_SENDSHORT, 0,
	HB_P_DOSHORT, 3,
/* 00259 */ HB_P_LINEOFFSET, 26,	/* 108 */
	HB_P_PUSHSYMNEAR, 31,	/* DELETEENHMETAFILE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 6,	/* HEMF */
	HB_P_DOSHORT, 1,
/* 00268 */ HB_P_LINEOFFSET, 28,	/* 110 */
	HB_P_PUSHSYMNEAR, 36,	/* RELEASEDC32 */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* HDC */
	HB_P_DOSHORT, 1,
/* 00277 */ HB_P_LINEOFFSET, 30,	/* 112 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00282 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_INIT( LOADGDI32 )
{
   static const BYTE pcode[] =
   {
	HB_P_SFRAME, 52, 0,	/* symbol (_INITSTATICS) */
/* 00003 */ HB_P_BASELINE, 116, 0,	/* 116 */
	HB_P_PUSHSYMNEAR, 38,	/* LOADLIB32 */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'g', 'd', 'i', '3', '2', '.', 'd', 'l', 'l', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPSTATIC, 1, 0,	/* HGDI32 */
/* 00026 */ HB_P_LINEOFFSET, 2,	/* 118 */
	HB_P_ENDPROC
/* 00029 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_EXIT( FREEGDI32 )
{
   static const BYTE pcode[] =
   {
	HB_P_SFRAME, 52, 0,	/* symbol (_INITSTATICS) */
/* 00003 */ HB_P_BASELINE, 122, 0,	/* 122 */
	HB_P_PUSHSYMNEAR, 40,	/* FREELIB32 */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_DOSHORT, 1,
/* 00014 */ HB_P_LINEOFFSET, 2,	/* 124 */
	HB_P_ENDPROC
/* 00017 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( CREATEENHMETAFILE )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 3, 4,	/* locals, params */
	HB_P_SFRAME, 52, 0,	/* symbol (_INITSTATICS) */
	HB_P_PUSHSYMNEAR, 41,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00026) */
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_JUMPNEAR, 16,	/* 16 (abs: 00040) */
	HB_P_PUSHSYMNEAR, 42,	/* LOADLIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'h', 'G', 'D', 'I', '3', '2', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 5,	/* HDLL */
	HB_P_PUSHSYMNEAR, 43,	/* ABS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_GREATER,
	HB_P_JUMPFALSE, 141, 0,	/* 141 (abs: 00193) */
	HB_P_PUSHSYMNEAR, 44,	/* GETPROCADDRESS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* HDLL */
	HB_P_PUSHSYMNEAR, 45,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	'C', 'r', 'e', 'a', 't', 'e', 'E', 'n', 'h', 'M', 'e', 't', 'a', 'F', 'i', 'l', 'e', 'A', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_TRUE,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 24,	/* 24 (abs: 00112) */
	HB_P_PUSHSTRSHORT, 18,	/* 18 */
	'C', 'R', 'E', 'A', 'T', 'E', 'E', 'N', 'H', 'M', 'E', 'T', 'A', 'F', 'I', 'L', 'E', 0, 
	HB_P_JUMPNEAR, 23,	/* 23 (abs: 00133) */
	HB_P_PUSHSTRSHORT, 19,	/* 19 */
	'C', 'r', 'e', 'a', 't', 'e', 'E', 'n', 'h', 'M', 'e', 't', 'a', 'F', 'i', 'l', 'e', 'A', 0, 
	HB_P_TRUE,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_FUNCTIONSHORT, 8,
	HB_P_POPLOCALNEAR, 7,	/* CFARPROC */
	HB_P_PUSHSYMNEAR, 46,	/* CALLDLL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 7,	/* CFARPROC */
	HB_P_PUSHLOCALNEAR, 1,	/* HDCREF */
	HB_P_PUSHLOCALNEAR, 2,	/* CFILENAME */
	HB_P_PUSHLOCALNEAR, 3,	/* CRECT */
	HB_P_PUSHLOCALNEAR, 4,	/* CDESCRIPTION */
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 6,	/* URESULT */
	HB_P_PUSHSYMNEAR, 41,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00183) */
	HB_P_PUSHNIL,
	HB_P_JUMPNEAR, 9,	/* 9 (abs: 00190) */
	HB_P_PUSHSYMNEAR, 47,	/* FREELIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 52,	/* 52 (abs: 00243) */
	HB_P_PUSHSYMNEAR, 48,	/* MSGALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'E', 'r', 'r', 'o', 'r', ' ', 'c', 'o', 'd', 'e', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 49,	/* LTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	' ', 'l', 'o', 'a', 'd', 'i', 'n', 'g', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHLOCALNEAR, 6,	/* URESULT */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00247 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( CLOSEENHMETAFILE )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 3, 1,	/* locals, params */
	HB_P_SFRAME, 52, 0,	/* symbol (_INITSTATICS) */
	HB_P_PUSHSYMNEAR, 41,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00026) */
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_JUMPNEAR, 16,	/* 16 (abs: 00040) */
	HB_P_PUSHSYMNEAR, 42,	/* LOADLIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'h', 'G', 'D', 'I', '3', '2', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 2,	/* HDLL */
	HB_P_PUSHSYMNEAR, 43,	/* ABS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_GREATER,
	HB_P_JUMPFALSE, 124, 0,	/* 124 (abs: 00176) */
	HB_P_PUSHSYMNEAR, 44,	/* GETPROCADDRESS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_PUSHSYMNEAR, 45,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 17,	/* 17 */
	'C', 'l', 'o', 's', 'e', 'E', 'n', 'h', 'M', 'e', 't', 'a', 'F', 'i', 'l', 'e', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_TRUE,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 23,	/* 23 (abs: 00109) */
	HB_P_PUSHSTRSHORT, 17,	/* 17 */
	'C', 'L', 'O', 'S', 'E', 'E', 'N', 'H', 'M', 'E', 'T', 'A', 'F', 'I', 'L', 'E', 0, 
	HB_P_JUMPNEAR, 21,	/* 21 (abs: 00128) */
	HB_P_PUSHSTRSHORT, 17,	/* 17 */
	'C', 'l', 'o', 's', 'e', 'E', 'n', 'h', 'M', 'e', 't', 'a', 'F', 'i', 'l', 'e', 0, 
	HB_P_TRUE,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 4,	/* CFARPROC */
	HB_P_PUSHSYMNEAR, 46,	/* CALLDLL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* CFARPROC */
	HB_P_PUSHLOCALNEAR, 1,	/* HDC */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 3,	/* URESULT */
	HB_P_PUSHSYMNEAR, 41,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00166) */
	HB_P_PUSHNIL,
	HB_P_JUMPNEAR, 9,	/* 9 (abs: 00173) */
	HB_P_PUSHSYMNEAR, 47,	/* FREELIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 52,	/* 52 (abs: 00226) */
	HB_P_PUSHSYMNEAR, 48,	/* MSGALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'E', 'r', 'r', 'o', 'r', ' ', 'c', 'o', 'd', 'e', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 49,	/* LTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	' ', 'l', 'o', 'a', 'd', 'i', 'n', 'g', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHLOCALNEAR, 3,	/* URESULT */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00230 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( DELETEENHMETAFILE )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 3, 1,	/* locals, params */
	HB_P_SFRAME, 52, 0,	/* symbol (_INITSTATICS) */
	HB_P_PUSHSYMNEAR, 41,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00026) */
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_JUMPNEAR, 16,	/* 16 (abs: 00040) */
	HB_P_PUSHSYMNEAR, 42,	/* LOADLIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'h', 'G', 'D', 'I', '3', '2', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 2,	/* HDLL */
	HB_P_PUSHSYMNEAR, 43,	/* ABS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_GREATER,
	HB_P_JUMPFALSE, 127, 0,	/* 127 (abs: 00179) */
	HB_P_PUSHSYMNEAR, 44,	/* GETPROCADDRESS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_PUSHSYMNEAR, 45,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 18,	/* 18 */
	'D', 'e', 'l', 'e', 't', 'e', 'E', 'n', 'h', 'M', 'e', 't', 'a', 'F', 'i', 'l', 'e', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_TRUE,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 24,	/* 24 (abs: 00111) */
	HB_P_PUSHSTRSHORT, 18,	/* 18 */
	'D', 'E', 'L', 'E', 'T', 'E', 'E', 'N', 'H', 'M', 'E', 'T', 'A', 'F', 'I', 'L', 'E', 0, 
	HB_P_JUMPNEAR, 22,	/* 22 (abs: 00131) */
	HB_P_PUSHSTRSHORT, 18,	/* 18 */
	'D', 'e', 'l', 'e', 't', 'e', 'E', 'n', 'h', 'M', 'e', 't', 'a', 'F', 'i', 'l', 'e', 0, 
	HB_P_TRUE,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 4,	/* CFARPROC */
	HB_P_PUSHSYMNEAR, 46,	/* CALLDLL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* CFARPROC */
	HB_P_PUSHLOCALNEAR, 1,	/* HEMF */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 3,	/* URESULT */
	HB_P_PUSHSYMNEAR, 41,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00169) */
	HB_P_PUSHNIL,
	HB_P_JUMPNEAR, 9,	/* 9 (abs: 00176) */
	HB_P_PUSHSYMNEAR, 47,	/* FREELIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 52,	/* 52 (abs: 00229) */
	HB_P_PUSHSYMNEAR, 48,	/* MSGALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'E', 'r', 'r', 'o', 'r', ' ', 'c', 'o', 'd', 'e', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 49,	/* LTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	' ', 'l', 'o', 'a', 'd', 'i', 'n', 'g', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHLOCALNEAR, 3,	/* URESULT */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00233 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( GETENHMETAFILE )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 3, 1,	/* locals, params */
	HB_P_SFRAME, 52, 0,	/* symbol (_INITSTATICS) */
	HB_P_PUSHSYMNEAR, 41,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00026) */
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_JUMPNEAR, 16,	/* 16 (abs: 00040) */
	HB_P_PUSHSYMNEAR, 42,	/* LOADLIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'h', 'G', 'D', 'I', '3', '2', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 2,	/* HDLL */
	HB_P_PUSHSYMNEAR, 43,	/* ABS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_GREATER,
	HB_P_JUMPFALSE, 120, 0,	/* 120 (abs: 00172) */
	HB_P_PUSHSYMNEAR, 44,	/* GETPROCADDRESS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_PUSHSYMNEAR, 45,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	'G', 'e', 't', 'E', 'n', 'h', 'M', 'e', 't', 'a', 'F', 'i', 'l', 'e', 'A', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_TRUE,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 21,	/* 21 (abs: 00106) */
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'G', 'E', 'T', 'E', 'N', 'H', 'M', 'E', 'T', 'A', 'F', 'I', 'L', 'E', 0, 
	HB_P_JUMPNEAR, 20,	/* 20 (abs: 00124) */
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	'G', 'e', 't', 'E', 'n', 'h', 'M', 'e', 't', 'a', 'F', 'i', 'l', 'e', 'A', 0, 
	HB_P_TRUE,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 4,	/* CFARPROC */
	HB_P_PUSHSYMNEAR, 46,	/* CALLDLL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* CFARPROC */
	HB_P_PUSHLOCALNEAR, 1,	/* CMETAFILE */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 3,	/* URESULT */
	HB_P_PUSHSYMNEAR, 41,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00162) */
	HB_P_PUSHNIL,
	HB_P_JUMPNEAR, 9,	/* 9 (abs: 00169) */
	HB_P_PUSHSYMNEAR, 47,	/* FREELIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 52,	/* 52 (abs: 00222) */
	HB_P_PUSHSYMNEAR, 48,	/* MSGALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'E', 'r', 'r', 'o', 'r', ' ', 'c', 'o', 'd', 'e', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 49,	/* LTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	' ', 'l', 'o', 'a', 'd', 'i', 'n', 'g', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHLOCALNEAR, 3,	/* URESULT */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00226 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( PLAYENHMETAFILE )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 3, 3,	/* locals, params */
	HB_P_SFRAME, 52, 0,	/* symbol (_INITSTATICS) */
	HB_P_PUSHSYMNEAR, 41,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00026) */
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_JUMPNEAR, 16,	/* 16 (abs: 00040) */
	HB_P_PUSHSYMNEAR, 42,	/* LOADLIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'h', 'G', 'D', 'I', '3', '2', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 4,	/* HDLL */
	HB_P_PUSHSYMNEAR, 43,	/* ABS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_GREATER,
	HB_P_JUMPFALSE, 129, 0,	/* 129 (abs: 00181) */
	HB_P_PUSHSYMNEAR, 44,	/* GETPROCADDRESS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* HDLL */
	HB_P_PUSHSYMNEAR, 45,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	'P', 'l', 'a', 'y', 'E', 'n', 'h', 'M', 'e', 't', 'a', 'F', 'i', 'l', 'e', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_TRUE,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 22,	/* 22 (abs: 00107) */
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	'P', 'L', 'A', 'Y', 'E', 'N', 'H', 'M', 'E', 'T', 'A', 'F', 'I', 'L', 'E', 0, 
	HB_P_JUMPNEAR, 20,	/* 20 (abs: 00125) */
	HB_P_PUSHSTRSHORT, 16,	/* 16 */
	'P', 'l', 'a', 'y', 'E', 'n', 'h', 'M', 'e', 't', 'a', 'F', 'i', 'l', 'e', 0, 
	HB_P_TRUE,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_FUNCTIONSHORT, 7,
	HB_P_POPLOCALNEAR, 6,	/* CFARPROC */
	HB_P_PUSHSYMNEAR, 46,	/* CALLDLL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 6,	/* CFARPROC */
	HB_P_PUSHLOCALNEAR, 1,	/* HDC */
	HB_P_PUSHLOCALNEAR, 2,	/* HEMF */
	HB_P_PUSHLOCALNEAR, 3,	/* CRECT */
	HB_P_FUNCTIONSHORT, 4,
	HB_P_POPLOCALNEAR, 5,	/* URESULT */
	HB_P_PUSHSYMNEAR, 41,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00171) */
	HB_P_PUSHNIL,
	HB_P_JUMPNEAR, 9,	/* 9 (abs: 00178) */
	HB_P_PUSHSYMNEAR, 47,	/* FREELIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 52,	/* 52 (abs: 00231) */
	HB_P_PUSHSYMNEAR, 48,	/* MSGALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'E', 'r', 'r', 'o', 'r', ' ', 'c', 'o', 'd', 'e', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 49,	/* LTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	' ', 'l', 'o', 'a', 'd', 'i', 'n', 'g', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHLOCALNEAR, 5,	/* URESULT */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00235 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( MOVETO32 )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 3, 4,	/* locals, params */
	HB_P_SFRAME, 52, 0,	/* symbol (_INITSTATICS) */
	HB_P_PUSHSYMNEAR, 41,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00026) */
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_JUMPNEAR, 16,	/* 16 (abs: 00040) */
	HB_P_PUSHSYMNEAR, 42,	/* LOADLIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'h', 'G', 'D', 'I', '3', '2', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 5,	/* HDLL */
	HB_P_PUSHSYMNEAR, 43,	/* ABS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_GREATER,
	HB_P_JUMPFALSE, 112, 0,	/* 112 (abs: 00164) */
	HB_P_PUSHSYMNEAR, 44,	/* GETPROCADDRESS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* HDLL */
	HB_P_PUSHSYMNEAR, 45,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'M', 'o', 'v', 'e', 'T', 'o', 'E', 'x', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_TRUE,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 15,	/* 15 (abs: 00093) */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'M', 'O', 'V', 'E', 'T', 'O', '3', '2', 0, 
	HB_P_JUMPNEAR, 13,	/* 13 (abs: 00104) */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'M', 'o', 'v', 'e', 'T', 'o', 'E', 'x', 0, 
	HB_P_TRUE,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_FUNCTIONSHORT, 8,
	HB_P_POPLOCALNEAR, 7,	/* CFARPROC */
	HB_P_PUSHSYMNEAR, 46,	/* CALLDLL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 7,	/* CFARPROC */
	HB_P_PUSHLOCALNEAR, 1,	/* HDC */
	HB_P_PUSHLOCALNEAR, 2,	/* NX */
	HB_P_PUSHLOCALNEAR, 3,	/* NY */
	HB_P_PUSHLOCALNEAR, 4,	/* CPOINT */
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 6,	/* URESULT */
	HB_P_PUSHSYMNEAR, 41,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00154) */
	HB_P_PUSHNIL,
	HB_P_JUMPNEAR, 9,	/* 9 (abs: 00161) */
	HB_P_PUSHSYMNEAR, 47,	/* FREELIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 52,	/* 52 (abs: 00214) */
	HB_P_PUSHSYMNEAR, 48,	/* MSGALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'E', 'r', 'r', 'o', 'r', ' ', 'c', 'o', 'd', 'e', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 49,	/* LTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	' ', 'l', 'o', 'a', 'd', 'i', 'n', 'g', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHLOCALNEAR, 6,	/* URESULT */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00218 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( LINETO32 )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 3, 3,	/* locals, params */
	HB_P_SFRAME, 52, 0,	/* symbol (_INITSTATICS) */
	HB_P_PUSHSYMNEAR, 41,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00026) */
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_JUMPNEAR, 16,	/* 16 (abs: 00040) */
	HB_P_PUSHSYMNEAR, 42,	/* LOADLIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'h', 'G', 'D', 'I', '3', '2', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 4,	/* HDLL */
	HB_P_PUSHSYMNEAR, 43,	/* ABS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 103,	/* 103 (abs: 00155) */
	HB_P_PUSHSYMNEAR, 44,	/* GETPROCADDRESS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* HDLL */
	HB_P_PUSHSYMNEAR, 45,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'L', 'i', 'n', 'e', 'T', 'o', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_TRUE,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 15,	/* 15 (abs: 00090) */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'L', 'I', 'N', 'E', 'T', 'O', '3', '2', 0, 
	HB_P_JUMPNEAR, 11,	/* 11 (abs: 00099) */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'L', 'i', 'n', 'e', 'T', 'o', 0, 
	HB_P_TRUE,
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_FUNCTIONSHORT, 7,
	HB_P_POPLOCALNEAR, 6,	/* CFARPROC */
	HB_P_PUSHSYMNEAR, 46,	/* CALLDLL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 6,	/* CFARPROC */
	HB_P_PUSHLOCALNEAR, 1,	/* HDC */
	HB_P_PUSHLOCALNEAR, 2,	/* NXEND */
	HB_P_PUSHLOCALNEAR, 3,	/* NYEND */
	HB_P_FUNCTIONSHORT, 4,
	HB_P_POPLOCALNEAR, 5,	/* URESULT */
	HB_P_PUSHSYMNEAR, 41,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00145) */
	HB_P_PUSHNIL,
	HB_P_JUMPNEAR, 9,	/* 9 (abs: 00152) */
	HB_P_PUSHSYMNEAR, 47,	/* FREELIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 52,	/* 52 (abs: 00205) */
	HB_P_PUSHSYMNEAR, 48,	/* MSGALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'E', 'r', 'r', 'o', 'r', ' ', 'c', 'o', 'd', 'e', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 49,	/* LTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	' ', 'l', 'o', 'a', 'd', 'i', 'n', 'g', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSTATIC, 1, 0,	/* HGDI32 */
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHLOCALNEAR, 5,	/* URESULT */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00209 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( GETDC32 )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 3, 1,	/* locals, params */
	HB_P_PUSHSYMNEAR, 41,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'u', 's', 'e', 'r', '3', '2', '.', 'd', 'l', 'l', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 17,	/* 17 (abs: 00043) */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'u', 's', 'e', 'r', '3', '2', '.', 'd', 'l', 'l', 0, 
	HB_P_JUMPNEAR, 20,	/* 20 (abs: 00061) */
	HB_P_PUSHSYMNEAR, 42,	/* LOADLIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'u', 's', 'e', 'r', '3', '2', '.', 'd', 'l', 'l', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 2,	/* HDLL */
	HB_P_PUSHSYMNEAR, 43,	/* ABS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 102,	/* 102 (abs: 00175) */
	HB_P_PUSHSYMNEAR, 44,	/* GETPROCADDRESS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_PUSHSYMNEAR, 45,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'G', 'e', 't', 'D', 'C', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_TRUE,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 14,	/* 14 (abs: 00109) */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'G', 'E', 'T', 'D', 'C', '3', '2', 0, 
	HB_P_JUMPNEAR, 10,	/* 10 (abs: 00117) */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'G', 'e', 't', 'D', 'C', 0, 
	HB_P_TRUE,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 4,	/* CFARPROC */
	HB_P_PUSHSYMNEAR, 46,	/* CALLDLL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* CFARPROC */
	HB_P_PUSHLOCALNEAR, 1,	/* HWND */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 3,	/* URESULT */
	HB_P_PUSHSYMNEAR, 41,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'u', 's', 'e', 'r', '3', '2', '.', 'd', 'l', 'l', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00165) */
	HB_P_PUSHNIL,
	HB_P_JUMPNEAR, 9,	/* 9 (abs: 00172) */
	HB_P_PUSHSYMNEAR, 47,	/* FREELIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 62,	/* 62 (abs: 00235) */
	HB_P_PUSHSYMNEAR, 48,	/* MSGALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'E', 'r', 'r', 'o', 'r', ' ', 'c', 'o', 'd', 'e', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 49,	/* LTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	' ', 'l', 'o', 'a', 'd', 'i', 'n', 'g', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'u', 's', 'e', 'r', '3', '2', '.', 'd', 'l', 'l', 0, 
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHLOCALNEAR, 3,	/* URESULT */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00239 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( RELEASEDC32 )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 3, 2,	/* locals, params */
	HB_P_PUSHSYMNEAR, 41,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'u', 's', 'e', 'r', '3', '2', '.', 'd', 'l', 'l', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 17,	/* 17 (abs: 00043) */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'u', 's', 'e', 'r', '3', '2', '.', 'd', 'l', 'l', 0, 
	HB_P_JUMPNEAR, 20,	/* 20 (abs: 00061) */
	HB_P_PUSHSYMNEAR, 42,	/* LOADLIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'u', 's', 'e', 'r', '3', '2', '.', 'd', 'l', 'l', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 3,	/* HDLL */
	HB_P_PUSHSYMNEAR, 43,	/* ABS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_GREATER,
	HB_P_JUMPFALSE, 119, 0,	/* 119 (abs: 00192) */
	HB_P_PUSHSYMNEAR, 44,	/* GETPROCADDRESS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* HDLL */
	HB_P_PUSHSYMNEAR, 45,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'R', 'e', 'l', 'e', 'a', 's', 'e', 'D', 'C', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_TRUE,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00118) */
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'R', 'E', 'L', 'E', 'A', 'S', 'E', 'D', 'C', '3', '2', 0, 
	HB_P_JUMPNEAR, 14,	/* 14 (abs: 00130) */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'R', 'e', 'l', 'e', 'a', 's', 'e', 'D', 'C', 0, 
	HB_P_TRUE,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_FUNCTIONSHORT, 6,
	HB_P_POPLOCALNEAR, 5,	/* CFARPROC */
	HB_P_PUSHSYMNEAR, 46,	/* CALLDLL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* CFARPROC */
	HB_P_PUSHLOCALNEAR, 1,	/* HWND */
	HB_P_PUSHLOCALNEAR, 2,	/* HDC */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPLOCALNEAR, 4,	/* URESULT */
	HB_P_PUSHSYMNEAR, 41,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'u', 's', 'e', 'r', '3', '2', '.', 'd', 'l', 'l', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00182) */
	HB_P_PUSHNIL,
	HB_P_JUMPNEAR, 9,	/* 9 (abs: 00189) */
	HB_P_PUSHSYMNEAR, 47,	/* FREELIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 62,	/* 62 (abs: 00252) */
	HB_P_PUSHSYMNEAR, 48,	/* MSGALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'E', 'r', 'r', 'o', 'r', ' ', 'c', 'o', 'd', 'e', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 49,	/* LTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 50,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	' ', 'l', 'o', 'a', 'd', 'i', 'n', 'g', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'u', 's', 'e', 'r', '3', '2', '.', 'd', 'l', 'l', 0, 
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHLOCALNEAR, 4,	/* URESULT */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00256 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

static HARBOUR hb_INITSTATICS( void )
{
   static const BYTE pcode[] =
   {
	HB_P_STATICS, 52, 0, 1, 0,	/* symbol (_INITSTATICS), 1 statics */
	HB_P_ENDPROC
/* 00006 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

