/*
 * xHarbour Compiler, build 82.0 (SimpLex)
 * Generated C source code from <c:/EDUCAR/program/hollow.prg>
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "c:/EDUCAR/program/hollow.prg"

HB_FUNC_STATIC( TEXTO );
HB_FUNC( SAYROTATED );
HB_FUNC_STATIC( DRAWROTATED );
HB_FUNC( TEST );
HB_FUNC( HOLLOWTEXT );
HB_FUNC_STATIC( BEGINPATH );
HB_FUNC_STATIC( ENDPATH );
HB_FUNC_STATIC( STROKEPATH );
extern HB_FUNC( TDIALOG );
extern HB_FUNC( TFONT );
extern HB_FUNC( SETTEXTCOLOR );
extern HB_FUNC( SETBKCOLOR );
extern HB_FUNC( SETBKMODE );
extern HB_FUNC( SELECTOBJECT );
extern HB_FUNC( TEXTOUT );
extern HB_FUNC( LEN );
extern HB_FUNC( MSGGET );
extern HB_FUNC( TBITMAP );
extern HB_FUNC( DRAWBITMAP );
extern HB_FUNC( CREATEPEN );
extern HB_FUNC( DELETEOBJECT );
extern HB_FUNC( VALTYPE );
extern HB_FUNC( LOADLIBRARY );
extern HB_FUNC( ABS );
extern HB_FUNC( GETPROCADDRESS );
extern HB_FUNC( CALLDLL );
extern HB_FUNC( FREELIBRARY );
extern HB_FUNC( MSGALERT );
extern HB_FUNC( LTRIM );
extern HB_FUNC( STR );
extern HB_FUNC( ERRORSYS );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 5

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_HOLLOW )
{ "TEXTO", HB_FS_STATIC | HB_FS_PUBLIC | HB_FS_FIRST, HB_FUNCNAME( TEXTO ), (PHB_DYNS) 1 },
{ "NEW", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TDIALOG", HB_FS_PUBLIC, HB_FUNCNAME( TDIALOG ), NULL },
{ "TFONT", HB_FS_PUBLIC, HB_FUNCNAME( TFONT ), NULL },
{ "ACTIVATE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BLCLICKED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BMOVED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_BPAINTED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "SAYROTATED", HB_FS_PUBLIC, HB_FUNCNAME( SAYROTATED ), (PHB_DYNS) 1 },
{ "BRCLICKED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "HDC", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "DRAWROTATED", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( DRAWROTATED ), (PHB_DYNS) 1 },
{ "SETTEXTCOLOR", HB_FS_PUBLIC, HB_FUNCNAME( SETTEXTCOLOR ), NULL },
{ "SETBKCOLOR", HB_FS_PUBLIC, HB_FUNCNAME( SETBKCOLOR ), NULL },
{ "SETBKMODE", HB_FS_PUBLIC, HB_FUNCNAME( SETBKMODE ), NULL },
{ "SELECTOBJECT", HB_FS_PUBLIC, HB_FUNCNAME( SELECTOBJECT ), NULL },
{ "HFONT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TEXTOUT", HB_FS_PUBLIC, HB_FUNCNAME( TEXTOUT ), NULL },
{ "LEN", HB_FS_PUBLIC, HB_FUNCNAME( LEN ), NULL },
{ "TEST", HB_FS_PUBLIC, HB_FUNCNAME( TEST ), (PHB_DYNS) 1 },
{ "MSGGET", HB_FS_PUBLIC, HB_FUNCNAME( MSGGET ), NULL },
{ "DEFINE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TBITMAP", HB_FS_PUBLIC, HB_FUNCNAME( TBITMAP ), NULL },
{ "DRAWBITMAP", HB_FS_PUBLIC, HB_FUNCNAME( DRAWBITMAP ), NULL },
{ "HBITMAP", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NWIDTH", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NHEIGHT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "HOLLOWTEXT", HB_FS_PUBLIC, HB_FUNCNAME( HOLLOWTEXT ), (PHB_DYNS) 1 },
{ "END", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OFONT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NCLRTEXT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "CREATEPEN", HB_FS_PUBLIC, HB_FUNCNAME( CREATEPEN ), NULL },
{ "HPEN", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "HOLDPEN", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BEGINPATH", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( BEGINPATH ), (PHB_DYNS) 1 },
{ "ENDPATH", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( ENDPATH ), (PHB_DYNS) 1 },
{ "STROKEPATH", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( STROKEPATH ), (PHB_DYNS) 1 },
{ "DELETEOBJECT", HB_FS_PUBLIC, HB_FUNCNAME( DELETEOBJECT ), NULL },
{ "VALTYPE", HB_FS_PUBLIC, HB_FUNCNAME( VALTYPE ), NULL },
{ "LOADLIBRARY", HB_FS_PUBLIC, HB_FUNCNAME( LOADLIBRARY ), NULL },
{ "ABS", HB_FS_PUBLIC, HB_FUNCNAME( ABS ), NULL },
{ "GETPROCADDRESS", HB_FS_PUBLIC, HB_FUNCNAME( GETPROCADDRESS ), NULL },
{ "CALLDLL", HB_FS_PUBLIC, HB_FUNCNAME( CALLDLL ), NULL },
{ "FREELIBRARY", HB_FS_PUBLIC, HB_FUNCNAME( FREELIBRARY ), NULL },
{ "MSGALERT", HB_FS_PUBLIC, HB_FUNCNAME( MSGALERT ), NULL },
{ "LTRIM", HB_FS_PUBLIC, HB_FUNCNAME( LTRIM ), NULL },
{ "STR", HB_FS_PUBLIC, HB_FUNCNAME( STR ), NULL },
{ "ERRORSYS", HB_FS_PUBLIC, HB_FUNCNAME( ERRORSYS ), NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_HOLLOW )

#if defined(HB_STATIC_STARTUP)
   #pragma startup hb_vm_SymbolInit_HOLLOW
#elif defined(_MSC_VER)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_HOLLOW = hb_vm_SymbolInit_HOLLOW;
   #pragma data_seg()
#elif ! defined(__GNUC__)
   #pragma startup hb_vm_SymbolInit_HOLLOW
#endif

HB_FUNC_STATIC( TEXTO )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 3, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 7, 0,	/* 7 */
	HB_P_MESSAGE, 1, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 2,	/* TDIALOG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_PUSHSTRSHORT, 18,	/* 18 */
	'T', 'e', 'x', 't', 'o', ' ', 'e', 'n', ' ', 'D', 'i', 'a', 'l', 'o', 'g', 'o', 's', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 19,
	HB_P_POPLOCALNEAR, 3,	/* ODLGD */
/* 00060 */ HB_P_LINEOFFSET, 1,	/* 8 */
	HB_P_MESSAGE, 1, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 3,	/* TFONT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'A', 'r', 'i', 'a', 'l', 0, 
	HB_P_ZERO,
	HB_P_PUSHBYTE, 220,	/* -36 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHINT, 132, 3,	/* 900 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 17,
	HB_P_POPLOCALNEAR, 1,	/* OFONT1 */
/* 00101 */ HB_P_LINEOFFSET, 2,	/* 9 */
	HB_P_MESSAGE, 1, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 3,	/* TFONT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'A', 'r', 'i', 'a', 'l', 0, 
	HB_P_ZERO,
	HB_P_PUSHBYTE, 244,	/* -12 */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHINT, 132, 3,	/* 900 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 17,
	HB_P_POPLOCALNEAR, 2,	/* OFONT2 */
/* 00142 */ HB_P_LINEOFFSET, 6,	/* 13 */
	HB_P_MESSAGE, 4, 0,	/* ACTIVATE */
	HB_P_PUSHLOCALNEAR, 3,	/* ODLGD */
	HB_P_MESSAGE, 5, 0,	/* BLCLICKED */
	HB_P_PUSHLOCALNEAR, 3,	/* ODLGD */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 6, 0,	/* BMOVED */
	HB_P_PUSHLOCALNEAR, 3,	/* ODLGD */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 7, 0,	/* _BPAINTED */
	HB_P_PUSHLOCALNEAR, 3,	/* ODLGD */
	HB_P_PUSHBLOCK, 83, 0,	/* 83 */
	2, 0,	/* number of local parameters (2) */
	3, 0,	/* number of local variables (3) */
	3, 0,	/* ODLGD */
	1, 0,	/* OFONT1 */
	2, 0,	/* OFONT2 */
	HB_P_PUSHSYMNEAR, 8,	/* SAYROTATED */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_PUSHINT, 4, 1,	/* 260 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'T', 'e', 'x', 't', 'o', ' ', '1', ' ', 0, 
	HB_P_PUSHLOCALNEAR, 254,	/* localvar2 */
	HB_P_PUSHLONG, 0, 0, 255, 0,	/* 16711680 */
	HB_P_PUSHLONG, 0, 128, 0, 0,	/* 32768 */
	HB_P_TRUE,
	HB_P_DOSHORT, 8,
	HB_P_PUSHSYMNEAR, 8,	/* SAYROTATED */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_PUSHINT, 150, 0,	/* 150 */
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'T', 'e', 'x', 't', 'o', ' ', '2', 0, 
	HB_P_PUSHLOCALNEAR, 253,	/* localvar3 */
	HB_P_PUSHINT, 255, 0,	/* 255 */
	HB_P_PUSHLONG, 255, 255, 0, 0,	/* 65535 */
	HB_P_FALSE,
	HB_P_FUNCTIONSHORT, 8,
	HB_P_ENDBLOCK,
	HB_P_SENDSHORT, 1,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 9, 0,	/* BRCLICKED */
	HB_P_PUSHLOCALNEAR, 3,	/* ODLGD */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 9,
	HB_P_POP,
/* 00268 */ HB_P_LINEOFFSET, 8,	/* 15 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00273 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( SAYROTATED )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 8,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 25, 0,	/* 25 */
	HB_P_MESSAGE, 10, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_POPLOCALNEAR, 9,	/* HDC */
/* 00015 */ HB_P_LINEOFFSET, 2,	/* 27 */
	HB_P_PUSHLOCALNEAR, 6,	/* NCLRTEXT */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00028) */
	HB_P_PUSHINT, 255, 0,	/* 255 */
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00030) */
	HB_P_PUSHLOCALNEAR, 6,	/* NCLRTEXT */
	HB_P_POPLOCALNEAR, 6,	/* NCLRTEXT */
	HB_P_PUSHLOCALNEAR, 8,	/* L3D */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00041) */
	HB_P_TRUE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00043) */
	HB_P_PUSHLOCALNEAR, 8,	/* L3D */
	HB_P_POPLOCALNEAR, 8,	/* L3D */
	HB_P_PUSHLOCALNEAR, 8,	/* L3D */
	HB_P_JUMPFALSENEAR, 57,	/* 57 (abs: 00104) */
/* 00049 */ HB_P_LINEOFFSET, 5,	/* 30 */
	HB_P_PUSHSYMNEAR, 11,	/* DRAWROTATED */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 9,	/* HDC */
	HB_P_PUSHLOCALNEAR, 4,	/* CPROMPT */
	HB_P_PUSHLOCALNEAR, 2,	/* Y */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_PUSHLOCALNEAR, 3,	/* X */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_ZERO,
	HB_P_PUSHLOCALNEAR, 7,	/* NCLRPANE */
	HB_P_PUSHLOCALNEAR, 5,	/* OFONT */
	HB_P_DOSHORT, 7,
/* 00075 */ HB_P_LINEOFFSET, 6,	/* 31 */
	HB_P_PUSHSYMNEAR, 11,	/* DRAWROTATED */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 9,	/* HDC */
	HB_P_PUSHLOCALNEAR, 4,	/* CPROMPT */
	HB_P_PUSHLOCALNEAR, 2,	/* Y */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_PUSHLOCALNEAR, 3,	/* X */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_PUSHLOCALNEAR, 6,	/* NCLRTEXT */
	HB_P_PUSHLOCALNEAR, 7,	/* NCLRPANE */
	HB_P_PUSHLOCALNEAR, 5,	/* OFONT */
	HB_P_DOSHORT, 7,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00104) */
/* 00104 */ HB_P_LINEOFFSET, 9,	/* 34 */
	HB_P_PUSHSYMNEAR, 11,	/* DRAWROTATED */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 9,	/* HDC */
	HB_P_PUSHLOCALNEAR, 4,	/* CPROMPT */
	HB_P_PUSHLOCALNEAR, 2,	/* Y */
	HB_P_PUSHLOCALNEAR, 3,	/* X */
	HB_P_PUSHLOCALNEAR, 6,	/* NCLRTEXT */
	HB_P_PUSHLOCALNEAR, 7,	/* NCLRPANE */
	HB_P_PUSHLOCALNEAR, 5,	/* OFONT */
	HB_P_DOSHORT, 7,
/* 00125 */ HB_P_LINEOFFSET, 11,	/* 36 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00130 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( DRAWROTATED )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 5, 7,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 43, 0,	/* 43 */
	HB_P_PUSHSYMNEAR, 12,	/* SETTEXTCOLOR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* HDC */
	HB_P_PUSHLOCALNEAR, 5,	/* NCLRTEXT */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 10,	/* NOLDCLRTEXT */
/* 00017 */ HB_P_LINEOFFSET, 2,	/* 45 */
	HB_P_PUSHLOCALNEAR, 6,	/* NCLRPANE */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 17,	/* 17 (abs: 00040) */
/* 00025 */ HB_P_LINEOFFSET, 3,	/* 46 */
	HB_P_PUSHSYMNEAR, 13,	/* SETBKCOLOR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* HDC */
	HB_P_PUSHLOCALNEAR, 6,	/* NCLRPANE */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 11,	/* NOLDCLRPANE */
	HB_P_JUMPNEAR, 14,	/* 14 (abs: 00052) */
/* 00040 */ HB_P_LINEOFFSET, 5,	/* 48 */
	HB_P_PUSHSYMNEAR, 14,	/* SETBKMODE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* HDC */
	HB_P_ONE,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 12,	/* NOLDBKMODE */
/* 00052 */ HB_P_LINEOFFSET, 8,	/* 51 */
	HB_P_PUSHSYMNEAR, 15,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* HDC */
	HB_P_MESSAGE, 16, 0,	/* HFONT */
	HB_P_PUSHLOCALNEAR, 7,	/* OFONT */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 8,	/* HOLDFONT */
/* 00070 */ HB_P_LINEOFFSET, 10,	/* 53 */
	HB_P_PUSHSYMNEAR, 17,	/* TEXTOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* HDC */
	HB_P_PUSHLOCALNEAR, 3,	/* Y */
	HB_P_PUSHLOCALNEAR, 4,	/* X */
	HB_P_PUSHLOCALNEAR, 2,	/* CPROMPT */
	HB_P_PUSHSYMNEAR, 18,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* CPROMPT */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DOSHORT, 5,
/* 00092 */ HB_P_LINEOFFSET, 11,	/* 54 */
	HB_P_PUSHSYMNEAR, 15,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* HDC */
	HB_P_PUSHLOCALNEAR, 8,	/* HOLDFONT */
	HB_P_DOSHORT, 2,
/* 00103 */ HB_P_LINEOFFSET, 13,	/* 56 */
	HB_P_PUSHLOCALNEAR, 6,	/* NCLRPANE */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 15,	/* 15 (abs: 00124) */
/* 00111 */ HB_P_LINEOFFSET, 14,	/* 57 */
	HB_P_PUSHSYMNEAR, 13,	/* SETBKCOLOR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* HDC */
	HB_P_PUSHLOCALNEAR, 11,	/* NOLDCLRPANE */
	HB_P_DOSHORT, 2,
	HB_P_JUMPNEAR, 13,	/* 13 (abs: 00135) */
/* 00124 */ HB_P_LINEOFFSET, 16,	/* 59 */
	HB_P_PUSHSYMNEAR, 14,	/* SETBKMODE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* HDC */
	HB_P_PUSHLOCALNEAR, 12,	/* NOLDBKMODE */
	HB_P_DOSHORT, 2,
/* 00135 */ HB_P_LINEOFFSET, 19,	/* 62 */
	HB_P_PUSHSYMNEAR, 12,	/* SETTEXTCOLOR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* HDC */
	HB_P_PUSHLOCALNEAR, 10,	/* NOLDCLRTEXT */
	HB_P_DOSHORT, 2,
/* 00146 */ HB_P_LINEOFFSET, 21,	/* 64 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00151 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( TEST )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 4, 0,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 69, 0,	/* 69 */
	HB_P_LOCALNEARSETINT, 4, 44, 1,	/* N300 300*/
/* 00010 */ HB_P_LINEOFFSET, 2,	/* 71 */
	HB_P_PUSHSYMNEAR, 20,	/* MSGGET */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'i', 'n', 'g', 'r', 'e', 's', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'v', 'a', 'l', 'o', 'e', 0, 
	HB_P_PUSHLOCALREF, 4, 0,	/* N300 */
	HB_P_DOSHORT, 3,
/* 00037 */ HB_P_LINEOFFSET, 4,	/* 73 */
	HB_P_MESSAGE, 21, 0,	/* DEFINE */
	HB_P_PUSHSYMNEAR, 22,	/* TBITMAP */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'b', 'a', 'c', 'k', '.', 'b', 'm', 'p', 0, 
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 3,
	HB_P_POPLOCALNEAR, 3,	/* OBMP */
/* 00064 */ HB_P_LINEOFFSET, 5,	/* 74 */
	HB_P_MESSAGE, 1, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 3,	/* TFONT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'A', 'r', 'i', 'a', 'l', 0, 
	HB_P_ZERO,
	HB_P_PUSHBYTE, 220,	/* -36 */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHLOCALNEAR, 4,	/* N300 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 17,
	HB_P_POPLOCALNEAR, 2,	/* OFONT */
/* 00104 */ HB_P_LINEOFFSET, 7,	/* 76 */
	HB_P_MESSAGE, 1, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 2,	/* TDIALOG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 18,	/* 18 */
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_PUSHSTRSHORT, 18,	/* 18 */
	'T', 'e', 'x', 't', 'o', ' ', 's', 'i', 'n', ' ', 'r', 'e', 'l', 'l', 'e', 'n', 'o', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 19,
	HB_P_POPLOCALNEAR, 1,	/* ODLG */
/* 00158 */ HB_P_LINEOFFSET, 11,	/* 80 */
	HB_P_MESSAGE, 4, 0,	/* ACTIVATE */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_MESSAGE, 5, 0,	/* BLCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 6, 0,	/* BMOVED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 7, 0,	/* _BPAINTED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_PUSHBLOCK, 92, 0,	/* 92 */
	2, 0,	/* number of local parameters (2) */
	3, 0,	/* number of local variables (3) */
	1, 0,	/* ODLG */
	3, 0,	/* OBMP */
	2, 0,	/* OFONT */
	HB_P_PUSHSYMNEAR, 23,	/* DRAWBITMAP */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 10, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 24, 0,	/* HBITMAP */
	HB_P_PUSHLOCALNEAR, 254,	/* localvar2 */
	HB_P_SENDSHORT, 0,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_MESSAGE, 25, 0,	/* NWIDTH */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 26, 0,	/* NHEIGHT */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_DOSHORT, 6,
	HB_P_PUSHSYMNEAR, 27,	/* HOLLOWTEXT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_PUSHINT, 200, 0,	/* 200 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHSTRSHORT, 20,	/* 20 */
	' ', 'T', 'e', 'x', 't', 'o', ' ', 's', 'i', 'n', ' ', 'r', 'e', 'l', 'l', 'e', 'n', 'o', ' ', 0, 
	HB_P_PUSHLOCALNEAR, 253,	/* localvar3 */
	HB_P_PUSHLONG, 0, 128, 0, 0,	/* 32768 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 7,
	HB_P_ENDBLOCK,
	HB_P_SENDSHORT, 1,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 9, 0,	/* BRCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 9,
	HB_P_POP,
/* 00293 */ HB_P_LINEOFFSET, 13,	/* 82 */
	HB_P_MESSAGE, 28, 0,	/* END */
	HB_P_PUSHLOCALNEAR, 2,	/* OFONT */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_PUSHNIL,
	HB_P_POPLOCALNEAR, 2,	/* OFONT */
/* 00306 */ HB_P_LINEOFFSET, 14,	/* 83 */
	HB_P_MESSAGE, 28, 0,	/* END */
	HB_P_PUSHLOCALNEAR, 3,	/* OBMP */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_PUSHNIL,
	HB_P_POPLOCALNEAR, 3,	/* OBMP */
/* 00319 */ HB_P_LINEOFFSET, 16,	/* 85 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00324 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( HOLLOWTEXT )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 2, 8,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 101, 0,	/* 101 */
	HB_P_MESSAGE, 10, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_POPLOCALNEAR, 9,	/* HDC */
/* 00015 */ HB_P_LINEOFFSET, 3,	/* 104 */
	HB_P_PUSHLOCALNEAR, 5,	/* OFONT */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 00032) */
	HB_P_MESSAGE, 29, 0,	/* OFONT */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00034) */
	HB_P_PUSHLOCALNEAR, 5,	/* OFONT */
	HB_P_POPLOCALNEAR, 5,	/* OFONT */
	HB_P_PUSHLOCALNEAR, 6,	/* NCOLOR */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 00051) */
	HB_P_MESSAGE, 30, 0,	/* NCLRTEXT */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00053) */
	HB_P_PUSHLOCALNEAR, 6,	/* NCOLOR */
	HB_P_POPLOCALNEAR, 6,	/* NCOLOR */
	HB_P_PUSHLOCALNEAR, 7,	/* NWIDTH */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00064) */
	HB_P_ONE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00066) */
	HB_P_PUSHLOCALNEAR, 7,	/* NWIDTH */
	HB_P_POPLOCALNEAR, 7,	/* NWIDTH */
	HB_P_PUSHLOCALNEAR, 8,	/* NSTYLE */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00077) */
	HB_P_ZERO,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00079) */
	HB_P_PUSHLOCALNEAR, 8,	/* NSTYLE */
	HB_P_POPLOCALNEAR, 8,	/* NSTYLE */
	HB_P_PUSHSYMNEAR, 15,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 9,	/* HDC */
	HB_P_MESSAGE, 16, 0,	/* HFONT */
	HB_P_PUSHLOCALNEAR, 5,	/* OFONT */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 10,	/* NOLDFONT */
/* 00097 */ HB_P_LINEOFFSET, 6,	/* 107 */
	HB_P_PUSHSYMNEAR, 31,	/* CREATEPEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 8,	/* NSTYLE */
	HB_P_PUSHLOCALNEAR, 7,	/* NWIDTH */
	HB_P_PUSHLOCALNEAR, 6,	/* NCOLOR */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPVARIABLE, 32, 0,	/* HPEN */
/* 00113 */ HB_P_LINEOFFSET, 7,	/* 108 */
	HB_P_PUSHSYMNEAR, 15,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 9,	/* HDC */
	HB_P_PUSHVARIABLE, 32, 0,	/* HPEN */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPVARIABLE, 33, 0,	/* HOLDPEN */
/* 00128 */ HB_P_LINEOFFSET, 9,	/* 110 */
	HB_P_PUSHSYMNEAR, 34,	/* BEGINPATH */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 9,	/* HDC */
	HB_P_DOSHORT, 1,
/* 00137 */ HB_P_LINEOFFSET, 10,	/* 111 */
	HB_P_PUSHSYMNEAR, 17,	/* TEXTOUT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 9,	/* HDC */
	HB_P_PUSHLOCALNEAR, 2,	/* Y */
	HB_P_PUSHLOCALNEAR, 3,	/* X */
	HB_P_PUSHLOCALNEAR, 4,	/* CTEXT */
	HB_P_PUSHSYMNEAR, 18,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* CTEXT */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DOSHORT, 5,
/* 00159 */ HB_P_LINEOFFSET, 11,	/* 112 */
	HB_P_PUSHSYMNEAR, 35,	/* ENDPATH */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 9,	/* HDC */
	HB_P_DOSHORT, 1,
/* 00168 */ HB_P_LINEOFFSET, 12,	/* 113 */
	HB_P_PUSHSYMNEAR, 36,	/* STROKEPATH */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 9,	/* HDC */
	HB_P_DOSHORT, 1,
/* 00177 */ HB_P_LINEOFFSET, 14,	/* 115 */
	HB_P_PUSHSYMNEAR, 15,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 9,	/* HDC */
	HB_P_PUSHLOCALNEAR, 10,	/* NOLDFONT */
	HB_P_DOSHORT, 2,
/* 00188 */ HB_P_LINEOFFSET, 15,	/* 116 */
	HB_P_PUSHSYMNEAR, 15,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 9,	/* HDC */
	HB_P_PUSHVARIABLE, 33, 0,	/* HOLDPEN */
	HB_P_DOSHORT, 2,
/* 00200 */ HB_P_LINEOFFSET, 16,	/* 117 */
	HB_P_PUSHSYMNEAR, 37,	/* DELETEOBJECT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 32, 0,	/* HPEN */
	HB_P_DOSHORT, 1,
/* 00210 */ HB_P_LINEOFFSET, 18,	/* 119 */
	HB_P_ENDPROC
/* 00213 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( BEGINPATH )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 3, 1,	/* locals, params */
	HB_P_PUSHSYMNEAR, 38,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'G', 'D', 'I', '3', '2', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 12,	/* 12 (abs: 00033) */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'G', 'D', 'I', '3', '2', 0, 
	HB_P_JUMPNEAR, 15,	/* 15 (abs: 00046) */
	HB_P_PUSHSYMNEAR, 39,	/* LOADLIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'G', 'D', 'I', '3', '2', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 2,	/* HDLL */
	HB_P_PUSHSYMNEAR, 40,	/* ABS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 72,	/* 72 (abs: 00130) */
	HB_P_PUSHSYMNEAR, 41,	/* GETPROCADDRESS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'B', 'e', 'g', 'i', 'n', 'P', 'a', 't', 'h', 0, 
	HB_P_TRUE,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 4,	/* CFARPROC */
	HB_P_PUSHSYMNEAR, 42,	/* CALLDLL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* CFARPROC */
	HB_P_PUSHLOCALNEAR, 1,	/* HDC */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 3,	/* URESULT */
	HB_P_PUSHSYMNEAR, 38,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'G', 'D', 'I', '3', '2', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00120) */
	HB_P_PUSHNIL,
	HB_P_JUMPNEAR, 9,	/* 9 (abs: 00127) */
	HB_P_PUSHSYMNEAR, 43,	/* FREELIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 57,	/* 57 (abs: 00185) */
	HB_P_PUSHSYMNEAR, 44,	/* MSGALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'E', 'r', 'r', 'o', 'r', ' ', 'c', 'o', 'd', 'e', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 45,	/* LTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 46,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	' ', 'l', 'o', 'a', 'd', 'i', 'n', 'g', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'G', 'D', 'I', '3', '2', 0, 
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHLOCALNEAR, 3,	/* URESULT */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00189 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( ENDPATH )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 3, 1,	/* locals, params */
	HB_P_PUSHSYMNEAR, 38,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'G', 'D', 'I', '3', '2', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 12,	/* 12 (abs: 00033) */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'G', 'D', 'I', '3', '2', 0, 
	HB_P_JUMPNEAR, 15,	/* 15 (abs: 00046) */
	HB_P_PUSHSYMNEAR, 39,	/* LOADLIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'G', 'D', 'I', '3', '2', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 2,	/* HDLL */
	HB_P_PUSHSYMNEAR, 40,	/* ABS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 70,	/* 70 (abs: 00128) */
	HB_P_PUSHSYMNEAR, 41,	/* GETPROCADDRESS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'E', 'n', 'd', 'P', 'a', 't', 'h', 0, 
	HB_P_TRUE,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 4,	/* CFARPROC */
	HB_P_PUSHSYMNEAR, 42,	/* CALLDLL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* CFARPROC */
	HB_P_PUSHLOCALNEAR, 1,	/* HDC */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 3,	/* URESULT */
	HB_P_PUSHSYMNEAR, 38,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'G', 'D', 'I', '3', '2', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00118) */
	HB_P_PUSHNIL,
	HB_P_JUMPNEAR, 9,	/* 9 (abs: 00125) */
	HB_P_PUSHSYMNEAR, 43,	/* FREELIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 57,	/* 57 (abs: 00183) */
	HB_P_PUSHSYMNEAR, 44,	/* MSGALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'E', 'r', 'r', 'o', 'r', ' ', 'c', 'o', 'd', 'e', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 45,	/* LTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 46,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	' ', 'l', 'o', 'a', 'd', 'i', 'n', 'g', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'G', 'D', 'I', '3', '2', 0, 
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHLOCALNEAR, 3,	/* URESULT */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00187 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( STROKEPATH )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 3, 1,	/* locals, params */
	HB_P_PUSHSYMNEAR, 38,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'G', 'D', 'I', '3', '2', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 12,	/* 12 (abs: 00033) */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'G', 'D', 'I', '3', '2', 0, 
	HB_P_JUMPNEAR, 15,	/* 15 (abs: 00046) */
	HB_P_PUSHSYMNEAR, 39,	/* LOADLIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'G', 'D', 'I', '3', '2', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 2,	/* HDLL */
	HB_P_PUSHSYMNEAR, 40,	/* ABS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 73,	/* 73 (abs: 00131) */
	HB_P_PUSHSYMNEAR, 41,	/* GETPROCADDRESS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'S', 't', 'r', 'o', 'k', 'e', 'P', 'a', 't', 'h', 0, 
	HB_P_TRUE,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 4,	/* CFARPROC */
	HB_P_PUSHSYMNEAR, 42,	/* CALLDLL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* CFARPROC */
	HB_P_PUSHLOCALNEAR, 1,	/* HDC */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 3,	/* URESULT */
	HB_P_PUSHSYMNEAR, 38,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'G', 'D', 'I', '3', '2', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00121) */
	HB_P_PUSHNIL,
	HB_P_JUMPNEAR, 9,	/* 9 (abs: 00128) */
	HB_P_PUSHSYMNEAR, 43,	/* FREELIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 57,	/* 57 (abs: 00186) */
	HB_P_PUSHSYMNEAR, 44,	/* MSGALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'E', 'r', 'r', 'o', 'r', ' ', 'c', 'o', 'd', 'e', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 45,	/* LTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 46,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	' ', 'l', 'o', 'a', 'd', 'i', 'n', 'g', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'G', 'D', 'I', '3', '2', 0, 
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHLOCALNEAR, 3,	/* URESULT */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00190 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

