/*
 * xHarbour Compiler, build 82.0 (SimpLex)
 * Generated C source code from <c:/EDUCAR/program/PRUEBA.prg>
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "c:/EDUCAR/program/PRUEBA.prg"

HB_FUNC( PRUEBA );
HB_FUNC( RMMDT );
HB_FUNC_STATIC( INI_ODLGDT );
HB_FUNC_STATIC( AJUSTA );
HB_FUNC_STATIC( VALDIA );
HB_FUNC_STATIC( MESANO );
HB_FUNC( _CONFDATA );
HB_FUNC( _VERKEY );
HB_FUNC_STATIC( MYPAINT );
HB_FUNC( SETLAYEREDWINDOWATTRIBUTES );

static HARBOUR hb_INITSTATICS( void );

extern HB_FUNC( SET );
extern HB_FUNC( __SETCENTURY );
extern HB_FUNC( DATE );
extern HB_FUNC( CTOD );
extern HB_FUNC( TDIALOG );
extern HB_FUNC( TGET );
extern HB_FUNC( PCOUNT );
extern HB_FUNC( TBUTTON );
extern HB_FUNC( __MVPRIVATE );
extern HB_FUNC( STRZERO );
extern HB_FUNC( MONTH );
extern HB_FUNC( YEAR );
extern HB_FUNC( TFONT );
extern HB_FUNC( NOR );
extern HB_FUNC( ALLTRIM );
extern HB_FUNC( DTOC );
extern HB_FUNC( TSAY );
extern HB_FUNC( TBTNBMP );
extern HB_FUNC( STR );
extern HB_FUNC( CLIENTTOSCREEN );
extern HB_FUNC( GETCOORS );
extern HB_FUNC( GETDESKTOPWINDOW );
extern HB_FUNC( DOW );
extern HB_FUNC( DAY );
extern HB_FUNC( CREATEPEN );
extern HB_FUNC( SELECTOBJECT );
extern HB_FUNC( ARC );
extern HB_FUNC( DELETEOBJECT );
extern HB_FUNC( NRGB );
extern HB_FUNC( MOVETO );
extern HB_FUNC( LINETO );
extern HB_FUNC( SETWINDOWLONG );
extern HB_FUNC( GETWINDOWLONG );
extern HB_FUNC( VALTYPE );
extern HB_FUNC( LOADLIBRARY );
extern HB_FUNC( ABS );
extern HB_FUNC( GETPROCADDRESS );
extern HB_FUNC( EMPTY );
extern HB_FUNC( CALLDLL );
extern HB_FUNC( FREELIBRARY );
extern HB_FUNC( MSGALERT );
extern HB_FUNC( LTRIM );
extern HB_FUNC( ERRORSYS );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 5

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_PRUEBA )
{ "PRUEBA", HB_FS_PUBLIC | HB_FS_FIRST, HB_FUNCNAME( PRUEBA ), (PHB_DYNS) 1 },
{ "SET", HB_FS_PUBLIC, HB_FUNCNAME( SET ), NULL },
{ "__SETCENTURY", HB_FS_PUBLIC, HB_FUNCNAME( __SETCENTURY ), NULL },
{ "DATE", HB_FS_PUBLIC, HB_FUNCNAME( DATE ), NULL },
{ "DDTA", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "CTOD", HB_FS_PUBLIC, HB_FUNCNAME( CTOD ), NULL },
{ "DDTA2", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NEW", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TDIALOG", HB_FS_PUBLIC, HB_FUNCNAME( TDIALOG ), NULL },
{ "ODIAG", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TGET", HB_FS_PUBLIC, HB_FUNCNAME( TGET ), NULL },
{ "PCOUNT", HB_FS_PUBLIC, HB_FUNCNAME( PCOUNT ), NULL },
{ "OGETDATA", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TBUTTON", HB_FS_PUBLIC, HB_FUNCNAME( TBUTTON ), NULL },
{ "RMMDT", HB_FS_PUBLIC, HB_FUNCNAME( RMMDT ), (PHB_DYNS) 1 },
{ "OGETDATA2", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ACTIVATE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BLCLICKED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BMOVED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BPAINTED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BRCLICKED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD1", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD2", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD3", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD4", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD5", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD6", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD7", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD8", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD9", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD10", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "__MVPRIVATE", HB_FS_PUBLIC, HB_FUNCNAME( __MVPRIVATE ), NULL },
{ "OSD11", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD12", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD13", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD14", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD15", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD16", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD17", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD18", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD19", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD20", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD21", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD22", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD23", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD24", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD25", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD26", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD27", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD28", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD29", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD30", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OSD31", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "STRZERO", HB_FS_PUBLIC, HB_FUNCNAME( STRZERO ), NULL },
{ "MONTH", HB_FS_PUBLIC, HB_FUNCNAME( MONTH ), NULL },
{ "YEAR", HB_FS_PUBLIC, HB_FUNCNAME( YEAR ), NULL },
{ "TFONT", HB_FS_PUBLIC, HB_FUNCNAME( TFONT ), NULL },
{ "OFONT1", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OFONT2", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OFONT3", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NOR", HB_FS_PUBLIC, HB_FUNCNAME( NOR ), NULL },
{ "_BLCLICKED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "END", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_BKEYDOWN", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_VERKEY", HB_FS_PUBLIC, HB_FUNCNAME( _VERKEY ), (PHB_DYNS) 1 },
{ "_BPAINTED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "MYPAINT", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( MYPAINT ), (PHB_DYNS) 1 },
{ "INI_ODLGDT", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( INI_ODLGDT ), (PHB_DYNS) 1 },
{ "SETTEXT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "SETFOCUS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ALLTRIM", HB_FS_PUBLIC, HB_FUNCNAME( ALLTRIM ), NULL },
{ "DTOC", HB_FS_PUBLIC, HB_FUNCNAME( DTOC ), NULL },
{ "TSAY", HB_FS_PUBLIC, HB_FUNCNAME( TSAY ), NULL },
{ "TBTNBMP", HB_FS_PUBLIC, HB_FUNCNAME( TBTNBMP ), NULL },
{ "MESANO", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( MESANO ), (PHB_DYNS) 1 },
{ "AJUSTA", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( AJUSTA ), (PHB_DYNS) 1 },
{ "PIXEL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "STR", HB_FS_PUBLIC, HB_FUNCNAME( STR ), NULL },
{ "_LWANTCLICK", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_BLBUTTONUP", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "CLIENTTOSCREEN", HB_FS_PUBLIC, HB_FUNCNAME( CLIENTTOSCREEN ), NULL },
{ "HWND", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "GETCOORS", HB_FS_PUBLIC, HB_FUNCNAME( GETCOORS ), NULL },
{ "GETDESKTOPWINDOW", HB_FS_PUBLIC, HB_FUNCNAME( GETDESKTOPWINDOW ), NULL },
{ "MOVE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NHEIGHT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "DOW", HB_FS_PUBLIC, HB_FUNCNAME( DOW ), NULL },
{ "VALDIA", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( VALDIA ), (PHB_DYNS) 1 },
{ "SETCOLOR", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "DAY", HB_FS_PUBLIC, HB_FUNCNAME( DAY ), NULL },
{ "SETFONT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NTOP", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NLEFT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "SHOW", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "HIDE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_CONFDATA", HB_FS_PUBLIC, HB_FUNCNAME( _CONFDATA ), (PHB_DYNS) 1 },
{ "CCAPTION", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "GETDC", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "CREATEPEN", HB_FS_PUBLIC, HB_FUNCNAME( CREATEPEN ), NULL },
{ "SELECTOBJECT", HB_FS_PUBLIC, HB_FUNCNAME( SELECTOBJECT ), NULL },
{ "HDC", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "HOLDPEN", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ARC", HB_FS_PUBLIC, HB_FUNCNAME( ARC ), NULL },
{ "DELETEOBJECT", HB_FS_PUBLIC, HB_FUNCNAME( DELETEOBJECT ), NULL },
{ "NRGB", HB_FS_PUBLIC, HB_FUNCNAME( NRGB ), NULL },
{ "MOVETO", HB_FS_PUBLIC, HB_FUNCNAME( MOVETO ), NULL },
{ "LINETO", HB_FS_PUBLIC, HB_FUNCNAME( LINETO ), NULL },
{ "RELEASEDC", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "REFRESH", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "SETWINDOWLONG", HB_FS_PUBLIC, HB_FUNCNAME( SETWINDOWLONG ), NULL },
{ "GETWINDOWLONG", HB_FS_PUBLIC, HB_FUNCNAME( GETWINDOWLONG ), NULL },
{ "SETLAYEREDWINDOWATTRIBUTES", HB_FS_PUBLIC, HB_FUNCNAME( SETLAYEREDWINDOWATTRIBUTES ), (PHB_DYNS) 1 },
{ "VALTYPE", HB_FS_PUBLIC, HB_FUNCNAME( VALTYPE ), NULL },
{ "LOADLIBRARY", HB_FS_PUBLIC, HB_FUNCNAME( LOADLIBRARY ), NULL },
{ "ABS", HB_FS_PUBLIC, HB_FUNCNAME( ABS ), NULL },
{ "GETPROCADDRESS", HB_FS_PUBLIC, HB_FUNCNAME( GETPROCADDRESS ), NULL },
{ "EMPTY", HB_FS_PUBLIC, HB_FUNCNAME( EMPTY ), NULL },
{ "CALLDLL", HB_FS_PUBLIC, HB_FUNCNAME( CALLDLL ), NULL },
{ "FREELIBRARY", HB_FS_PUBLIC, HB_FUNCNAME( FREELIBRARY ), NULL },
{ "MSGALERT", HB_FS_PUBLIC, HB_FUNCNAME( MSGALERT ), NULL },
{ "LTRIM", HB_FS_PUBLIC, HB_FUNCNAME( LTRIM ), NULL },
{ "ERRORSYS", HB_FS_PUBLIC, HB_FUNCNAME( ERRORSYS ), NULL },
{ "(_INITSTATICS)", HB_FS_INIT | HB_FS_EXIT, hb_INITSTATICS, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_PRUEBA )

#if defined(HB_STATIC_STARTUP)
   #pragma startup hb_vm_SymbolInit_PRUEBA
#elif defined(_MSC_VER)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_PRUEBA = hb_vm_SymbolInit_PRUEBA;
   #pragma data_seg()
#elif ! defined(__GNUC__)
   #pragma startup hb_vm_SymbolInit_PRUEBA
#endif

HB_FUNC( PRUEBA )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 21, 0,	/* 21 */
	HB_P_PUSHSYMNEAR, 1,	/* SET */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_PUSHSYMNEAR, 2,	/* __SETCENTURY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPFALSENEAR, 17,	/* 17 (abs: 00030) */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'd', 'd', '/', 'm', 'm', '/', 'y', 'y', 'y', 'y', 0, 
	HB_P_JUMPNEAR, 13,	/* 13 (abs: 00041) */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'd', 'd', '/', 'm', 'm', '/', 'y', 'y', 0, 
	HB_P_DOSHORT, 2,
/* 00043 */ HB_P_LINEOFFSET, 1,	/* 22 */
	HB_P_PUSHSYMNEAR, 2,	/* __SETCENTURY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'O', 'N', 0, 
	HB_P_DOSHORT, 1,
/* 00055 */ HB_P_LINEOFFSET, 2,	/* 23 */
	HB_P_PUSHSYMNEAR, 3,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_POPVARIABLE, 4, 0,	/* DDTA */
/* 00065 */ HB_P_LINEOFFSET, 3,	/* 24 */
	HB_P_PUSHSYMNEAR, 5,	/* CTOD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'0', '5', '/', '0', '8', '/', '2', '0', '0', '7', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPVARIABLE, 6, 0,	/* DDTA2 */
/* 00088 */ HB_P_LINEOFFSET, 5,	/* 26 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 8,	/* TDIALOG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	't', 'e', 's', 't', 'e', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 19,
	HB_P_POPVARIABLE, 9, 0,	/* ODIAG */
/* 00129 */ HB_P_LINEOFFSET, 7,	/* 28 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 10,	/* TGET */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBLOCK, 28, 0,	/* 28 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 11,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00164) */
	HB_P_PUSHVARIABLE, 4, 0,	/* DDTA */
	HB_P_JUMPNEAR, 8,	/* 8 (abs: 00170) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 4, 0,	/* DDTA */
	HB_P_ENDBLOCK,
	HB_P_PUSHVARIABLE, 9, 0,	/* ODIAG */
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 29,
	HB_P_POPVARIABLE, 12, 0,	/* OGETDATA */
/* 00206 */ HB_P_LINEOFFSET, 8,	/* 29 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 13,	/* TBUTTON */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 52,	/* 52 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'?', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 14,	/* 14 */
	HB_P_PUSHSYMNEAR, 14,	/* RMMDT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 12, 0,	/* OGETDATA */
	HB_P_PUSHMEMVARREF, 4, 0,	/* DDTA */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_ENDBLOCK,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 17,
	HB_P_POP,
/* 00256 */ HB_P_LINEOFFSET, 10,	/* 31 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 10,	/* TGET */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 70,	/* 70 */
	HB_P_PUSHBLOCK, 28, 0,	/* 28 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 11,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00291) */
	HB_P_PUSHVARIABLE, 6, 0,	/* DDTA2 */
	HB_P_JUMPNEAR, 8,	/* 8 (abs: 00297) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 6, 0,	/* DDTA2 */
	HB_P_ENDBLOCK,
	HB_P_PUSHVARIABLE, 9, 0,	/* ODIAG */
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 29,
	HB_P_POPVARIABLE, 15, 0,	/* OGETDATA2 */
/* 00333 */ HB_P_LINEOFFSET, 11,	/* 32 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 13,	/* TBUTTON */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 112,	/* 112 */
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'?', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCKSHORT, 15,	/* 15 */
	HB_P_PUSHSYMNEAR, 14,	/* RMMDT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 15, 0,	/* OGETDATA2 */
	HB_P_PUSHMEMVARREF, 6, 0,	/* DDTA2 */
	HB_P_TRUE,
	HB_P_FUNCTIONSHORT, 3,
	HB_P_ENDBLOCK,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 17,
	HB_P_POP,
/* 00384 */ HB_P_LINEOFFSET, 13,	/* 34 */
	HB_P_MESSAGE, 16, 0,	/* ACTIVATE */
	HB_P_PUSHVARIABLE, 9, 0,	/* ODIAG */
	HB_P_MESSAGE, 17, 0,	/* BLCLICKED */
	HB_P_PUSHVARIABLE, 9, 0,	/* ODIAG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 18, 0,	/* BMOVED */
	HB_P_PUSHVARIABLE, 9, 0,	/* ODIAG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 19, 0,	/* BPAINTED */
	HB_P_PUSHVARIABLE, 9, 0,	/* ODIAG */
	HB_P_SENDSHORT, 0,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 20, 0,	/* BRCLICKED */
	HB_P_PUSHVARIABLE, 9, 0,	/* ODIAG */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 9,
	HB_P_POP,
	HB_P_ENDPROC
/* 00433 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( RMMDT )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 0, 3,	/* locals, params */
	HB_P_SFRAME, 122, 0,	/* symbol (_INITSTATICS) */
/* 00006 */ HB_P_BASELINE, 39, 0,	/* 39 */
	HB_P_PUSHSYMNEAR, 31,	/* __MVPRIVATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 21,	/* OSD1 */
	HB_P_PUSHSYMNEAR, 22,	/* OSD2 */
	HB_P_PUSHSYMNEAR, 23,	/* OSD3 */
	HB_P_PUSHSYMNEAR, 24,	/* OSD4 */
	HB_P_PUSHSYMNEAR, 25,	/* OSD5 */
	HB_P_PUSHSYMNEAR, 26,	/* OSD6 */
	HB_P_PUSHSYMNEAR, 27,	/* OSD7 */
	HB_P_PUSHSYMNEAR, 28,	/* OSD8 */
	HB_P_PUSHSYMNEAR, 29,	/* OSD9 */
	HB_P_PUSHSYMNEAR, 30,	/* OSD10 */
	HB_P_DOSHORT, 10,
/* 00034 */ HB_P_LINEOFFSET, 1,	/* 40 */
	HB_P_PUSHSYMNEAR, 31,	/* __MVPRIVATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 32,	/* OSD11 */
	HB_P_PUSHSYMNEAR, 33,	/* OSD12 */
	HB_P_PUSHSYMNEAR, 34,	/* OSD13 */
	HB_P_PUSHSYMNEAR, 35,	/* OSD14 */
	HB_P_PUSHSYMNEAR, 36,	/* OSD15 */
	HB_P_PUSHSYMNEAR, 37,	/* OSD16 */
	HB_P_PUSHSYMNEAR, 38,	/* OSD17 */
	HB_P_PUSHSYMNEAR, 39,	/* OSD18 */
	HB_P_PUSHSYMNEAR, 40,	/* OSD19 */
	HB_P_PUSHSYMNEAR, 41,	/* OSD20 */
	HB_P_DOSHORT, 10,
/* 00061 */ HB_P_LINEOFFSET, 2,	/* 41 */
	HB_P_PUSHSYMNEAR, 31,	/* __MVPRIVATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 42,	/* OSD21 */
	HB_P_PUSHSYMNEAR, 43,	/* OSD22 */
	HB_P_PUSHSYMNEAR, 44,	/* OSD23 */
	HB_P_PUSHSYMNEAR, 45,	/* OSD24 */
	HB_P_PUSHSYMNEAR, 46,	/* OSD25 */
	HB_P_PUSHSYMNEAR, 47,	/* OSD26 */
	HB_P_PUSHSYMNEAR, 48,	/* OSD27 */
	HB_P_PUSHSYMNEAR, 49,	/* OSD28 */
	HB_P_PUSHSYMNEAR, 50,	/* OSD29 */
	HB_P_PUSHSYMNEAR, 51,	/* OSD30 */
	HB_P_DOSHORT, 10,
/* 00088 */ HB_P_LINEOFFSET, 3,	/* 42 */
	HB_P_PUSHSYMNEAR, 31,	/* __MVPRIVATE */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 52,	/* OSD31 */
	HB_P_DOSHORT, 1,
/* 00097 */ HB_P_LINEOFFSET, 4,	/* 43 */
	HB_P_PUSHLOCALNEAR, 3,	/* _LTRANSP */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00108) */
	HB_P_FALSE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00110) */
	HB_P_PUSHLOCALNEAR, 3,	/* _LTRANSP */
	HB_P_POPLOCALNEAR, 3,	/* _LTRANSP */
	HB_P_PUSHLOCALNEAR, 3,	/* _LTRANSP */
	HB_P_POPSTATIC, 1, 0,	/* LTRANSP */
/* 00117 */ HB_P_LINEOFFSET, 7,	/* 46 */
	HB_P_PUSHLOCALNEAR, 2,	/* DD */
	HB_P_PUSHSYMNEAR, 5,	/* CTOD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 13,	/* 13 (abs: 00143) */
/* 00132 */ HB_P_LINEOFFSET, 8,	/* 47 */
	HB_P_PUSHSYMNEAR, 3,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_POPLOCALNEAR, 2,	/* DD */
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00143) */
/* 00143 */ HB_P_LINEOFFSET, 11,	/* 50 */
	HB_P_PUSHSYMNEAR, 1,	/* SET */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_PUSHSYMNEAR, 2,	/* __SETCENTURY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPFALSENEAR, 17,	/* 17 (abs: 00172) */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'd', 'd', '/', 'm', 'm', '/', 'y', 'y', 'y', 'y', 0, 
	HB_P_JUMPNEAR, 13,	/* 13 (abs: 00183) */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'd', 'd', '/', 'm', 'm', '/', 'y', 'y', 0, 
	HB_P_DOSHORT, 2,
/* 00185 */ HB_P_LINEOFFSET, 12,	/* 51 */
	HB_P_PUSHSYMNEAR, 5,	/* CTOD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'0', '1', '/', 0, 
	HB_P_PUSHSYMNEAR, 53,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 54,	/* MONTH */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* DD */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'/', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 53,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 55,	/* YEAR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* DD */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPSTATIC, 18, 0,	/* DDATA */
/* 00236 */ HB_P_LINEOFFSET, 13,	/* 52 */
	HB_P_FALSE,
	HB_P_POPSTATIC, 4, 0,	/* LCONF */
/* 00242 */ HB_P_LINEOFFSET, 14,	/* 53 */
	HB_P_PUSHLOCALNEAR, 2,	/* DD */
	HB_P_POPSTATIC, 5, 0,	/* DATECONF */
/* 00249 */ HB_P_LINEOFFSET, 16,	/* 55 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 56,	/* TFONT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'C', 'o', 'u', 'r', 'i', 'e', 'r', ' ', 'N', 'e', 'w', 0, 
	HB_P_ZERO,
	HB_P_PUSHBYTE, 243,	/* -13 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 17,
	HB_P_POPVARIABLE, 57, 0,	/* OFONT1 */
/* 00295 */ HB_P_LINEOFFSET, 17,	/* 56 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 56,	/* TFONT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'C', 'o', 'u', 'r', 'i', 'e', 'r', ' ', 'N', 'e', 'w', 0, 
	HB_P_ZERO,
	HB_P_PUSHBYTE, 241,	/* -15 */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 17,
	HB_P_POPVARIABLE, 58, 0,	/* OFONT2 */
/* 00341 */ HB_P_LINEOFFSET, 18,	/* 57 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 56,	/* TFONT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'C', 'o', 'u', 'r', 'i', 'e', 'r', ' ', 'N', 'e', 'w', 0, 
	HB_P_ZERO,
	HB_P_PUSHBYTE, 243,	/* -13 */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 17,
	HB_P_POPVARIABLE, 59, 0,	/* OFONT3 */
/* 00387 */ HB_P_LINEOFFSET, 22,	/* 61 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 8,	/* TDIALOG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 198, 0,	/* 198 */
	HB_P_PUSHINT, 67, 1,	/* 323 */
	HB_P_PUSHINT, 204, 1,	/* 460 */
	HB_P_PUSHINT, 92, 2,	/* 604 */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHSYMNEAR, 60,	/* NOR */
	HB_P_PUSHNIL,
	HB_P_PUSHLONG, 0, 0, 0, 16,	/* 268435456 */
	HB_P_ZERO,
	HB_P_PUSHLONG, 0, 0, 128, 0,	/* 8388608 */
	HB_P_PUSHDOUBLE, 0, 0, 0, 0, 0, 0, 224, 65, 11, 0,	/* 2147483648.00000000000, 11, 0 */
	HB_P_FUNCTIONSHORT, 4,
	HB_P_ZERO,
	HB_P_PUSHLONG, 255, 255, 255, 0,	/* 16777215 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 19,
	HB_P_POPSTATIC, 6, 0,	/* ODLGDT */
/* 00461 */ HB_P_LINEOFFSET, 24,	/* 63 */
	HB_P_MESSAGE, 61, 0,	/* _BLCLICKED */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_PUSHBLOCKSHORT, 11,	/* 11 */
	HB_P_MESSAGE, 62, 0,	/* END */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00483 */ HB_P_LINEOFFSET, 25,	/* 64 */
	HB_P_MESSAGE, 63, 0,	/* _BKEYDOWN */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_PUSHBLOCK, 15, 0,	/* 15 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 64,	/* _VERKEY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00509 */ HB_P_LINEOFFSET, 27,	/* 66 */
	HB_P_MESSAGE, 16, 0,	/* ACTIVATE */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_MESSAGE, 17, 0,	/* BLCLICKED */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 18, 0,	/* BMOVED */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 65, 0,	/* _BPAINTED */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_PUSHBLOCK, 13, 0,	/* 13 */
	2, 0,	/* number of local parameters (2) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 66,	/* MYPAINT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_SENDSHORT, 1,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 17, 0,	/* 17 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	1, 0,	/* OGET */
	HB_P_PUSHSYMNEAR, 67,	/* INI_ODLGDT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_MESSAGE, 20, 0,	/* BRCLICKED */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 9,
	HB_P_POP,
/* 00586 */ HB_P_LINEOFFSET, 29,	/* 68 */
	HB_P_PUSHSTATIC, 4, 0,	/* LCONF */
	HB_P_JUMPFALSENEAR, 33,	/* 33 (abs: 00624) */
/* 00593 */ HB_P_LINEOFFSET, 30,	/* 69 */
	HB_P_PUSHSTATIC, 5, 0,	/* DATECONF */
	HB_P_POPLOCALNEAR, 2,	/* DD */
/* 00600 */ HB_P_LINEOFFSET, 31,	/* 70 */
	HB_P_MESSAGE, 68, 0,	/* SETTEXT */
	HB_P_PUSHLOCALNEAR, 1,	/* OGET */
	HB_P_PUSHLOCALNEAR, 2,	/* DD */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00612 */ HB_P_LINEOFFSET, 32,	/* 71 */
	HB_P_MESSAGE, 69, 0,	/* SETFOCUS */
	HB_P_PUSHLOCALNEAR, 1,	/* OGET */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00624) */
/* 00624 */ HB_P_LINEOFFSET, 35,	/* 74 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00629 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( INI_ODLGDT )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 8, 1,	/* locals, params */
	HB_P_SFRAME, 122, 0,	/* symbol (_INITSTATICS) */
/* 00006 */ HB_P_BASELINE, 78, 0,	/* 78 */
	HB_P_LOCALNEARSETINT, 4, 90, 0,	/* NLIN 90*/
	HB_P_LOCALNEARSETINT, 5, 10, 0,	/* NCOL 10*/
	HB_P_LOCALNEARSETINT, 6, 1, 0,	/* X 1*/
/* 00021 */ HB_P_LINEOFFSET, 1,	/* 79 */
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_ARRAYGEN, 2, 0,	/* 2 */
	HB_P_POPLOCALNEAR, 7,	/* APOS */
/* 00030 */ HB_P_LINEOFFSET, 2,	/* 80 */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'H', 'o', 'j', 'e', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 70,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 71,	/* DTOC */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 3,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 8,	/* CHOJE */
/* 00059 */ HB_P_LINEOFFSET, 6,	/* 84 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 72,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 8,	/* 8 */
	HB_P_PUSHBYTE, 45,	/* 45 */
	HB_P_PUSHBLOCKSHORT, 6,	/* 6 */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_ENDBLOCK,
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 58, 0,	/* OFONT2 */
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_PUSHLONG, 255, 255, 255, 0,	/* 16777215 */
	HB_P_PUSHLONG, 0, 0, 255, 0,	/* 16711680 */
	HB_P_PUSHINT, 195, 0,	/* 195 */
	HB_P_PUSHBYTE, 16,	/* 16 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 19,
	HB_P_POPSTATIC, 7, 0,	/* OSAY2 */
/* 00115 */ HB_P_LINEOFFSET, 10,	/* 88 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 73,	/* TBTNBMP */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 26,	/* 26 */
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 20, 0,	/* 20 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 74,	/* MESANO */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 75,	/* AJUSTA */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'<', '<', 0, 
	HB_P_PUSHVARIABLE, 57, 0,	/* OFONT1 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 20,
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 76, 0,	/* PIXEL */
	HB_P_POPSTATIC, 8, 0,	/* OBUT1 */
/* 00185 */ HB_P_LINEOFFSET, 14,	/* 92 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 73,	/* TBTNBMP */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_PUSHINT, 249, 0,	/* 249 */
	HB_P_PUSHBYTE, 26,	/* 26 */
	HB_P_PUSHBYTE, 24,	/* 24 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 19, 0,	/* 19 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 74,	/* MESANO */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
	HB_P_PUSHSYMNEAR, 75,	/* AJUSTA */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_PUSHSTRSHORT, 3,	/* 3 */
	'>', '>', 0, 
	HB_P_PUSHVARIABLE, 57, 0,	/* OFONT1 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 20,
	HB_P_DUPLICATE,
	HB_P_POPVARIABLE, 76, 0,	/* PIXEL */
	HB_P_POPSTATIC, 9, 0,	/* OBUT2 */
/* 00255 */ HB_P_LINEOFFSET, 16,	/* 94 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 72,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 54,	/* 54 */
	HB_P_PUSHBYTE, 8,	/* 8 */
	HB_P_PUSHBLOCKSHORT, 6,	/* 6 */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_PUSHLONG, 255, 255, 0, 0,	/* 65535 */
	HB_P_PUSHLONG, 255, 255, 0, 0,	/* 65535 */
	HB_P_PUSHINT, 14, 1,	/* 270 */
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 19,
	HB_P_POP,
/* 00305 */ HB_P_LINEOFFSET, 19,	/* 97 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 72,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 56,	/* 56 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBLOCKSHORT, 9,	/* 9 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'D', 'o', 'm', 0, 
	HB_P_ENDBLOCK,
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 59, 0,	/* OFONT3 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_ZERO,
	HB_P_PUSHLONG, 255, 255, 0, 0,	/* 65535 */
	HB_P_PUSHBYTE, 33,	/* 33 */
	HB_P_PUSHBYTE, 17,	/* 17 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 19,
	HB_P_POPSTATIC, 11, 0,	/* OSAY3 */
/* 00359 */ HB_P_LINEOFFSET, 23,	/* 101 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 72,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 56,	/* 56 */
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_PUSHBLOCKSHORT, 9,	/* 9 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'S', 'e', 'g', 0, 
	HB_P_ENDBLOCK,
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 59, 0,	/* OFONT3 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_ZERO,
	HB_P_PUSHLONG, 255, 255, 0, 0,	/* 65535 */
	HB_P_PUSHBYTE, 31,	/* 31 */
	HB_P_PUSHBYTE, 17,	/* 17 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 19,
	HB_P_POPSTATIC, 12, 0,	/* OSAY4 */
/* 00413 */ HB_P_LINEOFFSET, 27,	/* 105 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 72,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 56,	/* 56 */
	HB_P_PUSHBYTE, 90,	/* 90 */
	HB_P_PUSHBLOCKSHORT, 9,	/* 9 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'T', 'e', 'r', 0, 
	HB_P_ENDBLOCK,
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 59, 0,	/* OFONT3 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_ZERO,
	HB_P_PUSHLONG, 255, 255, 0, 0,	/* 65535 */
	HB_P_PUSHBYTE, 29,	/* 29 */
	HB_P_PUSHBYTE, 17,	/* 17 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 19,
	HB_P_POPSTATIC, 13, 0,	/* OSAY5 */
/* 00467 */ HB_P_LINEOFFSET, 31,	/* 109 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 72,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 56,	/* 56 */
	HB_P_PUSHINT, 130, 0,	/* 130 */
	HB_P_PUSHBLOCKSHORT, 9,	/* 9 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'Q', 'u', 'a', 0, 
	HB_P_ENDBLOCK,
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 59, 0,	/* OFONT3 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_ZERO,
	HB_P_PUSHLONG, 255, 255, 0, 0,	/* 65535 */
	HB_P_PUSHBYTE, 33,	/* 33 */
	HB_P_PUSHBYTE, 17,	/* 17 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 19,
	HB_P_POPSTATIC, 14, 0,	/* OSAY6 */
/* 00522 */ HB_P_LINEOFFSET, 35,	/* 113 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 72,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 56,	/* 56 */
	HB_P_PUSHINT, 170, 0,	/* 170 */
	HB_P_PUSHBLOCKSHORT, 9,	/* 9 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'Q', 'u', 'i', 0, 
	HB_P_ENDBLOCK,
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 59, 0,	/* OFONT3 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_ZERO,
	HB_P_PUSHLONG, 255, 255, 0, 0,	/* 65535 */
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_PUSHBYTE, 17,	/* 17 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 19,
	HB_P_POPSTATIC, 15, 0,	/* OSAY7 */
/* 00577 */ HB_P_LINEOFFSET, 39,	/* 117 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 72,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 56,	/* 56 */
	HB_P_PUSHINT, 210, 0,	/* 210 */
	HB_P_PUSHBLOCKSHORT, 9,	/* 9 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'S', 'e', 'x', 0, 
	HB_P_ENDBLOCK,
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 59, 0,	/* OFONT3 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_ZERO,
	HB_P_PUSHLONG, 255, 255, 0, 0,	/* 65535 */
	HB_P_PUSHBYTE, 31,	/* 31 */
	HB_P_PUSHBYTE, 17,	/* 17 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 19,
	HB_P_POPSTATIC, 16, 0,	/* OSAY8 */
/* 00632 */ HB_P_LINEOFFSET, 43,	/* 121 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 72,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 56,	/* 56 */
	HB_P_PUSHINT, 250, 0,	/* 250 */
	HB_P_PUSHBLOCKSHORT, 9,	/* 9 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'S', 'a', 'b', 0, 
	HB_P_ENDBLOCK,
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 59, 0,	/* OFONT3 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_ZERO,
	HB_P_PUSHLONG, 255, 255, 0, 0,	/* 65535 */
	HB_P_PUSHBYTE, 28,	/* 28 */
	HB_P_PUSHBYTE, 17,	/* 17 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 19,
	HB_P_POPSTATIC, 17, 0,	/* OSAY9 */
/* 00687 */ HB_P_LINEOFFSET, 46,	/* 124 */
	HB_P_LOCALNEARSETINT, 2, 1, 0,	/* I 1*/
	HB_P_PUSHLOCALNEAR, 2,	/* I */
	HB_P_PUSHBYTE, 31,	/* 31 */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSE, 188, 0,	/* 188 (abs: 00886) */
/* 00701 */ HB_P_LINEOFFSET, 47,	/* 125 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'o', 'S', 'D', 0, 
	HB_P_PUSHSYMNEAR, 70,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 77,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* I */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 3,	/* COBJ */
/* 00724 */ HB_P_LINEOFFSET, 48,	/* 126 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 72,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHLOCALNEAR, 4,	/* NLIN */
	HB_P_PUSHLOCALNEAR, 5,	/* NCOL */
	HB_P_PUSHBLOCK, 19, 0,	/* 19 */
	0, 0,	/* number of local parameters (0) */
	1, 0,	/* number of local variables (1) */
	2, 0,	/* I */
	HB_P_PUSHSYMNEAR, 53,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHBYTE, 16,	/* 16 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 19,
	HB_P_PUSHLOCALNEAR, 3,	/* COBJ */
	HB_P_MACROPOP, 11,
/* 00781 */ HB_P_LINEOFFSET, 49,	/* 127 */
	HB_P_MESSAGE, 78, 0,	/* _LWANTCLICK */
	HB_P_PUSHLOCALNEAR, 3,	/* COBJ */
	HB_P_MACROPUSH, 11,
	HB_P_TRUE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00794 */ HB_P_LINEOFFSET, 50,	/* 128 */
	HB_P_MESSAGE, 79, 0,	/* _BLBUTTONUP */
	HB_P_PUSHLOCALNEAR, 3,	/* COBJ */
	HB_P_MACROPUSH, 11,
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'{', '|', '|', ' ', '_', 'C', 'o', 'n', 'f', 'D', 'a', 't', 'a', '(', 0, 
	HB_P_PUSHLOCALNEAR, 3,	/* COBJ */
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	')', ' ', '}', 0, 
	HB_P_PLUS,
	HB_P_MACROPUSH, 11,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00835 */ HB_P_LINEOFFSET, 52,	/* 130 */
	HB_P_LOCALNEARADDINT, 5, 50, 0,	/* NCOL 50*/
/* 00841 */ HB_P_LINEOFFSET, 53,	/* 131 */
	HB_P_PUSHLOCALNEAR, 6,	/* X */
	HB_P_INC,
	HB_P_POPLOCALNEAR, 6,	/* X */
/* 00848 */ HB_P_LINEOFFSET, 54,	/* 132 */
	HB_P_PUSHLOCALNEAR, 6,	/* X */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_GREATEREQUAL,
	HB_P_JUMPFALSENEAR, 22,	/* 22 (abs: 00877) */
/* 00857 */ HB_P_LINEOFFSET, 55,	/* 133 */
	HB_P_LOCALNEARSETINT, 5, 10, 0,	/* NCOL 10*/
/* 00863 */ HB_P_LINEOFFSET, 56,	/* 134 */
	HB_P_LOCALNEARADDINT, 4, 25, 0,	/* NLIN 25*/
/* 00869 */ HB_P_LINEOFFSET, 57,	/* 135 */
	HB_P_LOCALNEARSETINT, 6, 1, 0,	/* X 1*/
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00877) */
/* 00877 */ HB_P_LINEOFFSET, 59,	/* 137 */
	HB_P_LOCALNEARADDINT, 2, 1, 0,	/* I 1*/
	HB_P_JUMP, 66, 255,	/* -190 (abs: 00693) */
/* 00886 */ HB_P_LINEOFFSET, 62,	/* 140 */
	HB_P_MESSAGE, 7, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 72,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 236, 0,	/* 236 */
	HB_P_PUSHBYTE, 70,	/* 70 */
	HB_P_PUSHBLOCK, 12, 0,	/* 12 */
	0, 0,	/* number of local parameters (0) */
	1, 0,	/* number of local variables (1) */
	8, 0,	/* CHOJE */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 59, 0,	/* OFONT3 */
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_PUSHLONG, 255, 255, 255, 0,	/* 16777215 */
	HB_P_PUSHLONG, 0, 128, 0, 0,	/* 32768 */
	HB_P_PUSHINT, 149, 0,	/* 149 */
	HB_P_PUSHBYTE, 17,	/* 17 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 19,
	HB_P_POPSTATIC, 10, 0,	/* OSAYHOJE */
/* 00949 */ HB_P_LINEOFFSET, 63,	/* 141 */
	HB_P_MESSAGE, 78, 0,	/* _LWANTCLICK */
	HB_P_PUSHSTATIC, 10, 0,	/* OSAYHOJE */
	HB_P_TRUE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00961 */ HB_P_LINEOFFSET, 64,	/* 142 */
	HB_P_MESSAGE, 79, 0,	/* _BLBUTTONUP */
	HB_P_PUSHSTATIC, 10, 0,	/* OSAYHOJE */
	HB_P_PUSHBLOCKSHORT, 23,	/* 23 */
	HB_P_TRUE,
	HB_P_POPSTATIC, 4, 0,	/* LCONF */
	HB_P_PUSHSYMNEAR, 3,	/* DATE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_POPSTATIC, 5, 0,	/* DATECONF */
	HB_P_MESSAGE, 62, 0,	/* END */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00995 */ HB_P_LINEOFFSET, 65,	/* 143 */
	HB_P_PUSHSYMNEAR, 75,	/* AJUSTA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 01002 */ HB_P_LINEOFFSET, 67,	/* 145 */
	HB_P_PUSHSYMNEAR, 80,	/* CLIENTTOSCREEN */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 81, 0,	/* HWND */
	HB_P_PUSHLOCALNEAR, 1,	/* OGET */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 7,	/* APOS */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 7,	/* APOS */
/* 01020 */ HB_P_LINEOFFSET, 68,	/* 146 */
	HB_P_PUSHSYMNEAR, 82,	/* GETCOORS */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 83,	/* GETDESKTOPWINDOW */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 9,	/* ARES */
/* 01034 */ HB_P_LINEOFFSET, 70,	/* 148 */
	HB_P_PUSHLOCALNEAR, 7,	/* APOS */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_ADDINT, 54, 1,	/* 310*/
	HB_P_PUSHLOCALNEAR, 9,	/* ARES */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPUSH,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 19,	/* 19 (abs: 01068) */
/* 01051 */ HB_P_LINEOFFSET, 71,	/* 149 */
	HB_P_PUSHLOCALNEAR, 9,	/* ARES */
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ARRAYPUSH,
	HB_P_ADDINT, 202, 254,	/* -310*/
	HB_P_PUSHLOCALREF, 7, 0,	/* APOS */
	HB_P_ONE,
	HB_P_ARRAYPOP,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 01068) */
/* 01068 */ HB_P_LINEOFFSET, 73,	/* 151 */
	HB_P_PUSHLOCALNEAR, 7,	/* APOS */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_ADDINT, 33, 1,	/* 289*/
	HB_P_PUSHLOCALNEAR, 9,	/* ARES */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ARRAYPUSH,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 20,	/* 20 (abs: 01104) */
/* 01086 */ HB_P_LINEOFFSET, 74,	/* 152 */
	HB_P_PUSHLOCALNEAR, 9,	/* ARES */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_ARRAYPUSH,
	HB_P_ADDINT, 223, 254,	/* -289*/
	HB_P_PUSHLOCALREF, 7, 0,	/* APOS */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPOP,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 01104) */
/* 01104 */ HB_P_LINEOFFSET, 77,	/* 155 */
	HB_P_MESSAGE, 84, 0,	/* MOVE */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_PUSHLOCALNEAR, 7,	/* APOS */
	HB_P_ONE,
	HB_P_ARRAYPUSH,
	HB_P_MESSAGE, 85, 0,	/* NHEIGHT */
	HB_P_PUSHLOCALNEAR, 1,	/* OGET */
	HB_P_SENDSHORT, 0,
	HB_P_PLUS,
	HB_P_ADDINT, 2, 0,	/* 2*/
	HB_P_PUSHLOCALNEAR, 7,	/* APOS */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_ARRAYPUSH,
	HB_P_PUSHINT, 33, 1,	/* 289 */
	HB_P_PUSHINT, 4, 1,	/* 260 */
	HB_P_TRUE,
	HB_P_SENDSHORT, 5,
	HB_P_POP,
/* 01142 */ HB_P_LINEOFFSET, 79,	/* 157 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 01147 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( AJUSTA )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 5, 0,	/* locals, params */
	HB_P_SFRAME, 122, 0,	/* symbol (_INITSTATICS) */
/* 00006 */ HB_P_BASELINE, 161, 0,	/* 161 */
	HB_P_LOCALNEARSETINT, 3, 90, 0,	/* NLIN 90*/
	HB_P_PUSHSYMNEAR, 86,	/* DOW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 18, 0,	/* DDATA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 5,	/* X */
/* 00023 */ HB_P_LINEOFFSET, 2,	/* 163 */
	HB_P_PUSHSYMNEAR, 86,	/* DOW */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 18, 0,	/* DDATA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_MULT,
	HB_P_ADDINT, 10, 0,	/* 10*/
	HB_P_POPLOCALNEAR, 4,	/* NCOL */
/* 00044 */ HB_P_LINEOFFSET, 4,	/* 165 */
	HB_P_LOCALNEARSETINT, 1, 1, 0,	/* I 1*/
	HB_P_PUSHLOCALNEAR, 1,	/* I */
	HB_P_PUSHBYTE, 31,	/* 31 */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSE, 22, 1,	/* 278 (abs: 00333) */
/* 00058 */ HB_P_LINEOFFSET, 5,	/* 166 */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'o', 'S', 'D', 0, 
	HB_P_PUSHSYMNEAR, 70,	/* ALLTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 77,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* I */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* COBJ */
/* 00081 */ HB_P_LINEOFFSET, 7,	/* 168 */
	HB_P_PUSHSYMNEAR, 87,	/* VALDIA */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* I */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSE, 180, 0,	/* 180 (abs: 00270) */
/* 00093 */ HB_P_LINEOFFSET, 8,	/* 169 */
	HB_P_PUSHLOCALNEAR, 5,	/* X */
	HB_P_ONE,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 24,	/* 24 (abs: 00123) */
/* 00101 */ HB_P_LINEOFFSET, 9,	/* 170 */
	HB_P_MESSAGE, 88, 0,	/* SETCOLOR */
	HB_P_PUSHLOCALNEAR, 2,	/* COBJ */
	HB_P_MACROPUSH, 11,
	HB_P_PUSHINT, 255, 0,	/* 255 */
	HB_P_PUSHLONG, 255, 255, 255, 0,	/* 16777215 */
	HB_P_SENDSHORT, 2,
	HB_P_POP,
	HB_P_JUMPNEAR, 20,	/* 20 (abs: 00141) */
/* 00123 */ HB_P_LINEOFFSET, 11,	/* 172 */
	HB_P_MESSAGE, 88, 0,	/* SETCOLOR */
	HB_P_PUSHLOCALNEAR, 2,	/* COBJ */
	HB_P_MACROPUSH, 11,
	HB_P_ZERO,
	HB_P_PUSHLONG, 255, 255, 255, 0,	/* 16777215 */
	HB_P_SENDSHORT, 2,
	HB_P_POP,
/* 00141 */ HB_P_LINEOFFSET, 13,	/* 174 */
	HB_P_PUSHLOCALNEAR, 1,	/* I */
	HB_P_PUSHSYMNEAR, 89,	/* DAY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 5, 0,	/* DATECONF */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 38,	/* 38 (abs: 00192) */
/* 00156 */ HB_P_LINEOFFSET, 14,	/* 175 */
	HB_P_MESSAGE, 90, 0,	/* SETFONT */
	HB_P_PUSHLOCALNEAR, 2,	/* COBJ */
	HB_P_MACROPUSH, 11,
	HB_P_PUSHVARIABLE, 58, 0,	/* OFONT2 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00171 */ HB_P_LINEOFFSET, 15,	/* 176 */
	HB_P_PUSHLOCALNEAR, 4,	/* NCOL */
	HB_P_POPSTATIC, 2, 0,	/* NX */
	HB_P_PUSHLOCALNEAR, 3,	/* NLIN */
	HB_P_POPSTATIC, 3, 0,	/* NY */
/* 00183 */ HB_P_LINEOFFSET, 16,	/* 177 */
	HB_P_PUSHSYMNEAR, 66,	/* MYPAINT */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
	HB_P_JUMPNEAR, 17,	/* 17 (abs: 00207) */
/* 00192 */ HB_P_LINEOFFSET, 18,	/* 179 */
	HB_P_MESSAGE, 90, 0,	/* SETFONT */
	HB_P_PUSHLOCALNEAR, 2,	/* COBJ */
	HB_P_MACROPUSH, 11,
	HB_P_PUSHVARIABLE, 57, 0,	/* OFONT1 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00207 */ HB_P_LINEOFFSET, 20,	/* 181 */
	HB_P_MESSAGE, 91, 0,	/* _NTOP */
	HB_P_PUSHLOCALNEAR, 2,	/* COBJ */
	HB_P_MACROPUSH, 11,
	HB_P_PUSHLOCALNEAR, 3,	/* NLIN */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00221 */ HB_P_LINEOFFSET, 21,	/* 182 */
	HB_P_MESSAGE, 92, 0,	/* _NLEFT */
	HB_P_PUSHLOCALNEAR, 2,	/* COBJ */
	HB_P_MACROPUSH, 11,
	HB_P_PUSHLOCALNEAR, 4,	/* NCOL */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00235 */ HB_P_LINEOFFSET, 22,	/* 183 */
	HB_P_MESSAGE, 93, 0,	/* SHOW */
	HB_P_PUSHLOCALNEAR, 2,	/* COBJ */
	HB_P_MACROPUSH, 11,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00247 */ HB_P_LINEOFFSET, 23,	/* 184 */
	HB_P_MESSAGE, 68, 0,	/* SETTEXT */
	HB_P_PUSHLOCALNEAR, 2,	/* COBJ */
	HB_P_MACROPUSH, 11,
	HB_P_PUSHSYMNEAR, 53,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* I */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 14,	/* 14 (abs: 00282) */
/* 00270 */ HB_P_LINEOFFSET, 25,	/* 186 */
	HB_P_MESSAGE, 94, 0,	/* HIDE */
	HB_P_PUSHLOCALNEAR, 2,	/* COBJ */
	HB_P_MACROPUSH, 11,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00282 */ HB_P_LINEOFFSET, 27,	/* 188 */
	HB_P_LOCALNEARADDINT, 4, 40, 0,	/* NCOL 40*/
/* 00288 */ HB_P_LINEOFFSET, 28,	/* 189 */
	HB_P_PUSHLOCALNEAR, 5,	/* X */
	HB_P_INC,
	HB_P_POPLOCALNEAR, 5,	/* X */
/* 00295 */ HB_P_LINEOFFSET, 29,	/* 190 */
	HB_P_PUSHLOCALNEAR, 5,	/* X */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 22,	/* 22 (abs: 00324) */
/* 00304 */ HB_P_LINEOFFSET, 30,	/* 191 */
	HB_P_LOCALNEARSETINT, 4, 10, 0,	/* NCOL 10*/
/* 00310 */ HB_P_LINEOFFSET, 31,	/* 192 */
	HB_P_LOCALNEARADDINT, 3, 25, 0,	/* NLIN 25*/
/* 00316 */ HB_P_LINEOFFSET, 32,	/* 193 */
	HB_P_LOCALNEARSETINT, 5, 1, 0,	/* X 1*/
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00324) */
/* 00324 */ HB_P_LINEOFFSET, 34,	/* 195 */
	HB_P_LOCALNEARADDINT, 1, 1, 0,	/* I 1*/
	HB_P_JUMP, 232, 254,	/* -280 (abs: 00050) */
/* 00333 */ HB_P_LINEOFFSET, 36,	/* 197 */
	HB_P_MESSAGE, 68, 0,	/* SETTEXT */
	HB_P_PUSHSTATIC, 7, 0,	/* OSAY2 */
	HB_P_PUSHSTATIC, 19, 0,	/* AMESES */
	HB_P_PUSHSYMNEAR, 54,	/* MONTH */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 18, 0,	/* DDATA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ARRAYPUSH,
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	' ', 'd', 'e', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 53,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 55,	/* YEAR */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 18, 0,	/* DDATA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00380 */ HB_P_LINEOFFSET, 38,	/* 199 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00385 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( VALDIA )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 0, 1,	/* locals, params */
	HB_P_SFRAME, 122, 0,	/* symbol (_INITSTATICS) */
/* 00006 */ HB_P_BASELINE, 206, 0,	/* 206 */
	HB_P_PUSHSYMNEAR, 54,	/* MONTH */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 18, 0,	/* DDATA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 56,	/* 56 (abs: 00076) */
/* 00022 */ HB_P_LINEOFFSET, 1,	/* 207 */
	HB_P_PUSHLOCALNEAR, 1,	/* I */
	HB_P_PUSHBYTE, 28,	/* 28 */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 9,	/* 9 (abs: 00038) */
/* 00031 */ HB_P_LINEOFFSET, 2,	/* 208 */
	HB_P_TRUE,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00038) */
/* 00038 */ HB_P_LINEOFFSET, 4,	/* 210 */
	HB_P_PUSHLOCALNEAR, 1,	/* I */
	HB_P_PUSHBYTE, 29,	/* 29 */
	HB_P_EQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPFALSENEAR, 16,	/* 16 (abs: 00062) */
	HB_P_PUSHSYMNEAR, 55,	/* YEAR */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 18, 0,	/* DDATA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_MODULUS,
	HB_P_ZERO,
	HB_P_EQUAL,
	HB_P_AND,
	HB_P_JUMPFALSENEAR, 9,	/* 9 (abs: 00071) */
/* 00064 */ HB_P_LINEOFFSET, 5,	/* 211 */
	HB_P_TRUE,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 5,	/* 5 (abs: 00074) */
	HB_P_FALSE,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 88,	/* 88 (abs: 00162) */
/* 00076 */ HB_P_LINEOFFSET, 13,	/* 219 */
	HB_P_PUSHSYMNEAR, 54,	/* MONTH */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 18, 0,	/* DDATA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_EQUAL,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 14,	/* 14 (abs: 00104) */
	HB_P_PUSHSYMNEAR, 54,	/* MONTH */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 18, 0,	/* DDATA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 14,	/* 14 (abs: 00119) */
	HB_P_PUSHSYMNEAR, 54,	/* MONTH */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 18, 0,	/* DDATA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 9,	/* 9 */
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_DUPLICATE,
	HB_P_JUMPTRUENEAR, 14,	/* 14 (abs: 00134) */
	HB_P_PUSHSYMNEAR, 54,	/* MONTH */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 18, 0,	/* DDATA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_EQUAL,
	HB_P_OR,
	HB_P_JUMPFALSENEAR, 23,	/* 23 (abs: 00157) */
/* 00136 */ HB_P_LINEOFFSET, 15,	/* 221 */
	HB_P_PUSHLOCALNEAR, 1,	/* I */
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 9,	/* 9 (abs: 00152) */
/* 00145 */ HB_P_LINEOFFSET, 16,	/* 222 */
	HB_P_TRUE,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 5,	/* 5 (abs: 00155) */
	HB_P_FALSE,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 00162) */
/* 00157 */ HB_P_LINEOFFSET, 22,	/* 228 */
	HB_P_TRUE,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
/* 00162 */ HB_P_LINEOFFSET, 25,	/* 231 */
	HB_P_TRUE,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00167 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( MESANO )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 2, 1,	/* locals, params */
	HB_P_SFRAME, 122, 0,	/* symbol (_INITSTATICS) */
/* 00006 */ HB_P_BASELINE, 235, 0,	/* 235 */
	HB_P_PUSHSYMNEAR, 54,	/* MONTH */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 18, 0,	/* DDATA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 2,	/* NMES */
/* 00019 */ HB_P_LINEOFFSET, 1,	/* 236 */
	HB_P_PUSHSYMNEAR, 55,	/* YEAR */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 18, 0,	/* DDATA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 3,	/* NANO */
/* 00031 */ HB_P_LINEOFFSET, 3,	/* 238 */
	HB_P_PUSHLOCALNEAR, 1,	/* N */
	HB_P_ONE,
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 37,	/* 37 (abs: 00074) */
/* 00039 */ HB_P_LINEOFFSET, 4,	/* 239 */
	HB_P_PUSHLOCALNEAR, 2,	/* NMES */
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_LESS,
	HB_P_JUMPFALSENEAR, 13,	/* 13 (abs: 00059) */
/* 00048 */ HB_P_LINEOFFSET, 5,	/* 240 */
	HB_P_PUSHLOCALNEAR, 2,	/* NMES */
	HB_P_PUSHLOCALNEAR, 1,	/* N */
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 2,	/* NMES */
	HB_P_JUMPNEAR, 15,	/* 15 (abs: 00072) */
/* 00059 */ HB_P_LINEOFFSET, 7,	/* 242 */
	HB_P_LOCALNEARSETINT, 2, 1, 0,	/* NMES 1*/
/* 00065 */ HB_P_LINEOFFSET, 8,	/* 243 */
	HB_P_PUSHLOCALNEAR, 3,	/* NANO */
	HB_P_INC,
	HB_P_POPLOCALNEAR, 3,	/* NANO */
	HB_P_JUMPNEAR, 32,	/* 32 (abs: 00104) */
/* 00074 */ HB_P_LINEOFFSET, 11,	/* 246 */
	HB_P_PUSHLOCALNEAR, 2,	/* NMES */
	HB_P_ONE,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 00091) */
/* 00082 */ HB_P_LINEOFFSET, 12,	/* 247 */
	HB_P_PUSHLOCALNEAR, 2,	/* NMES */
	HB_P_DEC,
	HB_P_POPLOCALNEAR, 2,	/* NMES */
	HB_P_JUMPNEAR, 15,	/* 15 (abs: 00104) */
/* 00091 */ HB_P_LINEOFFSET, 14,	/* 249 */
	HB_P_LOCALNEARSETINT, 2, 12, 0,	/* NMES 12*/
/* 00097 */ HB_P_LINEOFFSET, 15,	/* 250 */
	HB_P_PUSHLOCALNEAR, 3,	/* NANO */
	HB_P_DEC,
	HB_P_POPLOCALNEAR, 3,	/* NANO */
/* 00104 */ HB_P_LINEOFFSET, 18,	/* 253 */
	HB_P_PUSHSYMNEAR, 5,	/* CTOD */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'0', '1', '/', 0, 
	HB_P_PUSHSYMNEAR, 53,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NMES */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'/', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 53,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* NANO */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPSTATIC, 18, 0,	/* DDATA */
/* 00145 */ HB_P_LINEOFFSET, 19,	/* 254 */
	HB_P_PUSHSYMNEAR, 75,	/* AJUSTA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00152 */ HB_P_LINEOFFSET, 21,	/* 256 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00157 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( _CONFDATA )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 0, 1,	/* locals, params */
	HB_P_SFRAME, 122, 0,	/* symbol (_INITSTATICS) */
/* 00006 */ HB_P_BASELINE, 6, 1,	/* 262 */
	HB_P_PUSHSYMNEAR, 5,	/* CTOD */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 96, 0,	/* CCAPTION */
	HB_P_PUSHLOCALNEAR, 1,	/* OOBJ */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'/', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 53,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 54,	/* MONTH */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 18, 0,	/* DDATA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'/', 0, 
	HB_P_PLUS,
	HB_P_PUSHSYMNEAR, 53,	/* STRZERO */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 55,	/* YEAR */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 18, 0,	/* DDATA */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPSTATIC, 5, 0,	/* DATECONF */
/* 00066 */ HB_P_LINEOFFSET, 1,	/* 263 */
	HB_P_TRUE,
	HB_P_POPSTATIC, 4, 0,	/* LCONF */
/* 00072 */ HB_P_LINEOFFSET, 2,	/* 264 */
	HB_P_MESSAGE, 62, 0,	/* END */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00083 */ HB_P_LINEOFFSET, 4,	/* 266 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00088 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( _VERKEY )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 0, 1,	/* locals, params */
	HB_P_SFRAME, 122, 0,	/* symbol (_INITSTATICS) */
/* 00006 */ HB_P_BASELINE, 15, 1,	/* 271 */
	HB_P_PUSHLOCALNEAR, 1,	/* NKEY */
	HB_P_PUSHBYTE, 39,	/* 39 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 17,	/* 17 (abs: 00031) */
/* 00016 */ HB_P_LINEOFFSET, 1,	/* 272 */
	HB_P_PUSHSYMNEAR, 74,	/* MESANO */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_DOSHORT, 1,
/* 00024 */ HB_P_LINEOFFSET, 2,	/* 273 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00031) */
/* 00031 */ HB_P_LINEOFFSET, 4,	/* 275 */
	HB_P_PUSHLOCALNEAR, 1,	/* NKEY */
	HB_P_PUSHBYTE, 37,	/* 37 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00056) */
/* 00040 */ HB_P_LINEOFFSET, 5,	/* 276 */
	HB_P_PUSHSYMNEAR, 74,	/* MESANO */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_DOSHORT, 1,
/* 00049 */ HB_P_LINEOFFSET, 6,	/* 277 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00056) */
/* 00056 */ HB_P_LINEOFFSET, 8,	/* 279 */
	HB_P_PUSHLOCALNEAR, 1,	/* NKEY */
	HB_P_PUSHBYTE, 40,	/* 40 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 28,	/* 28 (abs: 00091) */
/* 00065 */ HB_P_LINEOFFSET, 9,	/* 280 */
	HB_P_PUSHSTATIC, 18, 0,	/* DDATA */
	HB_P_PUSHINT, 109, 1,	/* 365 */
	HB_P_MINUS,
	HB_P_POPSTATIC, 18, 0,	/* DDATA */
/* 00077 */ HB_P_LINEOFFSET, 10,	/* 281 */
	HB_P_PUSHSYMNEAR, 75,	/* AJUSTA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00084 */ HB_P_LINEOFFSET, 11,	/* 282 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00091) */
/* 00091 */ HB_P_LINEOFFSET, 13,	/* 284 */
	HB_P_PUSHLOCALNEAR, 1,	/* NKEY */
	HB_P_PUSHBYTE, 38,	/* 38 */
	HB_P_EQUAL,
	HB_P_JUMPFALSENEAR, 28,	/* 28 (abs: 00126) */
/* 00100 */ HB_P_LINEOFFSET, 14,	/* 285 */
	HB_P_PUSHSTATIC, 18, 0,	/* DDATA */
	HB_P_PUSHINT, 109, 1,	/* 365 */
	HB_P_PLUS,
	HB_P_POPSTATIC, 18, 0,	/* DDATA */
/* 00112 */ HB_P_LINEOFFSET, 15,	/* 286 */
	HB_P_PUSHSYMNEAR, 75,	/* AJUSTA */
	HB_P_PUSHNIL,
	HB_P_DOSHORT, 0,
/* 00119 */ HB_P_LINEOFFSET, 16,	/* 287 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00126) */
/* 00126 */ HB_P_LINEOFFSET, 19,	/* 290 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00131 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( MYPAINT )
{
   static const BYTE pcode[] =
   {
	HB_P_SFRAME, 122, 0,	/* symbol (_INITSTATICS) */
/* 00003 */ HB_P_BASELINE, 43, 1,	/* 299 */
	HB_P_MESSAGE, 97, 0,	/* GETDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00015 */ HB_P_LINEOFFSET, 2,	/* 301 */
	HB_P_PUSHSYMNEAR, 98,	/* CREATEPEN */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHLONG, 255, 255, 255, 0,	/* 16777215 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPSTATIC, 22, 0,	/* HPEN */
/* 00033 */ HB_P_LINEOFFSET, 3,	/* 302 */
	HB_P_PUSHSYMNEAR, 99,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSTATIC, 22, 0,	/* HPEN */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPVARIABLE, 101, 0,	/* HOLDPEN */
/* 00054 */ HB_P_LINEOFFSET, 4,	/* 303 */
	HB_P_PUSHSYMNEAR, 102,	/* ARC */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSTATIC, 20, 0,	/* NXOLD */
	HB_P_ADDINT, 251, 255,	/* -5*/
	HB_P_PUSHSTATIC, 21, 0,	/* NYOLD */
	HB_P_ADDINT, 251, 255,	/* -5*/
	HB_P_PUSHSTATIC, 20, 0,	/* NXOLD */
	HB_P_ADDINT, 25, 0,	/* 25*/
	HB_P_PUSHSTATIC, 21, 0,	/* NYOLD */
	HB_P_ADDINT, 22, 0,	/* 22*/
	HB_P_DOSHORT, 5,
/* 00093 */ HB_P_LINEOFFSET, 5,	/* 304 */
	HB_P_PUSHSYMNEAR, 99,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHVARIABLE, 101, 0,	/* HOLDPEN */
	HB_P_DOSHORT, 2,
/* 00111 */ HB_P_LINEOFFSET, 6,	/* 305 */
	HB_P_PUSHSYMNEAR, 103,	/* DELETEOBJECT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 22, 0,	/* HPEN */
	HB_P_DOSHORT, 1,
/* 00121 */ HB_P_LINEOFFSET, 8,	/* 307 */
	HB_P_PUSHSYMNEAR, 98,	/* CREATEPEN */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHLONG, 0, 0, 255, 0,	/* 16711680 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPSTATIC, 22, 0,	/* HPEN */
/* 00139 */ HB_P_LINEOFFSET, 9,	/* 308 */
	HB_P_PUSHSYMNEAR, 99,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSTATIC, 22, 0,	/* HPEN */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPVARIABLE, 101, 0,	/* HOLDPEN */
/* 00160 */ HB_P_LINEOFFSET, 10,	/* 309 */
	HB_P_PUSHSYMNEAR, 102,	/* ARC */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSTATIC, 2, 0,	/* NX */
	HB_P_ADDINT, 251, 255,	/* -5*/
	HB_P_PUSHSTATIC, 3, 0,	/* NY */
	HB_P_ADDINT, 251, 255,	/* -5*/
	HB_P_PUSHSTATIC, 2, 0,	/* NX */
	HB_P_ADDINT, 25, 0,	/* 25*/
	HB_P_PUSHSTATIC, 3, 0,	/* NY */
	HB_P_ADDINT, 22, 0,	/* 22*/
	HB_P_DOSHORT, 5,
/* 00199 */ HB_P_LINEOFFSET, 11,	/* 310 */
	HB_P_PUSHSYMNEAR, 99,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHVARIABLE, 101, 0,	/* HOLDPEN */
	HB_P_DOSHORT, 2,
/* 00217 */ HB_P_LINEOFFSET, 12,	/* 311 */
	HB_P_PUSHSYMNEAR, 103,	/* DELETEOBJECT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 22, 0,	/* HPEN */
	HB_P_DOSHORT, 1,
/* 00227 */ HB_P_LINEOFFSET, 14,	/* 313 */
	HB_P_ZERO,
	HB_P_POPSTATIC, 24, 0,	/* NLIN */
/* 00233 */ HB_P_LINEOFFSET, 15,	/* 314 */
	HB_P_ZERO,
	HB_P_POPSTATIC, 23, 0,	/* I */
	HB_P_PUSHSTATIC, 23, 0,	/* I */
	HB_P_PUSHBYTE, 16,	/* 16 */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSE, 142, 0,	/* 142 (abs: 00387) */
/* 00248 */ HB_P_LINEOFFSET, 16,	/* 315 */
	HB_P_PUSHSYMNEAR, 98,	/* CREATEPEN */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHSYMNEAR, 104,	/* NRGB */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_PUSHSTATIC, 23, 0,	/* I */
	HB_P_PUSHBYTE, 8,	/* 8 */
	HB_P_MULT,
	HB_P_ADDINT, 100, 0,	/* 100*/
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPSTATIC, 22, 0,	/* HPEN */
/* 00277 */ HB_P_LINEOFFSET, 17,	/* 316 */
	HB_P_PUSHSYMNEAR, 99,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSTATIC, 22, 0,	/* HPEN */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPVARIABLE, 101, 0,	/* HOLDPEN */
/* 00298 */ HB_P_LINEOFFSET, 18,	/* 317 */
	HB_P_PUSHSYMNEAR, 105,	/* MOVETO */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_ZERO,
	HB_P_PUSHSTATIC, 24, 0,	/* NLIN */
	HB_P_DOSHORT, 3,
/* 00317 */ HB_P_LINEOFFSET, 19,	/* 318 */
	HB_P_PUSHSYMNEAR, 106,	/* LINETO */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHINT, 33, 1,	/* 289 */
	HB_P_PUSHSTATIC, 24, 0,	/* NLIN */
	HB_P_DOSHORT, 3,
/* 00338 */ HB_P_LINEOFFSET, 20,	/* 319 */
	HB_P_PUSHSYMNEAR, 99,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHVARIABLE, 101, 0,	/* HOLDPEN */
	HB_P_DOSHORT, 2,
/* 00356 */ HB_P_LINEOFFSET, 21,	/* 320 */
	HB_P_PUSHSYMNEAR, 103,	/* DELETEOBJECT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 22, 0,	/* HPEN */
	HB_P_DOSHORT, 1,
/* 00366 */ HB_P_LINEOFFSET, 22,	/* 321 */
	HB_P_PUSHSTATIC, 24, 0,	/* NLIN */
	HB_P_INC,
	HB_P_POPSTATIC, 24, 0,	/* NLIN */
/* 00375 */ HB_P_LINEOFFSET, 23,	/* 322 */
	HB_P_PUSHSTATIC, 23, 0,	/* I */
	HB_P_INC,
	HB_P_POPSTATIC, 23, 0,	/* I */
	HB_P_JUMP, 111, 255,	/* -145 (abs: 00239) */
/* 00387 */ HB_P_LINEOFFSET, 24,	/* 323 */
	HB_P_PUSHBYTE, 16,	/* 16 */
	HB_P_POPSTATIC, 23, 0,	/* I */
	HB_P_PUSHSTATIC, 23, 0,	/* I */
	HB_P_ZERO,
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_FORTEST,
	HB_P_JUMPFALSE, 144, 0,	/* 144 (abs: 00545) */
/* 00404 */ HB_P_LINEOFFSET, 25,	/* 324 */
	HB_P_PUSHSYMNEAR, 98,	/* CREATEPEN */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHSYMNEAR, 104,	/* NRGB */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_ZERO,
	HB_P_PUSHSTATIC, 23, 0,	/* I */
	HB_P_PUSHBYTE, 8,	/* 8 */
	HB_P_MULT,
	HB_P_ADDINT, 100, 0,	/* 100*/
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPSTATIC, 22, 0,	/* HPEN */
/* 00433 */ HB_P_LINEOFFSET, 26,	/* 325 */
	HB_P_PUSHSYMNEAR, 99,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSTATIC, 22, 0,	/* HPEN */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPVARIABLE, 101, 0,	/* HOLDPEN */
/* 00454 */ HB_P_LINEOFFSET, 27,	/* 326 */
	HB_P_PUSHSYMNEAR, 105,	/* MOVETO */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_ZERO,
	HB_P_PUSHSTATIC, 24, 0,	/* NLIN */
	HB_P_DOSHORT, 3,
/* 00473 */ HB_P_LINEOFFSET, 28,	/* 327 */
	HB_P_PUSHSYMNEAR, 106,	/* LINETO */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHINT, 33, 1,	/* 289 */
	HB_P_PUSHSTATIC, 24, 0,	/* NLIN */
	HB_P_DOSHORT, 3,
/* 00494 */ HB_P_LINEOFFSET, 29,	/* 328 */
	HB_P_PUSHSYMNEAR, 99,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHVARIABLE, 101, 0,	/* HOLDPEN */
	HB_P_DOSHORT, 2,
/* 00512 */ HB_P_LINEOFFSET, 30,	/* 329 */
	HB_P_PUSHSYMNEAR, 103,	/* DELETEOBJECT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 22, 0,	/* HPEN */
	HB_P_DOSHORT, 1,
/* 00522 */ HB_P_LINEOFFSET, 31,	/* 330 */
	HB_P_PUSHSTATIC, 24, 0,	/* NLIN */
	HB_P_INC,
	HB_P_POPSTATIC, 24, 0,	/* NLIN */
/* 00531 */ HB_P_LINEOFFSET, 32,	/* 331 */
	HB_P_PUSHSTATIC, 23, 0,	/* I */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_PLUS,
	HB_P_POPSTATIC, 23, 0,	/* I */
	HB_P_JUMP, 108, 255,	/* -148 (abs: 00394) */
/* 00545 */ HB_P_LINEOFFSET, 34,	/* 333 */
	HB_P_PUSHINT, 232, 0,	/* 232 */
	HB_P_POPSTATIC, 24, 0,	/* NLIN */
/* 00553 */ HB_P_LINEOFFSET, 35,	/* 334 */
	HB_P_ZERO,
	HB_P_POPSTATIC, 23, 0,	/* I */
	HB_P_PUSHSTATIC, 23, 0,	/* I */
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSE, 142, 0,	/* 142 (abs: 00707) */
/* 00568 */ HB_P_LINEOFFSET, 36,	/* 335 */
	HB_P_PUSHSYMNEAR, 98,	/* CREATEPEN */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHSYMNEAR, 104,	/* NRGB */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_PUSHSTATIC, 23, 0,	/* I */
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_MULT,
	HB_P_ADDINT, 70, 0,	/* 70*/
	HB_P_ZERO,
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPSTATIC, 22, 0,	/* HPEN */
/* 00597 */ HB_P_LINEOFFSET, 37,	/* 336 */
	HB_P_PUSHSYMNEAR, 99,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSTATIC, 22, 0,	/* HPEN */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPVARIABLE, 101, 0,	/* HOLDPEN */
/* 00618 */ HB_P_LINEOFFSET, 38,	/* 337 */
	HB_P_PUSHSYMNEAR, 105,	/* MOVETO */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_ZERO,
	HB_P_PUSHSTATIC, 24, 0,	/* NLIN */
	HB_P_DOSHORT, 3,
/* 00637 */ HB_P_LINEOFFSET, 39,	/* 338 */
	HB_P_PUSHSYMNEAR, 106,	/* LINETO */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHINT, 33, 1,	/* 289 */
	HB_P_PUSHSTATIC, 24, 0,	/* NLIN */
	HB_P_DOSHORT, 3,
/* 00658 */ HB_P_LINEOFFSET, 40,	/* 339 */
	HB_P_PUSHSYMNEAR, 99,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHVARIABLE, 101, 0,	/* HOLDPEN */
	HB_P_DOSHORT, 2,
/* 00676 */ HB_P_LINEOFFSET, 41,	/* 340 */
	HB_P_PUSHSYMNEAR, 103,	/* DELETEOBJECT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 22, 0,	/* HPEN */
	HB_P_DOSHORT, 1,
/* 00686 */ HB_P_LINEOFFSET, 42,	/* 341 */
	HB_P_PUSHSTATIC, 24, 0,	/* NLIN */
	HB_P_INC,
	HB_P_POPSTATIC, 24, 0,	/* NLIN */
/* 00695 */ HB_P_LINEOFFSET, 43,	/* 342 */
	HB_P_PUSHSTATIC, 23, 0,	/* I */
	HB_P_INC,
	HB_P_POPSTATIC, 23, 0,	/* I */
	HB_P_JUMP, 111, 255,	/* -145 (abs: 00559) */
/* 00707 */ HB_P_LINEOFFSET, 44,	/* 343 */
	HB_P_PUSHBYTE, 13,	/* 13 */
	HB_P_POPSTATIC, 23, 0,	/* I */
	HB_P_PUSHSTATIC, 23, 0,	/* I */
	HB_P_ZERO,
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_FORTEST,
	HB_P_JUMPFALSE, 144, 0,	/* 144 (abs: 00865) */
/* 00724 */ HB_P_LINEOFFSET, 45,	/* 344 */
	HB_P_PUSHSYMNEAR, 98,	/* CREATEPEN */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHSYMNEAR, 104,	/* NRGB */
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_PUSHSTATIC, 23, 0,	/* I */
	HB_P_PUSHBYTE, 5,	/* 5 */
	HB_P_MULT,
	HB_P_ADDINT, 70, 0,	/* 70*/
	HB_P_ZERO,
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPSTATIC, 22, 0,	/* HPEN */
/* 00753 */ HB_P_LINEOFFSET, 46,	/* 345 */
	HB_P_PUSHSYMNEAR, 99,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSTATIC, 22, 0,	/* HPEN */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPVARIABLE, 101, 0,	/* HOLDPEN */
/* 00774 */ HB_P_LINEOFFSET, 47,	/* 346 */
	HB_P_PUSHSYMNEAR, 105,	/* MOVETO */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_ZERO,
	HB_P_PUSHSTATIC, 24, 0,	/* NLIN */
	HB_P_DOSHORT, 3,
/* 00793 */ HB_P_LINEOFFSET, 48,	/* 347 */
	HB_P_PUSHSYMNEAR, 106,	/* LINETO */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHINT, 33, 1,	/* 289 */
	HB_P_PUSHSTATIC, 24, 0,	/* NLIN */
	HB_P_DOSHORT, 3,
/* 00814 */ HB_P_LINEOFFSET, 49,	/* 348 */
	HB_P_PUSHSYMNEAR, 99,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* HDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHVARIABLE, 101, 0,	/* HOLDPEN */
	HB_P_DOSHORT, 2,
/* 00832 */ HB_P_LINEOFFSET, 50,	/* 349 */
	HB_P_PUSHSYMNEAR, 103,	/* DELETEOBJECT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 22, 0,	/* HPEN */
	HB_P_DOSHORT, 1,
/* 00842 */ HB_P_LINEOFFSET, 51,	/* 350 */
	HB_P_PUSHSTATIC, 24, 0,	/* NLIN */
	HB_P_INC,
	HB_P_POPSTATIC, 24, 0,	/* NLIN */
/* 00851 */ HB_P_LINEOFFSET, 52,	/* 351 */
	HB_P_PUSHSTATIC, 23, 0,	/* I */
	HB_P_PUSHBYTE, 255,	/* -1 */
	HB_P_PLUS,
	HB_P_POPSTATIC, 23, 0,	/* I */
	HB_P_JUMP, 108, 255,	/* -148 (abs: 00714) */
/* 00865 */ HB_P_LINEOFFSET, 55,	/* 354 */
	HB_P_MESSAGE, 107, 0,	/* RELEASEDC */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00876 */ HB_P_LINEOFFSET, 56,	/* 355 */
	HB_P_MESSAGE, 108, 0,	/* REFRESH */
	HB_P_PUSHSTATIC, 8, 0,	/* OBUT1 */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00887 */ HB_P_LINEOFFSET, 57,	/* 356 */
	HB_P_MESSAGE, 108, 0,	/* REFRESH */
	HB_P_PUSHSTATIC, 9, 0,	/* OBUT2 */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00898 */ HB_P_LINEOFFSET, 58,	/* 357 */
	HB_P_MESSAGE, 108, 0,	/* REFRESH */
	HB_P_PUSHSTATIC, 10, 0,	/* OSAYHOJE */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00909 */ HB_P_LINEOFFSET, 60,	/* 359 */
	HB_P_PUSHSTATIC, 2, 0,	/* NX */
	HB_P_POPSTATIC, 20, 0,	/* NXOLD */
/* 00917 */ HB_P_LINEOFFSET, 61,	/* 360 */
	HB_P_PUSHSTATIC, 3, 0,	/* NY */
	HB_P_POPSTATIC, 21, 0,	/* NYOLD */
/* 00925 */ HB_P_LINEOFFSET, 63,	/* 362 */
	HB_P_PUSHSTATIC, 1, 0,	/* LTRANSP */
	HB_P_JUMPFALSENEAR, 67,	/* 67 (abs: 00997) */
/* 00932 */ HB_P_LINEOFFSET, 67,	/* 366 */
	HB_P_PUSHSYMNEAR, 109,	/* SETWINDOWLONG */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 81, 0,	/* HWND */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 236,	/* -20 */
	HB_P_PUSHSYMNEAR, 60,	/* NOR */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 110,	/* GETWINDOWLONG */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 81, 0,	/* HWND */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 236,	/* -20 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PUSHLONG, 0, 0, 8, 0,	/* 524288 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_DOSHORT, 3,
/* 00974 */ HB_P_LINEOFFSET, 70,	/* 369 */
	HB_P_PUSHSYMNEAR, 111,	/* SETLAYEREDWINDOWATTRIBUTES */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 81, 0,	/* HWND */
	HB_P_PUSHSTATIC, 6, 0,	/* ODLGDT */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 25, 0,	/* NFACTOR */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DOSHORT, 4,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00997) */
/* 00997 */ HB_P_LINEOFFSET, 74,	/* 373 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 01002 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( SETLAYEREDWINDOWATTRIBUTES )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 3, 4,	/* locals, params */
	HB_P_PUSHSYMNEAR, 112,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'u', 's', 'e', 'r', '3', '2', '.', 'D', 'L', 'L', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 17,	/* 17 (abs: 00043) */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'u', 's', 'e', 'r', '3', '2', '.', 'D', 'L', 'L', 0, 
	HB_P_JUMPNEAR, 20,	/* 20 (abs: 00061) */
	HB_P_PUSHSYMNEAR, 113,	/* LOADLIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'u', 's', 'e', 'r', '3', '2', '.', 'D', 'L', 'L', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 5,	/* HDLL */
	HB_P_PUSHSYMNEAR, 114,	/* ABS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 32,	/* 32 */
	HB_P_GREATER,
	HB_P_JUMPFALSE, 176, 0,	/* 176 (abs: 00249) */
	HB_P_PUSHSYMNEAR, 115,	/* GETPROCADDRESS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* HDLL */
	HB_P_PUSHSYMNEAR, 116,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 27,	/* 27 */
	'S', 'e', 't', 'L', 'a', 'y', 'e', 'r', 'e', 'd', 'W', 'i', 'n', 'd', 'o', 'w', 'A', 't', 't', 'r', 'i', 'b', 'u', 't', 'e', 's', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_TRUE,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 33,	/* 33 (abs: 00150) */
	HB_P_PUSHSTRSHORT, 27,	/* 27 */
	'S', 'e', 't', 'L', 'a', 'y', 'e', 'r', 'e', 'd', 'W', 'i', 'n', 'd', 'o', 'w', 'A', 't', 't', 'r', 'i', 'b', 'u', 't', 'e', 's', 0, 
	HB_P_JUMPNEAR, 31,	/* 31 (abs: 00179) */
	HB_P_PUSHSTRSHORT, 27,	/* 27 */
	'S', 'e', 't', 'L', 'a', 'y', 'e', 'r', 'e', 'd', 'W', 'i', 'n', 'd', 'o', 'w', 'A', 't', 't', 'r', 'i', 'b', 'u', 't', 'e', 's', 0, 
	HB_P_TRUE,
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_PUSHBYTE, 7,	/* 7 */
	HB_P_FUNCTIONSHORT, 8,
	HB_P_POPLOCALNEAR, 7,	/* CFARPROC */
	HB_P_PUSHSYMNEAR, 117,	/* CALLDLL */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 7,	/* CFARPROC */
	HB_P_PUSHLOCALNEAR, 1,	/* HWND */
	HB_P_PUSHLOCALNEAR, 2,	/* CRKEY */
	HB_P_PUSHLOCALNEAR, 3,	/* BALPHA */
	HB_P_PUSHLOCALNEAR, 4,	/* DWFLAGS */
	HB_P_FUNCTIONSHORT, 5,
	HB_P_POPLOCALNEAR, 6,	/* URESULT */
	HB_P_PUSHSYMNEAR, 112,	/* VALTYPE */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'u', 's', 'e', 'r', '3', '2', '.', 'D', 'L', 'L', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'N', 0, 
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00239) */
	HB_P_PUSHNIL,
	HB_P_JUMPNEAR, 9,	/* 9 (abs: 00246) */
	HB_P_PUSHSYMNEAR, 118,	/* FREELIBRARY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 62,	/* 62 (abs: 00309) */
	HB_P_PUSHSYMNEAR, 119,	/* MSGALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 13,	/* 13 */
	'E', 'r', 'r', 'o', 'r', ' ', 'c', 'o', 'd', 'e', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 120,	/* LTRIM */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 77,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 5,	/* HDLL */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	' ', 'l', 'o', 'a', 'd', 'i', 'n', 'g', ' ', 0, 
	HB_P_PLUS,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'u', 's', 'e', 'r', '3', '2', '.', 'D', 'L', 'L', 0, 
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
	HB_P_PUSHLOCALNEAR, 6,	/* URESULT */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00313 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

static HARBOUR hb_INITSTATICS( void )
{
   static const BYTE pcode[] =
   {
	HB_P_STATICS, 122, 0, 25, 0,	/* symbol (_INITSTATICS), 25 statics */
	HB_P_SFRAME, 122, 0,	/* symbol (_INITSTATICS) */
	HB_P_FALSE,
	HB_P_POPSTATIC, 1, 0,	/* LTRANSP */
	HB_P_PUSHBYTE, 156,	/* -100 */
	HB_P_POPSTATIC, 2, 0,	/* NX */
	HB_P_PUSHBYTE, 156,	/* -100 */
	HB_P_POPSTATIC, 3, 0,	/* NY */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'J', 'a', 'n', 'e', 'i', 'r', 'o', 0, 
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'F', 'e', 'v', 'e', 'r', 'e', 'i', 'r', 'o', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'M', 'a', 'r', 231, 'o', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'A', 'b', 'r', 'i', 'l', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'M', 'a', 'i', 'o', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'J', 'u', 'n', 'h', 'o', 0, 
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'J', 'u', 'l', 'h', 'o', 0, 
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'A', 'g', 'o', 's', 't', 'o', 0, 
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'S', 'e', 't', 'e', 'm', 'b', 'r', 'o', 0, 
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'O', 'u', 't', 'u', 'b', 'r', 'o', 0, 
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'N', 'o', 'v', 'e', 'm', 'b', 'r', 'o', 0, 
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'D', 'e', 'z', 'e', 'm', 'b', 'r', 'o', 0, 
	HB_P_ARRAYGEN, 12, 0,	/* 12 */
	HB_P_POPSTATIC, 19, 0,	/* AMESES */
	HB_P_PUSHBYTE, 156,	/* -100 */
	HB_P_POPSTATIC, 20, 0,	/* NXOLD */
	HB_P_PUSHBYTE, 156,	/* -100 */
	HB_P_POPSTATIC, 21, 0,	/* NYOLD */
	HB_P_PUSHINT, 200, 0,	/* 200 */
	HB_P_POPSTATIC, 25, 0,	/* NFACTOR */
	HB_P_ENDPROC
/* 00158 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

