/*
 * xHarbour Compiler, build 82.0 (SimpLex)
 * Generated C source code from <c:/SGMTO/program/SL.prg>
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "c:/SGMTO/program/SL.prg"

HB_FUNC( SL );
HB_FUNC( TEST_DIALOG );
HB_FUNC( TEST_RESOURCE );
HB_FUNC_STATIC( TRIANGULO );
HB_FUNC( APPSYS );

static HARBOUR hb_INITSTATICS( void );

extern HB_FUNC( SPACE );
extern HB_FUNC( TWINDOW );
extern HB_FUNC( TMSGBAR );
extern HB_FUNC( TPEN );
extern HB_FUNC( TSAY );
extern HB_FUNC( TSLIDER );
extern HB_FUNC( PCOUNT );
extern HB_FUNC( STR );
extern HB_FUNC( TBUTTON );
extern HB_FUNC( TFONT );
extern HB_FUNC( TDIALOG );
extern HB_FUNC( ROUND );
extern HB_FUNC( MSGBEEP );
extern HB_FUNC( GETDC );
extern HB_FUNC( MOVETO );
extern HB_FUNC( LINETO );
extern HB_FUNC( RELEASEDC );
extern HB_FUNC( ERRORSYS );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 5

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_SL )
{ "SL", HB_FS_PUBLIC | HB_FS_FIRST, HB_FUNCNAME( SL ), (PHB_DYNS) 1 },
{ "SPACE", HB_FS_PUBLIC, HB_FUNCNAME( SPACE ), NULL },
{ "NEW", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TWINDOW", HB_FS_PUBLIC, HB_FUNCNAME( TWINDOW ), NULL },
{ "_OMSGBAR", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TMSGBAR", HB_FS_PUBLIC, HB_FUNCNAME( TMSGBAR ), NULL },
{ "TPEN", HB_FS_PUBLIC, HB_FUNCNAME( TPEN ), NULL },
{ "TSAY", HB_FS_PUBLIC, HB_FUNCNAME( TSAY ), NULL },
{ "TSLIDER", HB_FS_PUBLIC, HB_FUNCNAME( TSLIDER ), NULL },
{ "PCOUNT", HB_FS_PUBLIC, HB_FUNCNAME( PCOUNT ), NULL },
{ "STR", HB_FS_PUBLIC, HB_FUNCNAME( STR ), NULL },
{ "REFRESH", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TRIANGULO", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TRIANGULO ), (PHB_DYNS) 1 },
{ "TBUTTON", HB_FS_PUBLIC, HB_FUNCNAME( TBUTTON ), NULL },
{ "SET", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TEST_DIALOG", HB_FS_PUBLIC, HB_FUNCNAME( TEST_DIALOG ), (PHB_DYNS) 1 },
{ "TEST_RESOURCE", HB_FS_PUBLIC, HB_FUNCNAME( TEST_RESOURCE ), (PHB_DYNS) 1 },
{ "ACTIVATE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BLCLICKED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BRCLICKED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BMOVED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BRESIZED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_BPAINTED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BKEYDOWN", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BINIT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BLBUTTONUP", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "END", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TFONT", HB_FS_PUBLIC, HB_FUNCNAME( TFONT ), NULL },
{ "TDIALOG", HB_FS_PUBLIC, HB_FUNCNAME( TDIALOG ), NULL },
{ "BPAINTED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "REDEFINE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ROUND", HB_FS_PUBLIC, HB_FUNCNAME( ROUND ), NULL },
{ "ENABLE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "DISABLE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "MSGBEEP", HB_FS_PUBLIC, HB_FUNCNAME( MSGBEEP ), NULL },
{ "GETDC", HB_FS_PUBLIC, HB_FUNCNAME( GETDC ), NULL },
{ "HWND", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "MOVETO", HB_FS_PUBLIC, HB_FUNCNAME( MOVETO ), NULL },
{ "LINETO", HB_FS_PUBLIC, HB_FUNCNAME( LINETO ), NULL },
{ "HPEN", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "RELEASEDC", HB_FS_PUBLIC, HB_FUNCNAME( RELEASEDC ), NULL },
{ "APPSYS", HB_FS_PUBLIC, HB_FUNCNAME( APPSYS ), (PHB_DYNS) 1 },
{ "ERRORSYS", HB_FS_PUBLIC, HB_FUNCNAME( ERRORSYS ), NULL },
{ "(_INITSTATICS)", HB_FS_INIT | HB_FS_EXIT, hb_INITSTATICS, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_SL )

#if defined(HB_STATIC_STARTUP)
   #pragma startup hb_vm_SymbolInit_SL
#elif defined(_MSC_VER)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_SL = hb_vm_SymbolInit_SL;
   #pragma data_seg()
#elif ! defined(__GNUC__)
   #pragma startup hb_vm_SymbolInit_SL
#endif

HB_FUNC( SL )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 6, 0,	/* locals, params */
	HB_P_SFRAME, 43, 0,	/* symbol (_INITSTATICS) */
/* 00006 */ HB_P_BASELINE, 17, 0,	/* 17 */
	HB_P_LOCALNEARSETSTR, 1, 28, 0,	/* CTITLE 28*/
	'T', 'e', 's', 't', 'i', 'n', 'g', ' ', 't', 'h', 'e', ' ', 'S', 'l', 'i', 'd', 'e', 'r', ' ', 'c', 'o', 'n', 't', 'r', 'o', 'l', 's', 0, 
/* 00041 */ HB_P_LINEOFFSET, 2,	/* 19 */
	HB_P_PUSHSYMNEAR, 1,	/* SPACE */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 3,	/* CSAY */
/* 00052 */ HB_P_LINEOFFSET, 4,	/* 21 */
	HB_P_LOCALNEARSETINT, 4, 150, 0,	/* NVAR1 150*/
	HB_P_LOCALNEARSETINT, 5, 100, 0,	/* NVAR2 100*/
	HB_P_LOCALNEARSETINT, 6, 150, 0,	/* NVAR3 150*/
/* 00066 */ HB_P_LINEOFFSET, 8,	/* 25 */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 3,	/* TWINDOW */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ONE,
	HB_P_ONE,
	HB_P_PUSHINT, 144, 1,	/* 400 */
	HB_P_PUSHINT, 88, 2,	/* 600 */
	HB_P_PUSHLOCALNEAR, 1,	/* CTITLE */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ZERO,
	HB_P_PUSHLONG, 192, 192, 192, 0,	/* 12632256 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_SENDSHORT, 21,
	HB_P_POPSTATIC, 1, 0,	/* OWND */
/* 00111 */ HB_P_LINEOFFSET, 10,	/* 27 */
	HB_P_MESSAGE, 4, 0,	/* _OMSGBAR */
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 5,	/* TMSGBAR */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_PUSHLOCALNEAR, 1,	/* CTITLE */
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 10,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00145 */ HB_P_LINEOFFSET, 12,	/* 29 */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 6,	/* TPEN */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_PUSHLONG, 0, 0, 128, 0,	/* 8388608 */
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 4,
	HB_P_POPSTATIC, 2, 0,	/* OPEN */
/* 00169 */ HB_P_LINEOFFSET, 13,	/* 30 */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 6,	/* TPEN */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_PUSHLONG, 192, 192, 192, 0,	/* 12632256 */
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 4,
	HB_P_POPSTATIC, 3, 0,	/* OPEN_ */
/* 00193 */ HB_P_LINEOFFSET, 15,	/* 32 */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 7,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHINT, 130, 0,	/* 130 */
	HB_P_PUSHBLOCK, 12, 0,	/* 12 */
	0, 0,	/* number of local parameters (0) */
	1, 0,	/* number of local variables (1) */
	3, 0,	/* CSAY */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 19,
	HB_P_POPLOCALNEAR, 2,	/* OSAY */
/* 00242 */ HB_P_LINEOFFSET, 24,	/* 41 */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 8,	/* TSLIDER */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 30,	/* 30 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHBLOCK, 28, 0,	/* 28 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	4, 0,	/* NVAR1 */
	HB_P_PUSHSYMNEAR, 9,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00278) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 00283) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 60,	/* 60 */
	HB_P_PUSHINT, 44, 1,	/* 300 */
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_FALSE,
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_PUSHBLOCK, 30, 0,	/* 30 */
	1, 0,	/* number of local parameters (1) */
	3, 0,	/* number of local variables (3) */
	4, 0,	/* NVAR1 */
	3, 0,	/* CSAY */
	2, 0,	/* OSAY */
	HB_P_PUSHSYMNEAR, 10,	/* STR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 254,	/* localvar2 */
	HB_P_MESSAGE, 11, 0,	/* REFRESH */
	HB_P_PUSHLOCALNEAR, 253,	/* localvar3 */
	HB_P_SENDSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHBLOCK, 23, 0,	/* 23 */
	1, 0,	/* number of local parameters (1) */
	2, 0,	/* number of local variables (2) */
	5, 0,	/* NVAR2 */
	6, 0,	/* NVAR3 */
	HB_P_PUSHSYMNEAR, 12,	/* TRIANGULO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_PUSHLOCALNEAR, 254,	/* localvar2 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_ENDBLOCK,
	HB_P_PUSHINT, 54, 1,	/* 310 */
	HB_P_PUSHBYTE, 33,	/* 33 */
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 22,
	HB_P_POPSTATIC, 6, 0,	/* OSLIDE1 */
/* 00368 */ HB_P_LINEOFFSET, 34,	/* 51 */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 8,	/* TSLIDER */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 39, 1,	/* 295 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHBLOCK, 28, 0,	/* 28 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	5, 0,	/* NVAR2 */
	HB_P_PUSHSYMNEAR, 9,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00405) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 00410) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_PUSHINT, 210, 0,	/* 210 */
	HB_P_PUSHBYTE, 21,	/* 21 */
	HB_P_TRUE,
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_PUSHBLOCK, 23, 0,	/* 23 */
	1, 0,	/* number of local parameters (1) */
	2, 0,	/* number of local variables (2) */
	4, 0,	/* NVAR1 */
	6, 0,	/* NVAR3 */
	HB_P_PUSHSYMNEAR, 12,	/* TRIANGULO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHLOCALNEAR, 254,	/* localvar2 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_ENDBLOCK,
	HB_P_PUSHBLOCK, 23, 0,	/* 23 */
	1, 0,	/* number of local parameters (1) */
	2, 0,	/* number of local variables (2) */
	4, 0,	/* NVAR1 */
	6, 0,	/* NVAR3 */
	HB_P_PUSHSYMNEAR, 12,	/* TRIANGULO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHLOCALNEAR, 254,	/* localvar2 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_ENDBLOCK,
	HB_P_PUSHINT, 210, 0,	/* 210 */
	HB_P_PUSHBYTE, 33,	/* 33 */
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 22,
	HB_P_POPSTATIC, 7, 0,	/* OSLIDE2 */
/* 00488 */ HB_P_LINEOFFSET, 37,	/* 54 */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 13,	/* TBUTTON */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 49, 1,	/* 305 */
	HB_P_PUSHINT, 250, 0,	/* 250 */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'&', 'P', 'u', 'l', 's', 'a', 0, 
	HB_P_MACROTEXT,
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_PUSHBLOCK, 37, 0,	/* 37 */
	0, 0,	/* number of local parameters (0) */
	3, 0,	/* number of local variables (3) */
	4, 0,	/* NVAR1 */
	5, 0,	/* NVAR2 */
	6, 0,	/* NVAR3 */
	HB_P_MESSAGE, 14, 0,	/* SET */
	HB_P_PUSHSTATIC, 7, 0,	/* OSLIDE2 */
	HB_P_PUSHINT, 150, 0,	/* 150 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_PUSHSYMNEAR, 12,	/* TRIANGULO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_PUSHLOCALNEAR, 254,	/* localvar2 */
	HB_P_PUSHLOCALNEAR, 253,	/* localvar3 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_ENDBLOCK,
	HB_P_PUSHBYTE, 62,	/* 62 */
	HB_P_PUSHBYTE, 18,	/* 18 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 17,
	HB_P_POPSTATIC, 4, 0,	/* OBTN */
/* 00573 */ HB_P_LINEOFFSET, 44,	/* 61 */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 8,	/* TSLIDER */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 65,	/* 65 */
	HB_P_PUSHINT, 104, 1,	/* 360 */
	HB_P_PUSHBLOCK, 28, 0,	/* 28 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	6, 0,	/* NVAR3 */
	HB_P_PUSHSYMNEAR, 9,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00610) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 00615) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 80,	/* 80 */
	HB_P_PUSHINT, 24, 1,	/* 280 */
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FALSE,
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_PUSHNIL,
	HB_P_PUSHBLOCK, 23, 0,	/* 23 */
	1, 0,	/* number of local parameters (1) */
	2, 0,	/* number of local variables (2) */
	4, 0,	/* NVAR1 */
	5, 0,	/* NVAR2 */
	HB_P_PUSHSYMNEAR, 12,	/* TRIANGULO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_PUSHLOCALNEAR, 254,	/* localvar2 */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_ENDBLOCK,
	HB_P_PUSHBYTE, 35,	/* 35 */
	HB_P_PUSHINT, 240, 0,	/* 240 */
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 22,
	HB_P_POPSTATIC, 8, 0,	/* OSLIDE3 */
/* 00671 */ HB_P_LINEOFFSET, 46,	/* 63 */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 7,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 75,	/* 75 */
	HB_P_PUSHINT, 144, 1,	/* 400 */
	HB_P_PUSHBLOCKSHORT, 10,	/* 10 */
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'M', 'a', 'x', '.', 0, 
	HB_P_ENDBLOCK,
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 19,
	HB_P_POP,
/* 00717 */ HB_P_LINEOFFSET, 47,	/* 64 */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 7,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 24, 1,	/* 280 */
	HB_P_PUSHINT, 144, 1,	/* 400 */
	HB_P_PUSHBLOCKSHORT, 10,	/* 10 */
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'M', 'i', 'n', '.', 0, 
	HB_P_ENDBLOCK,
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 19,
	HB_P_POP,
/* 00764 */ HB_P_LINEOFFSET, 49,	/* 66 */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 13,	/* TBUTTON */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 200, 0,	/* 200 */
	HB_P_PUSHINT, 194, 1,	/* 450 */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'&', 'D', 'i', 'a', 'l', 'o', 'g', 0, 
	HB_P_MACROTEXT,
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_PUSHBLOCKSHORT, 8,	/* 8 */
	HB_P_PUSHSYMNEAR, 15,	/* TEST_DIALOG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHBYTE, 92,	/* 92 */
	HB_P_PUSHBYTE, 22,	/* 22 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 17,
	HB_P_POP,
/* 00819 */ HB_P_LINEOFFSET, 50,	/* 67 */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 13,	/* TBUTTON */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 235, 0,	/* 235 */
	HB_P_PUSHINT, 194, 1,	/* 450 */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'&', 'R', 'e', 's', 'o', 'u', 'r', 'c', 'e', 0, 
	HB_P_MACROTEXT,
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_PUSHBLOCKSHORT, 8,	/* 8 */
	HB_P_PUSHSYMNEAR, 16,	/* TEST_RESOURCE */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHBYTE, 92,	/* 92 */
	HB_P_PUSHBYTE, 22,	/* 22 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 17,
	HB_P_POP,
/* 00876 */ HB_P_LINEOFFSET, 53,	/* 70 */
	HB_P_MESSAGE, 17, 0,	/* ACTIVATE */
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 18, 0,	/* BLCLICKED */
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 19, 0,	/* BRCLICKED */
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 20, 0,	/* BMOVED */
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 21, 0,	/* BRESIZED */
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 22, 0,	/* _BPAINTED */
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	2, 0,	/* number of local parameters (2) */
	3, 0,	/* number of local variables (3) */
	4, 0,	/* NVAR1 */
	5, 0,	/* NVAR2 */
	6, 0,	/* NVAR3 */
	HB_P_PUSHSYMNEAR, 12,	/* TRIANGULO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_PUSHLOCALNEAR, 254,	/* localvar2 */
	HB_P_PUSHLOCALNEAR, 253,	/* localvar3 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_ENDBLOCK,
	HB_P_SENDSHORT, 1,
	HB_P_MESSAGE, 23, 0,	/* BKEYDOWN */
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 24, 0,	/* BINIT */
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 25, 0,	/* BLBUTTONUP */
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 19,
	HB_P_POP,
/* 00987 */ HB_P_LINEOFFSET, 55,	/* 72 */
	HB_P_MESSAGE, 26, 0,	/* END */
	HB_P_PUSHSTATIC, 2, 0,	/* OPEN */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_PUSHNIL,
	HB_P_POPSTATIC, 2, 0,	/* OPEN */
/* 01002 */ HB_P_LINEOFFSET, 56,	/* 73 */
	HB_P_MESSAGE, 26, 0,	/* END */
	HB_P_PUSHSTATIC, 3, 0,	/* OPEN_ */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_PUSHNIL,
	HB_P_POPSTATIC, 3, 0,	/* OPEN_ */
/* 01017 */ HB_P_LINEOFFSET, 58,	/* 75 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 01022 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( TEST_DIALOG )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 6, 0,	/* locals, params */
	HB_P_SFRAME, 43, 0,	/* symbol (_INITSTATICS) */
/* 00006 */ HB_P_BASELINE, 83, 0,	/* 83 */
	HB_P_LOCALNEARSETINT, 6, 0, 0,	/* NVAR 0*/
/* 00013 */ HB_P_LINEOFFSET, 2,	/* 85 */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 27,	/* TFONT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'A', 'r', 'i', 'a', 'l', 0, 
	HB_P_ZERO,
	HB_P_PUSHBYTE, 176,	/* -80 */
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 17,
	HB_P_POPLOCALNEAR, 2,	/* OFONT */
/* 00052 */ HB_P_LINEOFFSET, 5,	/* 88 */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 28,	/* TDIALOG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_PUSHINT, 144, 1,	/* 400 */
	HB_P_PUSHINT, 244, 1,	/* 500 */
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'S', 'l', 'i', 'd', 'e', 'r', 's', ' ', 'd', 'i', 'a', 'l', 'o', 'g', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 19,
	HB_P_POPLOCALNEAR, 1,	/* ODLG */
/* 00109 */ HB_P_LINEOFFSET, 8,	/* 91 */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 7,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 60,	/* 60 */
	HB_P_PUSHBYTE, 80,	/* 80 */
	HB_P_PUSHBLOCK, 12, 0,	/* 12 */
	0, 0,	/* number of local parameters (0) */
	1, 0,	/* number of local variables (1) */
	6, 0,	/* NVAR */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* OFONT */
	HB_P_TRUE,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 19,
	HB_P_POPLOCALNEAR, 4,	/* OSAY */
/* 00159 */ HB_P_LINEOFFSET, 17,	/* 100 */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 8,	/* TSLIDER */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHBLOCK, 28, 0,	/* 28 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	6, 0,	/* NVAR */
	HB_P_PUSHSYMNEAR, 9,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00195) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 00200) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_PUSHBYTE, 236,	/* -20 */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_TRUE,
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_PUSHBLOCK, 17, 0,	/* 17 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	4, 0,	/* OSAY */
	HB_P_MESSAGE, 11, 0,	/* REFRESH */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 42,	/* 42 */
	HB_P_PUSHINT, 160, 0,	/* 160 */
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 22,
	HB_P_POPLOCALNEAR, 3,	/* OSLIDE */
/* 00247 */ HB_P_LINEOFFSET, 19,	/* 102 */
	HB_P_LOCALNEARSETINT, 5, 236, 255,	/* N -20*/
	HB_P_PUSHLOCALNEAR, 5,	/* N */
	HB_P_PUSHBYTE, 20,	/* 20 */
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_FORTEST,
	HB_P_JUMPFALSENEAR, 73,	/* 73 (abs: 00333) */
/* 00262 */ HB_P_LINEOFFSET, 20,	/* 103 */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 7,	/* TSAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHLOCALNEAR, 5,	/* N */
	HB_P_PUSHDOUBLE, 205, 204, 204, 204, 204, 204, 12, 64, 1, 1,	/* 3.6, 1, 1 */
	HB_P_MULT,
	HB_P_ADDINT, 86, 0,	/* 86*/
	HB_P_PUSHBYTE, 50,	/* 50 */
	HB_P_PUSHBLOCK, 12, 0,	/* 12 */
	0, 0,	/* number of local parameters (0) */
	1, 0,	/* number of local variables (1) */
	5, 0,	/* N */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 12,	/* 12 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 19,
	HB_P_POP,
/* 00325 */ HB_P_LINEOFFSET, 21,	/* 104 */
	HB_P_LOCALNEARADDINT, 5, 4, 0,	/* N 4*/
	HB_P_JUMPNEAR, 178,	/* -78 (abs: 00253) */
/* 00333 */ HB_P_LINEOFFSET, 23,	/* 106 */
	HB_P_MESSAGE, 17, 0,	/* ACTIVATE */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_MESSAGE, 18, 0,	/* BLCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 20, 0,	/* BMOVED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 29, 0,	/* BPAINTED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 19, 0,	/* BRCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 9,
	HB_P_POP,
/* 00376 */ HB_P_LINEOFFSET, 25,	/* 108 */
	HB_P_MESSAGE, 26, 0,	/* END */
	HB_P_PUSHLOCALNEAR, 2,	/* OFONT */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_PUSHNIL,
	HB_P_POPLOCALNEAR, 2,	/* OFONT */
/* 00389 */ HB_P_LINEOFFSET, 27,	/* 110 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00394 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( TEST_RESOURCE )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 4, 0,	/* locals, params */
	HB_P_SFRAME, 43, 0,	/* symbol (_INITSTATICS) */
/* 00006 */ HB_P_BASELINE, 117, 0,	/* 117 */
	HB_P_LOCALNEARSETINT, 4, 1, 0,	/* NVAR 1*/
/* 00013 */ HB_P_LINEOFFSET, 4,	/* 121 */
	HB_P_MESSAGE, 2, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 28,	/* TDIALOG */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'T', 'E', 'S', 'T', '_', 'S', 'L', 'I', 'D', 'E', 'R', 0, 
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 19,
	HB_P_POPLOCALNEAR, 1,	/* ODLG */
/* 00061 */ HB_P_LINEOFFSET, 12,	/* 129 */
	HB_P_MESSAGE, 30, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 8,	/* TSLIDER */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 101,	/* 101 */
	HB_P_PUSHBLOCK, 28, 0,	/* 28 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	4, 0,	/* NVAR */
	HB_P_PUSHSYMNEAR, 9,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00095) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 00100) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_FALSE,
	HB_P_TRUE,
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_ZERO,
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_FALSE,
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLONG, 255, 255, 255, 0,	/* 16777215 */
	HB_P_PUSHLONG, 128, 128, 128, 0,	/* 8421504 */
	HB_P_PUSHLONG, 255, 255, 255, 0,	/* 16777215 */
	HB_P_TRUE,
	HB_P_SENDSHORT, 17,
	HB_P_POPLOCALNEAR, 3,	/* OSLIDEA */
/* 00135 */ HB_P_LINEOFFSET, 20,	/* 137 */
	HB_P_MESSAGE, 30, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 8,	/* TSLIDER */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHBYTE, 102,	/* 102 */
	HB_P_PUSHBLOCK, 28, 0,	/* 28 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	4, 0,	/* NVAR */
	HB_P_PUSHSYMNEAR, 9,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00169) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 00174) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_TRUE,
	HB_P_ZERO,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHBYTE, 11,	/* 11 */
	HB_P_FALSE,
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHINT, 128, 0,	/* 128 */
	HB_P_PUSHLONG, 192, 192, 192, 0,	/* 12632256 */
	HB_P_PUSHLONG, 0, 128, 128, 0,	/* 8421376 */
	HB_P_TRUE,
	HB_P_SENDSHORT, 17,
	HB_P_POP,
/* 00206 */ HB_P_LINEOFFSET, 29,	/* 146 */
	HB_P_MESSAGE, 30, 0,	/* REDEFINE */
	HB_P_PUSHSYMNEAR, 8,	/* TSLIDER */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHINT, 201, 0,	/* 201 */
	HB_P_PUSHBLOCK, 28, 0,	/* 28 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	4, 0,	/* NVAR */
	HB_P_PUSHSYMNEAR, 9,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00241) */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 00246) */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 255,	/* localvar1 */
	HB_P_ENDBLOCK,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_ZERO,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_PUSHBLOCK, 56, 0,	/* 56 */
	1, 0,	/* number of local parameters (1) */
	2, 0,	/* number of local variables (2) */
	2, 0,	/* OSLIDE */
	3, 0,	/* OSLIDEA */
	HB_P_MESSAGE, 14, 0,	/* SET */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_PUSHSYMNEAR, 31,	/* ROUND */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_ZERO,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_ONE,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 00298) */
	HB_P_MESSAGE, 32, 0,	/* ENABLE */
	HB_P_PUSHLOCALNEAR, 254,	/* localvar2 */
	HB_P_SENDSHORT, 0,
	HB_P_JUMPNEAR, 9,	/* 9 (abs: 00305) */
	HB_P_MESSAGE, 33, 0,	/* DISABLE */
	HB_P_PUSHLOCALNEAR, 254,	/* localvar2 */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_PUSHSYMNEAR, 34,	/* MSGBEEP */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_FALSE,
	HB_P_SENDSHORT, 17,
	HB_P_POPLOCALNEAR, 2,	/* OSLIDE */
/* 00322 */ HB_P_LINEOFFSET, 31,	/* 148 */
	HB_P_MESSAGE, 17, 0,	/* ACTIVATE */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_MESSAGE, 18, 0,	/* BLCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 20, 0,	/* BMOVED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 29, 0,	/* BPAINTED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_FALSE,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 19, 0,	/* BRCLICKED */
	HB_P_PUSHLOCALNEAR, 1,	/* ODLG */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 9,
	HB_P_POP,
/* 00365 */ HB_P_LINEOFFSET, 33,	/* 150 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00370 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TRIANGULO )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 3,	/* locals, params */
	HB_P_SFRAME, 43, 0,	/* symbol (_INITSTATICS) */
/* 00006 */ HB_P_BASELINE, 160, 0,	/* 160 */
	HB_P_PUSHSYMNEAR, 35,	/* GETDC */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 36, 0,	/* HWND */
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 4,	/* HDC */
/* 00024 */ HB_P_LINEOFFSET, 2,	/* 162 */
	HB_P_PUSHSYMNEAR, 37,	/* MOVETO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* HDC */
	HB_P_PUSHSTATIC, 9, 0,	/* NVAR1 */
	HB_P_PUSHBYTE, 80,	/* 80 */
	HB_P_DOSHORT, 3,
/* 00038 */ HB_P_LINEOFFSET, 3,	/* 163 */
	HB_P_PUSHSYMNEAR, 38,	/* LINETO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* HDC */
	HB_P_PUSHSTATIC, 10, 0,	/* NVAR2 */
	HB_P_PUSHINT, 24, 1,	/* 280 */
	HB_P_MESSAGE, 39, 0,	/* HPEN */
	HB_P_PUSHSTATIC, 3, 0,	/* OPEN_ */
	HB_P_SENDSHORT, 0,
	HB_P_DOSHORT, 4,
/* 00061 */ HB_P_LINEOFFSET, 4,	/* 164 */
	HB_P_PUSHSYMNEAR, 38,	/* LINETO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* HDC */
	HB_P_PUSHINT, 64, 1,	/* 320 */
	HB_P_PUSHSTATIC, 11, 0,	/* NVAR3 */
	HB_P_MESSAGE, 39, 0,	/* HPEN */
	HB_P_PUSHSTATIC, 3, 0,	/* OPEN_ */
	HB_P_SENDSHORT, 0,
	HB_P_DOSHORT, 4,
/* 00084 */ HB_P_LINEOFFSET, 5,	/* 165 */
	HB_P_PUSHSYMNEAR, 38,	/* LINETO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* HDC */
	HB_P_PUSHSTATIC, 9, 0,	/* NVAR1 */
	HB_P_PUSHBYTE, 80,	/* 80 */
	HB_P_MESSAGE, 39, 0,	/* HPEN */
	HB_P_PUSHSTATIC, 3, 0,	/* OPEN_ */
	HB_P_SENDSHORT, 0,
	HB_P_DOSHORT, 4,
/* 00106 */ HB_P_LINEOFFSET, 7,	/* 167 */
	HB_P_PUSHLOCALNEAR, 1,	/* NVAL1 */
	HB_P_POPSTATIC, 9, 0,	/* NVAR1 */
/* 00113 */ HB_P_LINEOFFSET, 8,	/* 168 */
	HB_P_PUSHLOCALNEAR, 2,	/* NVAL2 */
	HB_P_POPSTATIC, 10, 0,	/* NVAR2 */
/* 00120 */ HB_P_LINEOFFSET, 9,	/* 169 */
	HB_P_PUSHLOCALNEAR, 3,	/* NVAL3 */
	HB_P_POPSTATIC, 11, 0,	/* NVAR3 */
/* 00127 */ HB_P_LINEOFFSET, 11,	/* 171 */
	HB_P_PUSHSYMNEAR, 37,	/* MOVETO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* NVAL1 */
	HB_P_PUSHBYTE, 80,	/* 80 */
	HB_P_DOSHORT, 3,
/* 00140 */ HB_P_LINEOFFSET, 12,	/* 172 */
	HB_P_PUSHSYMNEAR, 38,	/* LINETO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* HDC */
	HB_P_PUSHLOCALNEAR, 2,	/* NVAL2 */
	HB_P_PUSHINT, 24, 1,	/* 280 */
	HB_P_MESSAGE, 39, 0,	/* HPEN */
	HB_P_PUSHSTATIC, 2, 0,	/* OPEN */
	HB_P_SENDSHORT, 0,
	HB_P_DOSHORT, 4,
/* 00162 */ HB_P_LINEOFFSET, 13,	/* 173 */
	HB_P_PUSHSYMNEAR, 38,	/* LINETO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* HDC */
	HB_P_PUSHINT, 64, 1,	/* 320 */
	HB_P_PUSHLOCALNEAR, 3,	/* NVAL3 */
	HB_P_MESSAGE, 39, 0,	/* HPEN */
	HB_P_PUSHSTATIC, 2, 0,	/* OPEN */
	HB_P_SENDSHORT, 0,
	HB_P_DOSHORT, 4,
/* 00184 */ HB_P_LINEOFFSET, 14,	/* 174 */
	HB_P_PUSHSYMNEAR, 38,	/* LINETO */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* NVAL1 */
	HB_P_PUSHBYTE, 80,	/* 80 */
	HB_P_MESSAGE, 39, 0,	/* HPEN */
	HB_P_PUSHSTATIC, 2, 0,	/* OPEN */
	HB_P_SENDSHORT, 0,
	HB_P_DOSHORT, 4,
/* 00205 */ HB_P_LINEOFFSET, 16,	/* 176 */
	HB_P_PUSHSYMNEAR, 40,	/* RELEASEDC */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 36, 0,	/* HWND */
	HB_P_PUSHSTATIC, 1, 0,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 4,	/* HDC */
	HB_P_DOSHORT, 2,
/* 00222 */ HB_P_LINEOFFSET, 18,	/* 178 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00227 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC( APPSYS )
{
   static const BYTE pcode[] =
   {
/* 00000 */ HB_P_BASELINE, 182, 0,	/* 182 */
	HB_P_ENDPROC
/* 00004 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

static HARBOUR hb_INITSTATICS( void )
{
   static const BYTE pcode[] =
   {
	HB_P_STATICS, 43, 0, 11, 0,	/* symbol (_INITSTATICS), 11 statics */
	HB_P_SFRAME, 43, 0,	/* symbol (_INITSTATICS) */
	HB_P_PUSHBYTE, 156,	/* -100 */
	HB_P_POPSTATIC, 9, 0,	/* NVAR1 */
	HB_P_PUSHBYTE, 156,	/* -100 */
	HB_P_POPSTATIC, 10, 0,	/* NVAR2 */
	HB_P_PUSHBYTE, 156,	/* -100 */
	HB_P_POPSTATIC, 11, 0,	/* NVAR3 */
	HB_P_ENDPROC
/* 00024 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

