/*
 * xHarbour Compiler, build 82.0 (SimpLex)
 * Generated C source code from </vclon/VZLL/TREGLA.prg>
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "/vclon/VZLL/TREGLA.prg"

HB_FUNC( TREGLA );
HB_FUNC_STATIC( TREGLA_NEW );
HB_FUNC_STATIC( TREGLA_REDEFINE );
HB_FUNC_STATIC( TREGLA_DESTROY );
HB_FUNC_STATIC( TREGLA_PAINT );
HB_FUNC_STATIC( TREGLA_SCROLLUP );
HB_FUNC_STATIC( TREGLA_SCROLLDOWN );

static HARBOUR hb_INITSTATICS( void );

extern HB_FUNC( HBCLASS );
extern HB_FUNC( __CLS_PARAM );
extern HB_FUNC( __CLSINST );
extern HB_FUNC( PCOUNT );
extern HB_FUNC( HB_APARAMS );
extern HB_FUNC( GETWNDDEFAULT );
extern HB_FUNC( GETSYSCOLOR );
extern HB_FUNC( NOR );
extern HB_FUNC( TFONT );
extern HB_FUNC( TPEN );
extern HB_FUNC( EMPTY );
extern HB_FUNC( WNDRAISED );
extern HB_FUNC( SELECTOBJECT );
extern HB_FUNC( SETTEXTCOLOR );
extern HB_FUNC( SETBKCOLOR );
extern HB_FUNC( MOVETO );
extern HB_FUNC( LINETO );
extern HB_FUNC( STR );
extern HB_FUNC( TEXTOUT );
extern HB_FUNC( ERRORSYS );
extern HB_FUNC( TCONTROL );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 5

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_TREGLA )
{ "TREGLA", HB_FS_PUBLIC | HB_FS_FIRST, HB_FUNCNAME( TREGLA ), (PHB_DYNS) 1 },
{ "NEW", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "HBCLASS", HB_FS_PUBLIC, HB_FUNCNAME( HBCLASS ), NULL },
{ "__CLS_PARAM", HB_FS_PUBLIC, HB_FUNCNAME( __CLS_PARAM ), NULL },
{ "ADDMULTICLSDATA", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ADDMULTIDATA", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ADDMETHOD", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TREGLA_NEW", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TREGLA_NEW ), (PHB_DYNS) 1 },
{ "TREGLA_REDEFINE", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TREGLA_REDEFINE ), (PHB_DYNS) 1 },
{ "ADDINLINE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "DESTROY", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "INITIATE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TCONTROL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, HB_FUNCNAME( TCONTROL ), NULL },
{ "BEGINPAINT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "PAINT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ENDPAINT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TREGLA_PAINT", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TREGLA_PAINT ), (PHB_DYNS) 1 },
{ "_PIX2MM", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "LINCHES", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TREGLA_DESTROY", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TREGLA_DESTROY ), (PHB_DYNS) 1 },
{ "TREGLA_SCROLLDOWN", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TREGLA_SCROLLDOWN ), (PHB_DYNS) 1 },
{ "TREGLA_SCROLLUP", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TREGLA_SCROLLUP ), (PHB_DYNS) 1 },
{ "CREATE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "HCLASS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "__CLSINST", HB_FS_PUBLIC, HB_FUNCNAME( __CLSINST ), NULL },
{ "PCOUNT", HB_FS_PUBLIC, HB_FUNCNAME( PCOUNT ), NULL },
{ "CONSTRUCTORCALL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "HB_APARAMS", HB_FS_PUBLIC, HB_FUNCNAME( HB_APARAMS ), NULL },
{ "GETWNDDEFAULT", HB_FS_PUBLIC, HB_FUNCNAME( GETWNDDEFAULT ), NULL },
{ "GETSYSCOLOR", HB_FS_PUBLIC, HB_FUNCNAME( GETSYSCOLOR ), NULL },
{ "_NTOP", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NLEFT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NBOTTOM", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NTOP", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NRIGHT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NLEFT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_OWND", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NSTYLE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NOR", HB_FS_PUBLIC, HB_FUNCNAME( NOR ), NULL },
{ "_NID", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "GETNEWID", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_LDRAG", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_LCAPTURED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NCLRPANE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NZOOM", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NMIN", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NMAX", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_LHORIZONTAL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NGAP", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_LINCHES", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NMAXDIB", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NMAX", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NMIN", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NMINDIB", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_STEPCM", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_STEPMM", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_OFONT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TFONT", HB_FS_PUBLIC, HB_FUNCNAME( TFONT ), NULL },
{ "_OPEN", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TPEN", HB_FS_PUBLIC, HB_FUNCNAME( TPEN ), NULL },
{ "SETCOLOR", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NCLRTEXT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NCLRPANE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "REGISTER", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "EMPTY", HB_FS_PUBLIC, HB_FUNCNAME( EMPTY ), NULL },
{ "HWND", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ADDCONTROL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "DEFCONTROL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_LUPDATE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "END", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OFONT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OPEN", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "WNDRAISED", HB_FS_PUBLIC, HB_FUNCNAME( WNDRAISED ), NULL },
{ "HDC", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "SELECTOBJECT", HB_FS_PUBLIC, HB_FUNCNAME( SELECTOBJECT ), NULL },
{ "HPEN", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "HFONT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "SETTEXTCOLOR", HB_FS_PUBLIC, HB_FUNCNAME( SETTEXTCOLOR ), NULL },
{ "NCOLOR", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "SETBKCOLOR", HB_FS_PUBLIC, HB_FUNCNAME( SETBKCOLOR ), NULL },
{ "_NPOSMARCA", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "LHORIZONTAL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NHEIGHT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NWIDTH", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "STEPCM", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NMINDIB", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NMAXDIB", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NGAP", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NZOOM", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "PIX2MM", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "MOVETO", HB_FS_PUBLIC, HB_FUNCNAME( MOVETO ), NULL },
{ "NPOSMARCA", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "LINETO", HB_FS_PUBLIC, HB_FUNCNAME( LINETO ), NULL },
{ "STR", HB_FS_PUBLIC, HB_FUNCNAME( STR ), NULL },
{ "TEXTOUT", HB_FS_PUBLIC, HB_FUNCNAME( TEXTOUT ), NULL },
{ "GETWIDTH", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "STEPMM", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "REFRESH", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ERRORSYS", HB_FS_PUBLIC, HB_FUNCNAME( ERRORSYS ), NULL },
{ "(_INITSTATICS)", HB_FS_INIT | HB_FS_EXIT, hb_INITSTATICS, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_TREGLA )

#if defined(HB_STATIC_STARTUP)
   #pragma startup hb_vm_SymbolInit_TREGLA
#elif defined(_MSC_VER)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_TREGLA = hb_vm_SymbolInit_TREGLA;
   #pragma data_seg()
#elif ! defined(__GNUC__)
   #pragma startup hb_vm_SymbolInit_TREGLA
#endif

HB_FUNC( TREGLA )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 2, 255,	/* locals, params */
	HB_P_SFRAME, 99, 0,	/* symbol (_INITSTATICS) */
	HB_P_LOCALNEARSETINT, 2, 1, 0,	/* NSCOPE 1*/
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSE, 104, 3,	/* 872 (abs: 00887) */
	HB_P_MESSAGE, 1, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 2,	/* HBCLASS */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'T', 'R', 'e', 'g', 'l', 'a', 0, 
	HB_P_PUSHSYMNEAR, 3,	/* __CLS_PARAM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'T', 'C', 'o', 'n', 't', 'r', 'o', 'l', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_SENDSHORT, 2,
	HB_P_POPSTATIC, 1, 0,	/* S_OCLASS */
/* 00056 */ HB_P_BASELINE, 19, 0,	/* 19 */
	HB_P_MESSAGE, 4, 0,	/* ADDMULTICLSDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'L', 'O', 'G', 'I', 'C', 'A', 'L', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_ADDINT, 32, 0,	/* 32*/
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'l', 'R', 'e', 'g', 'i', 's', 't', 'e', 'r', 'e', 'd', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_SENDSHORT, 5,
	HB_P_POP,
/* 00102 */ HB_P_LINEOFFSET, 2,	/* 21 */
	HB_P_MESSAGE, 5, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'n', 'C', 'l', 'r', 'P', 'a', 'n', 'e', 0, 
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'n', 'C', 'l', 'r', 'T', 'e', 'x', 't', 0, 
	HB_P_ARRAYGEN, 2, 0,	/* 2 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00144 */ HB_P_LINEOFFSET, 3,	/* 22 */
	HB_P_MESSAGE, 5, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'n', 'Z', 'o', 'o', 'm', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00172 */ HB_P_LINEOFFSET, 4,	/* 23 */
	HB_P_MESSAGE, 5, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	'P', 'i', 'x', '2', 'm', 'm', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00201 */ HB_P_LINEOFFSET, 5,	/* 24 */
	HB_P_MESSAGE, 5, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'n', 'M', 'i', 'n', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'n', 'M', 'a', 'x', 0, 
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'l', 'H', 'o', 'r', 'i', 'z', 'o', 'n', 't', 'a', 'l', 0, 
	HB_P_ARRAYGEN, 3, 0,	/* 3 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00249 */ HB_P_LINEOFFSET, 6,	/* 25 */
	HB_P_MESSAGE, 5, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'n', 'P', 'o', 's', 'M', 'a', 'r', 'c', 'a', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00281 */ HB_P_LINEOFFSET, 7,	/* 26 */
	HB_P_MESSAGE, 5, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'n', 'G', 'a', 'p', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00308 */ HB_P_LINEOFFSET, 8,	/* 27 */
	HB_P_MESSAGE, 5, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'o', 'F', 'o', 'n', 't', 0, 
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'o', 'P', 'e', 'n', 0, 
	HB_P_ARRAYGEN, 2, 0,	/* 2 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00343 */ HB_P_LINEOFFSET, 9,	/* 28 */
	HB_P_MESSAGE, 5, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'l', 'I', 'n', 'c', 'h', 'e', 's', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00373 */ HB_P_LINEOFFSET, 10,	/* 29 */
	HB_P_MESSAGE, 5, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'n', 'M', 'i', 'n', 'D', 'i', 'b', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00403 */ HB_P_LINEOFFSET, 11,	/* 30 */
	HB_P_MESSAGE, 5, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'n', 'M', 'a', 'x', 'D', 'i', 'b', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00433 */ HB_P_LINEOFFSET, 12,	/* 31 */
	HB_P_MESSAGE, 5, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	's', 't', 'e', 'p', 'c', 'm', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00462 */ HB_P_LINEOFFSET, 13,	/* 32 */
	HB_P_MESSAGE, 5, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 7,	/* 7 */
	's', 't', 'e', 'p', 'm', 'm', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00491 */ HB_P_LINEOFFSET, 16,	/* 35 */
	HB_P_MESSAGE, 6, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'N', 'e', 'w', 0, 
	HB_P_PUSHSYMNEAR, 7,	/* TREGLA_NEW */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_ADDINT, 8, 0,	/* 8*/
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00517 */ HB_P_LINEOFFSET, 18,	/* 37 */
	HB_P_MESSAGE, 6, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'R', 'e', 'D', 'e', 'f', 'i', 'n', 'e', 0, 
	HB_P_PUSHSYMNEAR, 8,	/* TREGLA_REDEFINE */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_ADDINT, 8, 0,	/* 8*/
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00548 */ HB_P_LINEOFFSET, 19,	/* 38 */
	HB_P_MESSAGE, 9, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'E', 'n', 'd', 0, 
	HB_P_PUSHBLOCK, 15, 0,	/* 15 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_MESSAGE, 10, 0,	/* DESTROY */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00583 */ HB_P_LINEOFFSET, 21,	/* 40 */
	HB_P_MESSAGE, 9, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'I', 'n', 'i', 't', 'i', 'a', 't', 'e', 0, 
	HB_P_PUSHBLOCK, 22, 0,	/* 22 */
	2, 0,	/* number of local parameters (2) */
	0, 0,	/* number of local variables (0) */
	HB_P_MESSAGE, 11, 0,	/* INITIATE */
	HB_P_MESSAGE, 12, 0,	/* TCONTROL */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 2,	/* codeblockvar2 */
	HB_P_SENDSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00630 */ HB_P_LINEOFFSET, 23,	/* 42 */
	HB_P_MESSAGE, 9, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'D', 'i', 's', 'p', 'l', 'a', 'y', 0, 
	HB_P_PUSHBLOCK, 33, 0,	/* 33 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_MESSAGE, 13, 0,	/* BEGINPAINT */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_MESSAGE, 14, 0,	/* PAINT */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_MESSAGE, 15, 0,	/* ENDPAINT */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_ZERO,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00687 */ HB_P_LINEOFFSET, 25,	/* 44 */
	HB_P_MESSAGE, 6, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 6,	/* 6 */
	'P', 'a', 'i', 'n', 't', 0, 
	HB_P_PUSHSYMNEAR, 16,	/* TREGLA_PAINT */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00712 */ HB_P_LINEOFFSET, 27,	/* 46 */
	HB_P_MESSAGE, 9, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'S', 'e', 't', 'P', 'i', 'x', '2', 'm', 'm', 0, 
	HB_P_PUSHBLOCK, 42, 0,	/* 42 */
	2, 0,	/* number of local parameters (2) */
	0, 0,	/* number of local variables (0) */
	HB_P_MESSAGE, 17, 0,	/* _PIX2MM */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_MESSAGE, 18, 0,	/* LINCHES */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_JUMPFALSENEAR, 18,	/* 18 (abs: 00769) */
	HB_P_PUSHLOCALNEAR, 2,	/* codeblockvar2 */
	HB_P_PUSHDOUBLE, 82, 184, 30, 133, 235, 81, 4, 64, 1, 2,	/* 2.5, 1, 2 */
	HB_P_DIVIDE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00771) */
	HB_P_PUSHLOCALNEAR, 2,	/* codeblockvar2 */
	HB_P_SENDSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00780 */ HB_P_LINEOFFSET, 28,	/* 47 */
	HB_P_MESSAGE, 6, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'D', 'e', 's', 't', 'r', 'o', 'y', 0, 
	HB_P_PUSHSYMNEAR, 19,	/* TREGLA_DESTROY */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00807 */ HB_P_LINEOFFSET, 30,	/* 49 */
	HB_P_MESSAGE, 6, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'S', 'c', 'r', 'o', 'l', 'l', 'D', 'o', 'w', 'n', 0, 
	HB_P_PUSHSYMNEAR, 20,	/* TREGLA_SCROLLDOWN */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00837 */ HB_P_LINEOFFSET, 31,	/* 50 */
	HB_P_MESSAGE, 6, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'S', 'c', 'r', 'o', 'l', 'l', 'U', 'p', 0, 
	HB_P_PUSHSYMNEAR, 21,	/* TREGLA_SCROLLUP */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00865 */ HB_P_LINEOFFSET, 33,	/* 52 */
	HB_P_MESSAGE, 22, 0,	/* CREATE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_MESSAGE, 23, 0,	/* HCLASS */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_SENDSHORT, 0,
	HB_P_CLASSSETMODULE,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00887) */
	HB_P_PUSHSYMNEAR, 24,	/* __CLSINST */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 23, 0,	/* HCLASS */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 1,	/* OCLASSINSTANCE */
	HB_P_PUSHSYMNEAR, 25,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 20,	/* 20 (abs: 00929) */
	HB_P_MESSAGE, 26, 0,	/* CONSTRUCTORCALL */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHLOCALNEAR, 1,	/* OCLASSINSTANCE */
	HB_P_PUSHSYMNEAR, 27,	/* HB_APARAMS */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_SENDSHORT, 2,
	HB_P_POP,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00929) */
	HB_P_PUSHLOCALNEAR, 1,	/* OCLASSINSTANCE */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00933 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TREGLA_NEW )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 16,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 17,	/* SELF */
/* 00006 */ HB_P_BASELINE, 60, 0,	/* 60 */
	HB_P_PUSHLOCALNEAR, 2,	/* NROW */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00018) */
	HB_P_ZERO,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00020) */
	HB_P_PUSHLOCALNEAR, 2,	/* NROW */
	HB_P_POPLOCALNEAR, 2,	/* NROW */
	HB_P_PUSHLOCALNEAR, 3,	/* NCOL */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00031) */
	HB_P_ZERO,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00033) */
	HB_P_PUSHLOCALNEAR, 3,	/* NCOL */
	HB_P_POPLOCALNEAR, 3,	/* NCOL */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 9,	/* 9 (abs: 00048) */
	HB_P_PUSHSYMNEAR, 28,	/* GETWNDDEFAULT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00050) */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_POPLOCALNEAR, 1,	/* OWND */
	HB_P_PUSHLOCALNEAR, 7,	/* NMIN */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00061) */
	HB_P_ZERO,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00063) */
	HB_P_PUSHLOCALNEAR, 7,	/* NMIN */
	HB_P_POPLOCALNEAR, 7,	/* NMIN */
	HB_P_PUSHLOCALNEAR, 8,	/* NMAX */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00075) */
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00077) */
	HB_P_PUSHLOCALNEAR, 8,	/* NMAX */
	HB_P_POPLOCALNEAR, 8,	/* NMAX */
	HB_P_PUSHLOCALNEAR, 9,	/* LHORIZONTAL */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00088) */
	HB_P_TRUE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00090) */
	HB_P_PUSHLOCALNEAR, 9,	/* LHORIZONTAL */
	HB_P_POPLOCALNEAR, 9,	/* LHORIZONTAL */
	HB_P_PUSHLOCALNEAR, 12,	/* LINCHES */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00101) */
	HB_P_FALSE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00103) */
	HB_P_PUSHLOCALNEAR, 12,	/* LINCHES */
	HB_P_POPLOCALNEAR, 12,	/* LINCHES */
	HB_P_PUSHLOCALNEAR, 4,	/* NWIDTH */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00115) */
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00117) */
	HB_P_PUSHLOCALNEAR, 4,	/* NWIDTH */
	HB_P_POPLOCALNEAR, 4,	/* NWIDTH */
	HB_P_PUSHLOCALNEAR, 5,	/* NHEIGHT */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00129) */
	HB_P_PUSHBYTE, 28,	/* 28 */
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00131) */
	HB_P_PUSHLOCALNEAR, 5,	/* NHEIGHT */
	HB_P_POPLOCALNEAR, 5,	/* NHEIGHT */
	HB_P_PUSHLOCALNEAR, 13,	/* NCLRTEXT */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00142) */
	HB_P_ZERO,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00144) */
	HB_P_PUSHLOCALNEAR, 13,	/* NCLRTEXT */
	HB_P_POPLOCALNEAR, 13,	/* NCLRTEXT */
	HB_P_PUSHLOCALNEAR, 14,	/* NCLRBACK */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 00161) */
	HB_P_PUSHSYMNEAR, 29,	/* GETSYSCOLOR */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00163) */
	HB_P_PUSHLOCALNEAR, 14,	/* NCLRBACK */
	HB_P_POPLOCALNEAR, 14,	/* NCLRBACK */
	HB_P_PUSHLOCALNEAR, 15,	/* STEPCM */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00174) */
	HB_P_ONE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00176) */
	HB_P_PUSHLOCALNEAR, 15,	/* STEPCM */
	HB_P_POPLOCALNEAR, 15,	/* STEPCM */
	HB_P_PUSHLOCALNEAR, 16,	/* STEPMM */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00187) */
	HB_P_ONE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00189) */
	HB_P_PUSHLOCALNEAR, 16,	/* STEPMM */
	HB_P_POPLOCALNEAR, 16,	/* STEPMM */
	HB_P_MESSAGE, 30, 0,	/* _NTOP */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_PUSHLOCALNEAR, 6,	/* LPIXEL */
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00204) */
	HB_P_PUSHLOCALNEAR, 2,	/* NROW */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 00209) */
	HB_P_PUSHLOCALNEAR, 2,	/* NROW */
	HB_P_PUSHBYTE, 16,	/* 16 */
	HB_P_MULT,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00212 */ HB_P_LINEOFFSET, 7,	/* 67 */
	HB_P_MESSAGE, 31, 0,	/* _NLEFT */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_PUSHLOCALNEAR, 6,	/* LPIXEL */
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00227) */
	HB_P_PUSHLOCALNEAR, 3,	/* NCOL */
	HB_P_JUMPNEAR, 7,	/* 7 (abs: 00232) */
	HB_P_PUSHLOCALNEAR, 3,	/* NCOL */
	HB_P_PUSHBYTE, 8,	/* 8 */
	HB_P_MULT,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00235 */ HB_P_LINEOFFSET, 8,	/* 68 */
	HB_P_MESSAGE, 32, 0,	/* _NBOTTOM */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_MESSAGE, 33, 0,	/* NTOP */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 5,	/* NHEIGHT */
	HB_P_PLUS,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00255 */ HB_P_LINEOFFSET, 9,	/* 69 */
	HB_P_MESSAGE, 34, 0,	/* _NRIGHT */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_MESSAGE, 35, 0,	/* NLEFT */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 4,	/* NWIDTH */
	HB_P_PLUS,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00275 */ HB_P_LINEOFFSET, 10,	/* 70 */
	HB_P_MESSAGE, 36, 0,	/* _OWND */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00287 */ HB_P_LINEOFFSET, 11,	/* 71 */
	HB_P_MESSAGE, 37, 0,	/* _NSTYLE */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_PUSHSYMNEAR, 38,	/* NOR */
	HB_P_PUSHNIL,
	HB_P_PUSHLONG, 0, 0, 128, 0,	/* 8388608 */
	HB_P_PUSHLONG, 0, 0, 0, 64,	/* 1073741824 */
	HB_P_PUSHLONG, 0, 0, 0, 16,	/* 268435456 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00317 */ HB_P_LINEOFFSET, 12,	/* 72 */
	HB_P_MESSAGE, 39, 0,	/* _NID */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_MESSAGE, 40, 0,	/* GETNEWID */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00334 */ HB_P_LINEOFFSET, 13,	/* 73 */
	HB_P_MESSAGE, 41, 0,	/* _LDRAG */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_FALSE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00345 */ HB_P_LINEOFFSET, 14,	/* 74 */
	HB_P_MESSAGE, 42, 0,	/* _LCAPTURED */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_FALSE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00356 */ HB_P_LINEOFFSET, 15,	/* 75 */
	HB_P_MESSAGE, 43, 0,	/* _NCLRPANE */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_PUSHLOCALNEAR, 14,	/* NCLRBACK */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00368 */ HB_P_LINEOFFSET, 17,	/* 77 */
	HB_P_MESSAGE, 44, 0,	/* _NZOOM */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_PUSHDOUBLE, 0, 0, 0, 0, 0, 0, 240, 63, 1, 1,	/* 1.0, 1, 1 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00389 */ HB_P_LINEOFFSET, 18,	/* 78 */
	HB_P_MESSAGE, 17, 0,	/* _PIX2MM */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_PUSHDOUBLE, 0, 0, 0, 0, 0, 0, 240, 63, 1, 1,	/* 1.0, 1, 1 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00410 */ HB_P_LINEOFFSET, 19,	/* 79 */
	HB_P_MESSAGE, 45, 0,	/* _NMIN */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_PUSHLOCALNEAR, 7,	/* NMIN */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00422 */ HB_P_LINEOFFSET, 20,	/* 80 */
	HB_P_MESSAGE, 46, 0,	/* _NMAX */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_PUSHLOCALNEAR, 8,	/* NMAX */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00434 */ HB_P_LINEOFFSET, 21,	/* 81 */
	HB_P_MESSAGE, 47, 0,	/* _LHORIZONTAL */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_PUSHLOCALNEAR, 9,	/* LHORIZONTAL */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00446 */ HB_P_LINEOFFSET, 22,	/* 82 */
	HB_P_MESSAGE, 48, 0,	/* _NGAP */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00457 */ HB_P_LINEOFFSET, 23,	/* 83 */
	HB_P_MESSAGE, 49, 0,	/* _LINCHES */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_PUSHLOCALNEAR, 12,	/* LINCHES */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00469 */ HB_P_LINEOFFSET, 24,	/* 84 */
	HB_P_MESSAGE, 50, 0,	/* _NMAXDIB */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_MESSAGE, 51, 0,	/* NMAX */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 52, 0,	/* NMIN */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MINUS,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00494 */ HB_P_LINEOFFSET, 25,	/* 85 */
	HB_P_MESSAGE, 53, 0,	/* _NMINDIB */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00505 */ HB_P_LINEOFFSET, 26,	/* 86 */
	HB_P_MESSAGE, 54, 0,	/* _STEPCM */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_PUSHLOCALNEAR, 15,	/* STEPCM */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00517 */ HB_P_LINEOFFSET, 27,	/* 87 */
	HB_P_MESSAGE, 55, 0,	/* _STEPMM */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_PUSHLOCALNEAR, 16,	/* STEPMM */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00529 */ HB_P_LINEOFFSET, 29,	/* 89 */
	HB_P_PUSHLOCALNEAR, 10,	/* OFONT */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 57,	/* 57 (abs: 00592) */
/* 00537 */ HB_P_LINEOFFSET, 30,	/* 90 */
	HB_P_MESSAGE, 56, 0,	/* _OFONT */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_MESSAGE, 1, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 57,	/* TFONT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 14,	/* 14 */
	'M', 'S', ' ', 'S', 'a', 'n', 's', ' ', 'S', 'e', 'r', 'i', 'f', 0, 
	HB_P_ZERO,
	HB_P_PUSHBYTE, 248,	/* -8 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 17,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 14,	/* 14 (abs: 00604) */
/* 00592 */ HB_P_LINEOFFSET, 32,	/* 92 */
	HB_P_MESSAGE, 56, 0,	/* _OFONT */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_PUSHLOCALNEAR, 10,	/* OFONT */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00604 */ HB_P_LINEOFFSET, 35,	/* 95 */
	HB_P_PUSHLOCALNEAR, 11,	/* OPEN */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 29,	/* 29 (abs: 00639) */
/* 00612 */ HB_P_LINEOFFSET, 36,	/* 96 */
	HB_P_MESSAGE, 58, 0,	/* _OPEN */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_MESSAGE, 1, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 59,	/* TPEN */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHLOCALNEAR, 13,	/* NCLRTEXT */
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 4,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 14,	/* 14 (abs: 00651) */
/* 00639 */ HB_P_LINEOFFSET, 38,	/* 98 */
	HB_P_MESSAGE, 58, 0,	/* _OPEN */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_PUSHLOCALNEAR, 11,	/* OPEN */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00651 */ HB_P_LINEOFFSET, 46,	/* 106 */
	HB_P_MESSAGE, 60, 0,	/* SETCOLOR */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_MESSAGE, 61, 0,	/* NCLRTEXT */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 62, 0,	/* NCLRPANE */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 2,
	HB_P_POP,
/* 00675 */ HB_P_LINEOFFSET, 48,	/* 108 */
	HB_P_MESSAGE, 63, 0,	/* REGISTER */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_PUSHSYMNEAR, 38,	/* NOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00693 */ HB_P_LINEOFFSET, 50,	/* 110 */
	HB_P_PUSHSYMNEAR, 64,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 65, 0,	/* HWND */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 26,	/* 26 (abs: 00734) */
/* 00710 */ HB_P_LINEOFFSET, 51,	/* 111 */
	HB_P_MESSAGE, 22, 0,	/* CREATE */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00720 */ HB_P_LINEOFFSET, 52,	/* 112 */
	HB_P_MESSAGE, 66, 0,	/* ADDCONTROL */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 14,	/* 14 (abs: 00746) */
/* 00734 */ HB_P_LINEOFFSET, 54,	/* 114 */
	HB_P_MESSAGE, 67, 0,	/* DEFCONTROL */
	HB_P_PUSHLOCALNEAR, 1,	/* OWND */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00746 */ HB_P_LINEOFFSET, 57,	/* 117 */
	HB_P_PUSHLOCALNEAR, 17,	/* SELF */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00752 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TREGLA_REDEFINE )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 13,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 14,	/* SELF */
/* 00006 */ HB_P_BASELINE, 123, 0,	/* 123 */
	HB_P_PUSHLOCALNEAR, 3,	/* NMIN */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00018) */
	HB_P_ZERO,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00020) */
	HB_P_PUSHLOCALNEAR, 3,	/* NMIN */
	HB_P_POPLOCALNEAR, 3,	/* NMIN */
	HB_P_PUSHLOCALNEAR, 4,	/* NMAX */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00032) */
	HB_P_PUSHBYTE, 100,	/* 100 */
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00034) */
	HB_P_PUSHLOCALNEAR, 4,	/* NMAX */
	HB_P_POPLOCALNEAR, 4,	/* NMAX */
	HB_P_PUSHLOCALNEAR, 5,	/* LHORIZONTAL */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00045) */
	HB_P_TRUE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00047) */
	HB_P_PUSHLOCALNEAR, 5,	/* LHORIZONTAL */
	HB_P_POPLOCALNEAR, 5,	/* LHORIZONTAL */
	HB_P_PUSHLOCALNEAR, 8,	/* LINCHES */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00058) */
	HB_P_FALSE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00060) */
	HB_P_PUSHLOCALNEAR, 8,	/* LINCHES */
	HB_P_POPLOCALNEAR, 8,	/* LINCHES */
	HB_P_PUSHLOCALNEAR, 9,	/* NCLRTEXT */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00071) */
	HB_P_ZERO,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00073) */
	HB_P_PUSHLOCALNEAR, 9,	/* NCLRTEXT */
	HB_P_POPLOCALNEAR, 9,	/* NCLRTEXT */
	HB_P_PUSHLOCALNEAR, 10,	/* NCLRBACK */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 00090) */
	HB_P_PUSHSYMNEAR, 29,	/* GETSYSCOLOR */
	HB_P_PUSHNIL,
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00092) */
	HB_P_PUSHLOCALNEAR, 10,	/* NCLRBACK */
	HB_P_POPLOCALNEAR, 10,	/* NCLRBACK */
	HB_P_PUSHLOCALNEAR, 11,	/* LUPDATE */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00103) */
	HB_P_FALSE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00105) */
	HB_P_PUSHLOCALNEAR, 11,	/* LUPDATE */
	HB_P_POPLOCALNEAR, 11,	/* LUPDATE */
	HB_P_MESSAGE, 39, 0,	/* _NID */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_PUSHLOCALNEAR, 1,	/* NID */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00117 */ HB_P_LINEOFFSET, 6,	/* 129 */
	HB_P_MESSAGE, 36, 0,	/* _OWND */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_PUSHLOCALNEAR, 2,	/* OWND */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00129 */ HB_P_LINEOFFSET, 7,	/* 130 */
	HB_P_MESSAGE, 68, 0,	/* _LUPDATE */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_PUSHLOCALNEAR, 11,	/* LUPDATE */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00141 */ HB_P_LINEOFFSET, 8,	/* 131 */
	HB_P_MESSAGE, 41, 0,	/* _LDRAG */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_FALSE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00152 */ HB_P_LINEOFFSET, 9,	/* 132 */
	HB_P_MESSAGE, 42, 0,	/* _LCAPTURED */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_FALSE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00163 */ HB_P_LINEOFFSET, 10,	/* 133 */
	HB_P_MESSAGE, 43, 0,	/* _NCLRPANE */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_PUSHLOCALNEAR, 10,	/* NCLRBACK */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00175 */ HB_P_LINEOFFSET, 12,	/* 135 */
	HB_P_MESSAGE, 44, 0,	/* _NZOOM */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_PUSHDOUBLE, 0, 0, 0, 0, 0, 0, 240, 63, 1, 1,	/* 1.0, 1, 1 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00196 */ HB_P_LINEOFFSET, 13,	/* 136 */
	HB_P_MESSAGE, 17, 0,	/* _PIX2MM */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_PUSHDOUBLE, 0, 0, 0, 0, 0, 0, 240, 63, 1, 1,	/* 1.0, 1, 1 */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00217 */ HB_P_LINEOFFSET, 14,	/* 137 */
	HB_P_MESSAGE, 45, 0,	/* _NMIN */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_PUSHLOCALNEAR, 3,	/* NMIN */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00229 */ HB_P_LINEOFFSET, 15,	/* 138 */
	HB_P_MESSAGE, 46, 0,	/* _NMAX */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_PUSHLOCALNEAR, 4,	/* NMAX */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00241 */ HB_P_LINEOFFSET, 16,	/* 139 */
	HB_P_MESSAGE, 47, 0,	/* _LHORIZONTAL */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_PUSHLOCALNEAR, 5,	/* LHORIZONTAL */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00253 */ HB_P_LINEOFFSET, 17,	/* 140 */
	HB_P_MESSAGE, 48, 0,	/* _NGAP */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00264 */ HB_P_LINEOFFSET, 18,	/* 141 */
	HB_P_MESSAGE, 49, 0,	/* _LINCHES */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_PUSHLOCALNEAR, 8,	/* LINCHES */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00276 */ HB_P_LINEOFFSET, 19,	/* 142 */
	HB_P_MESSAGE, 50, 0,	/* _NMAXDIB */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_MESSAGE, 51, 0,	/* NMAX */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 52, 0,	/* NMIN */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MINUS,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00301 */ HB_P_LINEOFFSET, 20,	/* 143 */
	HB_P_MESSAGE, 53, 0,	/* _NMINDIB */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00312 */ HB_P_LINEOFFSET, 21,	/* 144 */
	HB_P_MESSAGE, 54, 0,	/* _STEPCM */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_PUSHLOCALNEAR, 12,	/* STEPCM */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00324 */ HB_P_LINEOFFSET, 22,	/* 145 */
	HB_P_MESSAGE, 55, 0,	/* _STEPMM */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_PUSHLOCALNEAR, 13,	/* STEPMM */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00336 */ HB_P_LINEOFFSET, 25,	/* 148 */
	HB_P_PUSHLOCALNEAR, 6,	/* OFONT */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 57,	/* 57 (abs: 00399) */
/* 00344 */ HB_P_LINEOFFSET, 26,	/* 149 */
	HB_P_MESSAGE, 56, 0,	/* _OFONT */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_MESSAGE, 1, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 57,	/* TFONT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 14,	/* 14 */
	'M', 'S', ' ', 'S', 'a', 'n', 's', ' ', 'S', 'e', 'r', 'i', 'f', 0, 
	HB_P_ZERO,
	HB_P_PUSHBYTE, 248,	/* -8 */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 17,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 14,	/* 14 (abs: 00411) */
/* 00399 */ HB_P_LINEOFFSET, 28,	/* 151 */
	HB_P_MESSAGE, 56, 0,	/* _OFONT */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_PUSHLOCALNEAR, 6,	/* OFONT */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00411 */ HB_P_LINEOFFSET, 31,	/* 154 */
	HB_P_PUSHLOCALNEAR, 7,	/* OPEN */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 29,	/* 29 (abs: 00446) */
/* 00419 */ HB_P_LINEOFFSET, 32,	/* 155 */
	HB_P_MESSAGE, 58, 0,	/* _OPEN */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_MESSAGE, 1, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 59,	/* TPEN */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHLOCALNEAR, 9,	/* NCLRTEXT */
	HB_P_PUSHNIL,
	HB_P_SENDSHORT, 4,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 14,	/* 14 (abs: 00458) */
/* 00446 */ HB_P_LINEOFFSET, 34,	/* 157 */
	HB_P_MESSAGE, 58, 0,	/* _OPEN */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_PUSHLOCALNEAR, 7,	/* OPEN */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00458 */ HB_P_LINEOFFSET, 38,	/* 161 */
	HB_P_MESSAGE, 63, 0,	/* REGISTER */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_PUSHSYMNEAR, 38,	/* NOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00476 */ HB_P_LINEOFFSET, 40,	/* 163 */
	HB_P_PUSHLOCALNEAR, 2,	/* OWND */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 16,	/* 16 (abs: 00498) */
/* 00484 */ HB_P_LINEOFFSET, 41,	/* 164 */
	HB_P_MESSAGE, 67, 0,	/* DEFCONTROL */
	HB_P_PUSHLOCALNEAR, 2,	/* OWND */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00498) */
/* 00498 */ HB_P_LINEOFFSET, 44,	/* 167 */
	HB_P_PUSHLOCALNEAR, 14,	/* SELF */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00504 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TREGLA_DESTROY )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 0,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 1,	/* SELF */
/* 00006 */ HB_P_BASELINE, 172, 0,	/* 172 */
	HB_P_MESSAGE, 69, 0,	/* END */
	HB_P_MESSAGE, 70, 0,	/* OFONT */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00022 */ HB_P_LINEOFFSET, 1,	/* 173 */
	HB_P_MESSAGE, 69, 0,	/* END */
	HB_P_MESSAGE, 71, 0,	/* OPEN */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00037 */ HB_P_LINEOFFSET, 3,	/* 175 */
	HB_P_MESSAGE, 69, 0,	/* END */
	HB_P_MESSAGE, 12, 0,	/* TCONTROL */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00052 */ HB_P_LINEOFFSET, 5,	/* 177 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00057 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TREGLA_PAINT )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 10, 0,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 1,	/* SELF */
/* 00006 */ HB_P_BASELINE, 181, 0,	/* 181 */
	HB_P_LOCALNEARSETINT, 3, 1, 0,	/* N 1*/
/* 00013 */ HB_P_LINEOFFSET, 4,	/* 185 */
	HB_P_PUSHSYMNEAR, 72,	/* WNDRAISED */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 65, 0,	/* HWND */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 73, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_DOSHORT, 2,
/* 00034 */ HB_P_LINEOFFSET, 6,	/* 187 */
	HB_P_PUSHSYMNEAR, 74,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 73, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 75, 0,	/* HPEN */
	HB_P_MESSAGE, 71, 0,	/* OPEN */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 2,	/* HOLDPEN */
/* 00062 */ HB_P_LINEOFFSET, 7,	/* 188 */
	HB_P_PUSHSYMNEAR, 74,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 73, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 76, 0,	/* HFONT */
	HB_P_MESSAGE, 70, 0,	/* OFONT */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 8,	/* HOLDFONT */
/* 00090 */ HB_P_LINEOFFSET, 8,	/* 189 */
	HB_P_PUSHSYMNEAR, 77,	/* SETTEXTCOLOR */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 73, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 78, 0,	/* NCOLOR */
	HB_P_MESSAGE, 71, 0,	/* OPEN */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 0,
	HB_P_DOSHORT, 2,
/* 00116 */ HB_P_LINEOFFSET, 9,	/* 190 */
	HB_P_PUSHSYMNEAR, 79,	/* SETBKCOLOR */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 73, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 62, 0,	/* NCLRPANE */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_DOSHORT, 2,
/* 00137 */ HB_P_LINEOFFSET, 10,	/* 191 */
	HB_P_MESSAGE, 80, 0,	/* _NPOSMARCA */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_MESSAGE, 81, 0,	/* LHORIZONTAL */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_JUMPFALSENEAR, 11,	/* 11 (abs: 00162) */
	HB_P_MESSAGE, 82, 0,	/* NHEIGHT */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_JUMPNEAR, 9,	/* 9 (abs: 00169) */
	HB_P_MESSAGE, 83, 0,	/* NWIDTH */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00172 */ HB_P_LINEOFFSET, 11,	/* 192 */
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_MESSAGE, 84, 0,	/* STEPCM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MULT,
	HB_P_PUSHDOUBLE, 0, 0, 0, 0, 0, 0, 240, 63, 1, 1,	/* 1.0, 1, 1 */
	HB_P_MINUS,
	HB_P_POPLOCALNEAR, 10,	/* FINMM */
/* 00198 */ HB_P_LINEOFFSET, 12,	/* 193 */
	HB_P_MESSAGE, 81, 0,	/* LHORIZONTAL */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_JUMPFALSE, 71, 1,	/* 327 (abs: 00534) */
/* 00210 */ HB_P_LINEOFFSET, 13,	/* 194 */
	HB_P_MESSAGE, 85, 0,	/* NMINDIB */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POPLOCALNEAR, 3,	/* N */
	HB_P_PUSHLOCALNEAR, 3,	/* N */
	HB_P_MESSAGE, 86, 0,	/* NMAXDIB */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 84, 0,	/* STEPCM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_FORTEST,
	HB_P_JUMPFALSE, 37, 1,	/* 293 (abs: 00531) */
/* 00241 */ HB_P_LINEOFFSET, 14,	/* 195 */
	HB_P_MESSAGE, 87, 0,	/* NGAP */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 88, 0,	/* NZOOM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MULT,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHLOCALNEAR, 3,	/* N */
	HB_P_MESSAGE, 88, 0,	/* NZOOM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MULT,
	HB_P_MULT,
	HB_P_MESSAGE, 89, 0,	/* PIX2MM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_DIVIDE,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 4,	/* POS */
/* 00282 */ HB_P_LINEOFFSET, 15,	/* 196 */
	HB_P_PUSHSYMNEAR, 90,	/* MOVETO */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 73, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 4,	/* POS */
	HB_P_MESSAGE, 91, 0,	/* NPOSMARCA */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_ADDINT, 253, 255,	/* -3*/
	HB_P_DOSHORT, 3,
/* 00308 */ HB_P_LINEOFFSET, 16,	/* 197 */
	HB_P_PUSHSYMNEAR, 92,	/* LINETO */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 73, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 4,	/* POS */
	HB_P_MESSAGE, 91, 0,	/* NPOSMARCA */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_ADDINT, 246, 255,	/* -10*/
	HB_P_DOSHORT, 3,
/* 00334 */ HB_P_LINEOFFSET, 17,	/* 198 */
	HB_P_PUSHSYMNEAR, 93,	/* STR */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 52, 0,	/* NMIN */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 3,	/* N */
	HB_P_PLUS,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ZERO,
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPLOCALNEAR, 9,	/* TEXTO */
/* 00356 */ HB_P_LINEOFFSET, 18,	/* 199 */
	HB_P_PUSHSYMNEAR, 94,	/* TEXTOUT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 73, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_PUSHLOCALNEAR, 4,	/* POS */
	HB_P_MESSAGE, 95, 0,	/* GETWIDTH */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_PUSHLOCALNEAR, 9,	/* TEXTO */
	HB_P_MESSAGE, 70, 0,	/* OFONT */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 2,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DIVIDE,
	HB_P_MINUS,
	HB_P_PUSHLOCALNEAR, 9,	/* TEXTO */
	HB_P_DOSHORT, 4,
/* 00396 */ HB_P_LINEOFFSET, 19,	/* 200 */
	HB_P_MESSAGE, 96, 0,	/* STEPMM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POPLOCALNEAR, 5,	/* J */
	HB_P_PUSHLOCALNEAR, 5,	/* J */
	HB_P_PUSHLOCALNEAR, 10,	/* FINMM */
	HB_P_MESSAGE, 96, 0,	/* STEPMM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_FORTEST,
	HB_P_JUMPFALSENEAR, 95,	/* 95 (abs: 00514) */
/* 00421 */ HB_P_LINEOFFSET, 20,	/* 201 */
	HB_P_PUSHLOCALNEAR, 4,	/* POS */
	HB_P_PUSHLOCALNEAR, 5,	/* J */
	HB_P_MESSAGE, 88, 0,	/* NZOOM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MULT,
	HB_P_MESSAGE, 89, 0,	/* PIX2MM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_DIVIDE,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 6,	/* POSMM */
/* 00446 */ HB_P_LINEOFFSET, 21,	/* 202 */
	HB_P_PUSHSYMNEAR, 90,	/* MOVETO */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 73, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 6,	/* POSMM */
	HB_P_MESSAGE, 91, 0,	/* NPOSMARCA */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_ADDINT, 253, 255,	/* -3*/
	HB_P_DOSHORT, 3,
/* 00472 */ HB_P_LINEOFFSET, 22,	/* 203 */
	HB_P_PUSHSYMNEAR, 92,	/* LINETO */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 73, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 6,	/* POSMM */
	HB_P_MESSAGE, 91, 0,	/* NPOSMARCA */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_ADDINT, 250, 255,	/* -6*/
	HB_P_DOSHORT, 3,
/* 00498 */ HB_P_LINEOFFSET, 23,	/* 204 */
	HB_P_PUSHLOCALNEAR, 5,	/* J */
	HB_P_MESSAGE, 96, 0,	/* STEPMM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 5,	/* J */
	HB_P_JUMPNEAR, 151,	/* -105 (abs: 00407) */
/* 00514 */ HB_P_LINEOFFSET, 24,	/* 205 */
	HB_P_PUSHLOCALNEAR, 3,	/* N */
	HB_P_MESSAGE, 84, 0,	/* STEPCM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 3,	/* N */
	HB_P_JUMP, 205, 254,	/* -307 (abs: 00221) */
	HB_P_JUMP, 68, 1,	/* 324 (abs: 00855) */
/* 00534 */ HB_P_LINEOFFSET, 26,	/* 207 */
	HB_P_MESSAGE, 85, 0,	/* NMINDIB */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POPLOCALNEAR, 3,	/* N */
	HB_P_PUSHLOCALNEAR, 3,	/* N */
	HB_P_MESSAGE, 86, 0,	/* NMAXDIB */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 84, 0,	/* STEPCM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_FORTEST,
	HB_P_JUMPFALSE, 37, 1,	/* 293 (abs: 00855) */
/* 00565 */ HB_P_LINEOFFSET, 27,	/* 208 */
	HB_P_MESSAGE, 87, 0,	/* NGAP */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 88, 0,	/* NZOOM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MULT,
	HB_P_PUSHBYTE, 10,	/* 10 */
	HB_P_PUSHLOCALNEAR, 3,	/* N */
	HB_P_MESSAGE, 88, 0,	/* NZOOM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MULT,
	HB_P_MULT,
	HB_P_MESSAGE, 89, 0,	/* PIX2MM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_DIVIDE,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 4,	/* POS */
/* 00606 */ HB_P_LINEOFFSET, 28,	/* 209 */
	HB_P_PUSHSYMNEAR, 90,	/* MOVETO */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 73, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 91, 0,	/* NPOSMARCA */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_ADDINT, 253, 255,	/* -3*/
	HB_P_PUSHLOCALNEAR, 4,	/* POS */
	HB_P_DOSHORT, 3,
/* 00632 */ HB_P_LINEOFFSET, 29,	/* 210 */
	HB_P_PUSHSYMNEAR, 92,	/* LINETO */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 73, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 91, 0,	/* NPOSMARCA */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_ADDINT, 246, 255,	/* -10*/
	HB_P_PUSHLOCALNEAR, 4,	/* POS */
	HB_P_DOSHORT, 3,
/* 00658 */ HB_P_LINEOFFSET, 30,	/* 211 */
	HB_P_PUSHSYMNEAR, 93,	/* STR */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 52, 0,	/* NMIN */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 3,	/* N */
	HB_P_PLUS,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_ZERO,
	HB_P_FUNCTIONSHORT, 3,
	HB_P_POPLOCALNEAR, 9,	/* TEXTO */
/* 00680 */ HB_P_LINEOFFSET, 31,	/* 212 */
	HB_P_PUSHSYMNEAR, 94,	/* TEXTOUT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 73, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 4,	/* POS */
	HB_P_MESSAGE, 95, 0,	/* GETWIDTH */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_PUSHLOCALNEAR, 9,	/* TEXTO */
	HB_P_MESSAGE, 70, 0,	/* OFONT */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_SENDSHORT, 2,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_DIVIDE,
	HB_P_MINUS,
	HB_P_PUSHBYTE, 3,	/* 3 */
	HB_P_PUSHLOCALNEAR, 9,	/* TEXTO */
	HB_P_DOSHORT, 4,
/* 00720 */ HB_P_LINEOFFSET, 32,	/* 213 */
	HB_P_MESSAGE, 96, 0,	/* STEPMM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POPLOCALNEAR, 5,	/* J */
	HB_P_PUSHLOCALNEAR, 5,	/* J */
	HB_P_PUSHLOCALNEAR, 10,	/* FINMM */
	HB_P_MESSAGE, 96, 0,	/* STEPMM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_FORTEST,
	HB_P_JUMPFALSENEAR, 95,	/* 95 (abs: 00838) */
/* 00745 */ HB_P_LINEOFFSET, 33,	/* 214 */
	HB_P_PUSHLOCALNEAR, 4,	/* POS */
	HB_P_PUSHLOCALNEAR, 5,	/* J */
	HB_P_MESSAGE, 88, 0,	/* NZOOM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MULT,
	HB_P_MESSAGE, 89, 0,	/* PIX2MM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_DIVIDE,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 6,	/* POSMM */
/* 00770 */ HB_P_LINEOFFSET, 34,	/* 215 */
	HB_P_PUSHSYMNEAR, 90,	/* MOVETO */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 73, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 91, 0,	/* NPOSMARCA */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_ADDINT, 253, 255,	/* -3*/
	HB_P_PUSHLOCALNEAR, 6,	/* POSMM */
	HB_P_DOSHORT, 3,
/* 00796 */ HB_P_LINEOFFSET, 35,	/* 216 */
	HB_P_PUSHSYMNEAR, 92,	/* LINETO */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 73, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 91, 0,	/* NPOSMARCA */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_ADDINT, 250, 255,	/* -6*/
	HB_P_PUSHLOCALNEAR, 6,	/* POSMM */
	HB_P_DOSHORT, 3,
/* 00822 */ HB_P_LINEOFFSET, 36,	/* 217 */
	HB_P_PUSHLOCALNEAR, 5,	/* J */
	HB_P_MESSAGE, 96, 0,	/* STEPMM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 5,	/* J */
	HB_P_JUMPNEAR, 151,	/* -105 (abs: 00731) */
/* 00838 */ HB_P_LINEOFFSET, 37,	/* 218 */
	HB_P_PUSHLOCALNEAR, 3,	/* N */
	HB_P_MESSAGE, 84, 0,	/* STEPCM */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PLUS,
	HB_P_POPLOCALNEAR, 3,	/* N */
	HB_P_JUMP, 205, 254,	/* -307 (abs: 00545) */
/* 00855 */ HB_P_LINEOFFSET, 39,	/* 220 */
	HB_P_PUSHSYMNEAR, 74,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 73, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 2,	/* HOLDPEN */
	HB_P_DOSHORT, 2,
/* 00871 */ HB_P_LINEOFFSET, 40,	/* 221 */
	HB_P_PUSHSYMNEAR, 74,	/* SELECTOBJECT */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 73, 0,	/* HDC */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 8,	/* HOLDFONT */
	HB_P_DOSHORT, 2,
/* 00887 */ HB_P_LINEOFFSET, 42,	/* 223 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00892 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TREGLA_SCROLLUP )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 1,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 2,	/* SELF */
/* 00006 */ HB_P_BASELINE, 228, 0,	/* 228 */
	HB_P_MESSAGE, 48, 0,	/* _NGAP */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_MESSAGE, 87, 0,	/* NGAP */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 1,	/* NPIXELS */
	HB_P_MINUS,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00027 */ HB_P_LINEOFFSET, 1,	/* 229 */
	HB_P_MESSAGE, 97, 0,	/* REFRESH */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00037 */ HB_P_LINEOFFSET, 3,	/* 231 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00042 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TREGLA_SCROLLDOWN )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 1,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 2,	/* SELF */
/* 00006 */ HB_P_BASELINE, 235, 0,	/* 235 */
	HB_P_MESSAGE, 48, 0,	/* _NGAP */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_MESSAGE, 87, 0,	/* NGAP */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 1,	/* NPIXELS */
	HB_P_PLUS,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00027 */ HB_P_LINEOFFSET, 1,	/* 236 */
	HB_P_MESSAGE, 97, 0,	/* REFRESH */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00037 */ HB_P_LINEOFFSET, 3,	/* 238 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00042 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

static HARBOUR hb_INITSTATICS( void )
{
   static const BYTE pcode[] =
   {
	HB_P_STATICS, 99, 0, 1, 0,	/* symbol (_INITSTATICS), 1 statics */
	HB_P_ENDPROC
/* 00006 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

