/*
 * xHarbour Compiler, build 82.0 (SimpLex)
 * Generated C source code from <c:/EDUCAR/program/vbxctrl.prg>
 */

#include "hbvmpub.h"
#include "hbpcode.h"
#include "hbinit.h"

#define __PRG_SOURCE__ "c:/EDUCAR/program/vbxctrl.prg"

HB_FUNC( TVBCONTROL );
HB_FUNC_STATIC( TVBCONTROL_NEW );
HB_FUNC_STATIC( TVBCONTROL_REDEFINE );
HB_FUNC_STATIC( TVBCONTROL_INITIATE );
HB_FUNC_STATIC( TVBCONTROL_INITEVENTS );
HB_FUNC_STATIC( TVBCONTROL_AGETPROPS );
HB_FUNC_STATIC( TVBCONTROL_HANDLEEVENT );
HB_FUNC_STATIC( TVBCONTROL_DEFAULT );
HB_FUNC_STATIC( TVBCONTROL_VBXINHERIT );
HB_FUNC_STATIC( BGETPROP );
HB_FUNC_STATIC( BSETPROP );
HB_FUNC_STATIC( BARRAYPROP );

static HARBOUR hb_INITSTATICS( void );

extern HB_FUNC( HBCLASS );
extern HB_FUNC( __CLS_PARAM );
extern HB_FUNC( VBXGETPRPNAME );
extern HB_FUNC( VBXSETPROP );
extern HB_FUNC( GETCLASSNAME );
extern HB_FUNC( VBXGETNUMPROPS );
extern HB_FUNC( VBXGETNUMEVENTS );
extern HB_FUNC( VBXGETEVENAME );
extern HB_FUNC( VBXGETENUMS );
extern HB_FUNC( VBXGETPRPBYNAME );
extern HB_FUNC( VBXSETPRPBYNAME );
extern HB_FUNC( VBXGETPROP );
extern HB_FUNC( VBXGETPRPTYPE );
extern HB_FUNC( __VBXEVENT );
extern HB_FUNC( __CLSINST );
extern HB_FUNC( PCOUNT );
extern HB_FUNC( HB_APARAMS );
extern HB_FUNC( GETWNDDEFAULT );
extern HB_FUNC( UPPER );
extern HB_FUNC( SUBSTR );
extern HB_FUNC( AT );
extern HB_FUNC( NOR );
extern HB_FUNC( EMPTY );
extern HB_FUNC( FILE );
extern HB_FUNC( VBXCREATE );
extern HB_FUNC( MSGALERT );
extern HB_FUNC( VBXGETHWND );
extern HB_FUNC( VBXGETHCTL );
extern HB_FUNC( STR );
extern HB_FUNC( AADD );
extern HB_FUNC( VBXINIT );
extern HB_FUNC( GETRESOURCES );
extern HB_FUNC( REGISTERCLASS );
extern HB_FUNC( SET );
extern HB_FUNC( _OBJNEWCLS );
extern HB_FUNC( ARRAY );
extern HB_FUNC( ASORT );
extern HB_FUNC( SETCLSHANDLE );
extern HB_FUNC( _CLASSHANDLE );
extern HB_FUNC( LEN );
extern HB_FUNC( ASCAN );
extern HB_FUNC( TVBXARRAY );
extern HB_FUNC( ERRORSYS );
extern HB_FUNC( TCONTROL );

#undef HB_PRG_PCODE_VER
#define HB_PRG_PCODE_VER 5

HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_VBXCTRL )
{ "TVBCONTROL", HB_FS_PUBLIC | HB_FS_FIRST, HB_FUNCNAME( TVBCONTROL ), (PHB_DYNS) 1 },
{ "NEW", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "HBCLASS", HB_FS_PUBLIC, HB_FUNCNAME( HBCLASS ), NULL },
{ "__CLS_PARAM", HB_FS_PUBLIC, HB_FUNCNAME( __CLS_PARAM ), NULL },
{ "ADDMULTICLSDATA", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ADDMULTIDATA", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ADDMETHOD", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TVBCONTROL_NEW", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TVBCONTROL_NEW ), (PHB_DYNS) 1 },
{ "TVBCONTROL_REDEFINE", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TVBCONTROL_REDEFINE ), (PHB_DYNS) 1 },
{ "TVBCONTROL_INITIATE", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TVBCONTROL_INITIATE ), (PHB_DYNS) 1 },
{ "TVBCONTROL_INITEVENTS", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TVBCONTROL_INITEVENTS ), (PHB_DYNS) 1 },
{ "ADDINLINE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "VBXGETPRPNAME", HB_FS_PUBLIC, HB_FUNCNAME( VBXGETPRPNAME ), NULL },
{ "HCTL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TVBCONTROL_AGETPROPS", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TVBCONTROL_AGETPROPS ), (PHB_DYNS) 1 },
{ "TVBCONTROL_DEFAULT", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TVBCONTROL_DEFAULT ), (PHB_DYNS) 1 },
{ "VBXSETPROP", HB_FS_PUBLIC, HB_FUNCNAME( VBXSETPROP ), NULL },
{ "GETCLASSNAME", HB_FS_PUBLIC, HB_FUNCNAME( GETCLASSNAME ), NULL },
{ "HWND", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "VBXGETNUMPROPS", HB_FS_PUBLIC, HB_FUNCNAME( VBXGETNUMPROPS ), NULL },
{ "VBXGETNUMEVENTS", HB_FS_PUBLIC, HB_FUNCNAME( VBXGETNUMEVENTS ), NULL },
{ "VBXGETEVENAME", HB_FS_PUBLIC, HB_FUNCNAME( VBXGETEVENAME ), NULL },
{ "VBXGETENUMS", HB_FS_PUBLIC, HB_FUNCNAME( VBXGETENUMS ), NULL },
{ "VBXGETPRPBYNAME", HB_FS_PUBLIC, HB_FUNCNAME( VBXGETPRPBYNAME ), NULL },
{ "VBXSETPRPBYNAME", HB_FS_PUBLIC, HB_FUNCNAME( VBXSETPRPBYNAME ), NULL },
{ "VBXGETPROP", HB_FS_PUBLIC, HB_FUNCNAME( VBXGETPROP ), NULL },
{ "VBXGETPRPTYPE", HB_FS_PUBLIC, HB_FUNCNAME( VBXGETPRPTYPE ), NULL },
{ "TVBCONTROL_HANDLEEVENT", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TVBCONTROL_HANDLEEVENT ), (PHB_DYNS) 1 },
{ "__VBXEVENT", HB_FS_PUBLIC, HB_FUNCNAME( __VBXEVENT ), NULL },
{ "TVBCONTROL_VBXINHERIT", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( TVBCONTROL_VBXINHERIT ), (PHB_DYNS) 1 },
{ "CTOCHAR", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "TCONTROL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, HB_FUNCNAME( TCONTROL ), NULL },
{ "CREATE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "HCLASS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "__CLSINST", HB_FS_PUBLIC, HB_FUNCNAME( __CLSINST ), NULL },
{ "PCOUNT", HB_FS_PUBLIC, HB_FUNCNAME( PCOUNT ), NULL },
{ "CONSTRUCTORCALL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "HB_APARAMS", HB_FS_PUBLIC, HB_FUNCNAME( HB_APARAMS ), NULL },
{ "GETWNDDEFAULT", HB_FS_PUBLIC, HB_FUNCNAME( GETWNDDEFAULT ), NULL },
{ "UPPER", HB_FS_PUBLIC, HB_FUNCNAME( UPPER ), NULL },
{ "SUBSTR", HB_FS_PUBLIC, HB_FUNCNAME( SUBSTR ), NULL },
{ "AT", HB_FS_PUBLIC, HB_FUNCNAME( AT ), NULL },
{ "_NTOP", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NLEFT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NBOTTOM", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NRIGHT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_OWND", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_CCAPTION", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NSTYLE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NOR", HB_FS_PUBLIC, HB_FUNCNAME( NOR ), NULL },
{ "_LDRAG", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_AEVENTS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_BWHEN", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_BVALID", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "DEFAULT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "EMPTY", HB_FS_PUBLIC, HB_FUNCNAME( EMPTY ), NULL },
{ "FILE", HB_FS_PUBLIC, HB_FUNCNAME( FILE ), NULL },
{ "_HCTL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "VBXCREATE", HB_FS_PUBLIC, HB_FUNCNAME( VBXCREATE ), NULL },
{ "GETNEWID", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "CCAPTION", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NSTYLE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NLEFT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NTOP", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "MSGALERT", HB_FS_PUBLIC, HB_FUNCNAME( MSGALERT ), NULL },
{ "_HWND", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "VBXGETHWND", HB_FS_PUBLIC, HB_FUNCNAME( VBXGETHWND ), NULL },
{ "LINK", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "VBXINHERIT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ADDCONTROL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "DEFCONTROL", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "CHECKDOTS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_NID", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "SETCOLOR", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "INITIATE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "VBXGETHCTL", HB_FS_PUBLIC, HB_FUNCNAME( VBXGETHCTL ), NULL },
{ "STR", HB_FS_PUBLIC, HB_FUNCNAME( STR ), NULL },
{ "NID", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NGETEVENTS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "AADD", HB_FS_PUBLIC, HB_FUNCNAME( AADD ), NULL },
{ "GETEVENT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "_AEVENTNAMES", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NGETPROPS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "CGETPROP", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "VBXEVENT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "AEVENTS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "HANDLEEVENT", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "LREGISTERED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "VBXINIT", HB_FS_PUBLIC, HB_FUNCNAME( VBXINIT ), NULL },
{ "GETRESOURCES", HB_FS_PUBLIC, HB_FUNCNAME( GETRESOURCES ), NULL },
{ "_LREGISTERED", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "REGISTERCLASS", HB_FS_PUBLIC, HB_FUNCNAME( REGISTERCLASS ), NULL },
{ "_LVBX", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "OWND", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "SET", HB_FS_PUBLIC, HB_FUNCNAME( SET ), NULL },
{ "_OBJNEWCLS", HB_FS_PUBLIC, HB_FUNCNAME( _OBJNEWCLS ), NULL },
{ "GETNAME", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "S_OCLASS", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "NSCOPE", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ARRAY", HB_FS_PUBLIC, HB_FUNCNAME( ARRAY ), NULL },
{ "GETPROPNAME", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "ASORT", HB_FS_PUBLIC, HB_FUNCNAME( ASORT ), NULL },
{ "SETCLSHANDLE", HB_FS_PUBLIC, HB_FUNCNAME( SETCLSHANDLE ), NULL },
{ "_CLASSHANDLE", HB_FS_PUBLIC, HB_FUNCNAME( _CLASSHANDLE ), NULL },
{ "LEN", HB_FS_PUBLIC, HB_FUNCNAME( LEN ), NULL },
{ "ASCAN", HB_FS_PUBLIC, HB_FUNCNAME( ASCAN ), NULL },
{ "AEVENTNAMES", HB_FS_PUBLIC | HB_FS_MEMVAR | HB_FS_MESSAGE, NULL, NULL },
{ "BGETPROP", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( BGETPROP ), (PHB_DYNS) 1 },
{ "BSETPROP", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( BSETPROP ), (PHB_DYNS) 1 },
{ "BARRAYPROP", HB_FS_STATIC | HB_FS_PUBLIC, HB_FUNCNAME( BARRAYPROP ), (PHB_DYNS) 1 },
{ "TVBXARRAY", HB_FS_PUBLIC, HB_FUNCNAME( TVBXARRAY ), NULL },
{ "ERRORSYS", HB_FS_PUBLIC, HB_FUNCNAME( ERRORSYS ), NULL },
{ "(_INITSTATICS)", HB_FS_INIT | HB_FS_EXIT, hb_INITSTATICS, NULL }
HB_INIT_SYMBOLS_END( hb_vm_SymbolInit_VBXCTRL )

#if defined(HB_STATIC_STARTUP)
   #pragma startup hb_vm_SymbolInit_VBXCTRL
#elif defined(_MSC_VER)
   #if _MSC_VER >= 1010
      #pragma data_seg( ".CRT$XIY" )
      #pragma comment( linker, "/Merge:.CRT=.data" )
   #else
      #pragma data_seg( "XIY" )
   #endif
   static HB_$INITSYM hb_vm_auto_SymbolInit_VBXCTRL = hb_vm_SymbolInit_VBXCTRL;
   #pragma data_seg()
#elif ! defined(__GNUC__)
   #pragma startup hb_vm_SymbolInit_VBXCTRL
#endif

HB_FUNC( TVBCONTROL )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 2, 255,	/* locals, params */
	HB_P_SFRAME, 112, 0,	/* symbol (_INITSTATICS) */
	HB_P_LOCALNEARSETINT, 2, 1, 0,	/* NSCOPE 1*/
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSE, 45, 4,	/* 1069 (abs: 01084) */
	HB_P_MESSAGE, 1, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 2,	/* HBCLASS */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'T', 'V', 'b', 'C', 'o', 'n', 't', 'r', 'o', 'l', 0, 
	HB_P_PUSHSYMNEAR, 3,	/* __CLS_PARAM */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'T', 'C', 'o', 'n', 't', 'r', 'o', 'l', 0, 
	HB_P_FUNCTIONSHORT, 1,
	HB_P_SENDSHORT, 2,
	HB_P_POPSTATIC, 1, 0,	/* S_OCLASS */
/* 00060 */ HB_P_BASELINE, 12, 0,	/* 12 */
	HB_P_MESSAGE, 4, 0,	/* ADDMULTICLSDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_ADDINT, 32, 0,	/* 32*/
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'a', 'E', 'v', 'e', 'n', 't', 'N', 'a', 'm', 'e', 's', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_SENDSHORT, 5,
	HB_P_POP,
/* 00097 */ HB_P_LINEOFFSET, 1,	/* 13 */
	HB_P_MESSAGE, 4, 0,	/* ADDMULTICLSDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'L', 'O', 'G', 'I', 'C', 'A', 'L', 0, 
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_ADDINT, 32, 0,	/* 32*/
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'l', 'R', 'e', 'g', 'i', 's', 't', 'e', 'r', 'e', 'd', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_SENDSHORT, 5,
	HB_P_POP,
/* 00142 */ HB_P_LINEOFFSET, 3,	/* 15 */
	HB_P_MESSAGE, 5, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 5,	/* 5 */
	'h', 'C', 't', 'l', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00169 */ HB_P_LINEOFFSET, 4,	/* 16 */
	HB_P_MESSAGE, 5, 0,	/* ADDMULTIDATA */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'a', 'E', 'v', 'e', 'n', 't', 's', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_FALSE,
	HB_P_SENDSHORT, 6,
	HB_P_POP,
/* 00199 */ HB_P_LINEOFFSET, 7,	/* 19 */
	HB_P_MESSAGE, 6, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'N', 'e', 'w', 0, 
	HB_P_PUSHSYMNEAR, 7,	/* TVBCONTROL_NEW */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_ADDINT, 8, 0,	/* 8*/
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00225 */ HB_P_LINEOFFSET, 10,	/* 22 */
	HB_P_MESSAGE, 6, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'R', 'e', 'D', 'e', 'f', 'i', 'n', 'e', 0, 
	HB_P_PUSHSYMNEAR, 8,	/* TVBCONTROL_REDEFINE */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_ADDINT, 8, 0,	/* 8*/
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00256 */ HB_P_LINEOFFSET, 12,	/* 24 */
	HB_P_MESSAGE, 6, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'I', 'n', 'i', 't', 'i', 'a', 't', 'e', 0, 
	HB_P_PUSHSYMNEAR, 9,	/* TVBCONTROL_INITIATE */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00284 */ HB_P_LINEOFFSET, 14,	/* 26 */
	HB_P_MESSAGE, 6, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'I', 'n', 'i', 't', 'E', 'v', 'e', 'n', 't', 's', 0, 
	HB_P_PUSHSYMNEAR, 10,	/* TVBCONTROL_INITEVENTS */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00314 */ HB_P_LINEOFFSET, 16,	/* 28 */
	HB_P_MESSAGE, 11, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'G', 'e', 't', 'P', 'r', 'o', 'p', 'N', 'a', 'm', 'e', 0, 
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	2, 0,	/* number of local parameters (2) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 12,	/* VBXGETPRPNAME */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 13, 0,	/* HCTL */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 2,	/* codeblockvar2 */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_FUNCTIONSHORT, 2,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00367 */ HB_P_LINEOFFSET, 18,	/* 30 */
	HB_P_MESSAGE, 6, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'a', 'G', 'e', 't', 'P', 'r', 'o', 'p', 's', 0, 
	HB_P_PUSHSYMNEAR, 14,	/* TVBCONTROL_AGETPROPS */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00396 */ HB_P_LINEOFFSET, 20,	/* 32 */
	HB_P_MESSAGE, 6, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'D', 'e', 'f', 'a', 'u', 'l', 't', 0, 
	HB_P_PUSHSYMNEAR, 15,	/* TVBCONTROL_DEFAULT */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00423 */ HB_P_LINEOFFSET, 22,	/* 34 */
	HB_P_MESSAGE, 11, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'S', 'e', 't', 'P', 'r', 'o', 'p', 0, 
	HB_P_PUSHBLOCK, 27, 0,	/* 27 */
	3, 0,	/* number of local parameters (3) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 16,	/* VBXSETPROP */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 13, 0,	/* HCTL */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 2,	/* codeblockvar2 */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_PUSHLOCALNEAR, 3,	/* codeblockvar3 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00474 */ HB_P_LINEOFFSET, 24,	/* 36 */
	HB_P_MESSAGE, 11, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'G', 'e', 't', 'N', 'a', 'm', 'e', 0, 
	HB_P_PUSHBLOCK, 20, 0,	/* 20 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 17,	/* GETCLASSNAME */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 18, 0,	/* HWND */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00518 */ HB_P_LINEOFFSET, 26,	/* 38 */
	HB_P_MESSAGE, 11, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'n', 'G', 'e', 't', 'P', 'r', 'o', 'p', 's', 0, 
	HB_P_PUSHBLOCK, 20, 0,	/* 20 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 19,	/* VBXGETNUMPROPS */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 13, 0,	/* HCTL */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00564 */ HB_P_LINEOFFSET, 28,	/* 40 */
	HB_P_MESSAGE, 11, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'n', 'G', 'e', 't', 'E', 'v', 'e', 'n', 't', 's', 0, 
	HB_P_PUSHBLOCK, 20, 0,	/* 20 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 20,	/* VBXGETNUMEVENTS */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 13, 0,	/* HCTL */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00611 */ HB_P_LINEOFFSET, 30,	/* 42 */
	HB_P_MESSAGE, 11, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'G', 'e', 't', 'E', 'v', 'e', 'n', 't', 0, 
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	2, 0,	/* number of local parameters (2) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 21,	/* VBXGETEVENAME */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 13, 0,	/* HCTL */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 2,	/* codeblockvar2 */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_FUNCTIONSHORT, 2,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00661 */ HB_P_LINEOFFSET, 32,	/* 44 */
	HB_P_MESSAGE, 11, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 9,	/* 9 */
	'G', 'e', 't', 'E', 'n', 'u', 'm', 's', 0, 
	HB_P_PUSHBLOCK, 22, 0,	/* 22 */
	2, 0,	/* number of local parameters (2) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 22,	/* VBXGETENUMS */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 13, 0,	/* HCTL */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 2,	/* codeblockvar2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00708 */ HB_P_LINEOFFSET, 34,	/* 46 */
	HB_P_MESSAGE, 11, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'G', 'e', 't', 0, 
	HB_P_PUSHBLOCK, 22, 0,	/* 22 */
	2, 0,	/* number of local parameters (2) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 23,	/* VBXGETPRPBYNAME */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 13, 0,	/* HCTL */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 2,	/* codeblockvar2 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00750 */ HB_P_LINEOFFSET, 37,	/* 49 */
	HB_P_MESSAGE, 11, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 4,	/* 4 */
	'S', 'e', 't', 0, 
	HB_P_PUSHBLOCK, 24, 0,	/* 24 */
	3, 0,	/* number of local parameters (3) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 24,	/* VBXSETPRPBYNAME */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 13, 0,	/* HCTL */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 2,	/* codeblockvar2 */
	HB_P_PUSHLOCALNEAR, 3,	/* codeblockvar3 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00794 */ HB_P_LINEOFFSET, 39,	/* 51 */
	HB_P_MESSAGE, 11, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'G', 'e', 't', 'P', 'r', 'o', 'p', 0, 
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	2, 0,	/* number of local parameters (2) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 25,	/* VBXGETPROP */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 13, 0,	/* HCTL */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 2,	/* codeblockvar2 */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_FUNCTIONSHORT, 2,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00843 */ HB_P_LINEOFFSET, 41,	/* 53 */
	HB_P_MESSAGE, 11, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'G', 'e', 't', 'P', 'r', 'o', 'p', 'T', 'y', 'p', 'e', 0, 
	HB_P_PUSHBLOCK, 25, 0,	/* 25 */
	2, 0,	/* number of local parameters (2) */
	0, 0,	/* number of local variables (0) */
	HB_P_PUSHSYMNEAR, 26,	/* VBXGETPRPTYPE */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 13, 0,	/* HCTL */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 2,	/* codeblockvar2 */
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_FUNCTIONSHORT, 2,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00896 */ HB_P_LINEOFFSET, 43,	/* 55 */
	HB_P_MESSAGE, 6, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'H', 'a', 'n', 'd', 'l', 'e', 'E', 'v', 'e', 'n', 't', 0, 
	HB_P_PUSHSYMNEAR, 27,	/* TVBCONTROL_HANDLEEVENT */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00927 */ HB_P_LINEOFFSET, 45,	/* 57 */
	HB_P_MESSAGE, 6, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 30,	/* 30 */
	'V', 'b', 'x', 'E', 'v', 'e', 'n', 't', '(', 'h', 'C', 't', 'l', ',', 'b', 'E', 'v', 'e', 'n', 't', ',', 'c', 'E', 'v', 'e', 'n', 't', ' ', ')', 0, 
	HB_P_PUSHSYMNEAR, 28,	/* __VBXEVENT */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 00976 */ HB_P_LINEOFFSET, 47,	/* 59 */
	HB_P_MESSAGE, 6, 0,	/* ADDMETHOD */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 11,	/* 11 */
	'V', 'b', 'x', 'I', 'n', 'h', 'e', 'r', 'i', 't', 0, 
	HB_P_PUSHSYMNEAR, 29,	/* TVBCONTROL_VBXINHERIT */
	HB_P_FUNCPTR,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 01006 */ HB_P_LINEOFFSET, 49,	/* 61 */
	HB_P_MESSAGE, 11, 0,	/* ADDINLINE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHSTRSHORT, 8,	/* 8 */
	'c', 'T', 'o', 'C', 'h', 'a', 'r', 0, 
	HB_P_PUSHBLOCK, 32, 0,	/* 32 */
	1, 0,	/* number of local parameters (1) */
	0, 0,	/* number of local variables (0) */
	HB_P_MESSAGE, 30, 0,	/* CTOCHAR */
	HB_P_MESSAGE, 31, 0,	/* TCONTROL */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'V', 'B', 'C', 'O', 'N', 'T', 'R', 'O', 'L', 0, 
	HB_P_SENDSHORT, 1,
	HB_P_ENDBLOCK,
	HB_P_PUSHLOCALNEAR, 2,	/* NSCOPE */
	HB_P_FALSE,
	HB_P_SENDSHORT, 4,
	HB_P_POP,
/* 01062 */ HB_P_LINEOFFSET, 51,	/* 63 */
	HB_P_MESSAGE, 32, 0,	/* CREATE */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_MESSAGE, 33, 0,	/* HCLASS */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_SENDSHORT, 0,
	HB_P_CLASSSETMODULE,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 01084) */
	HB_P_PUSHSYMNEAR, 34,	/* __CLSINST */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 33, 0,	/* HCLASS */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 1,	/* OCLASSINSTANCE */
	HB_P_PUSHSYMNEAR, 35,	/* PCOUNT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 20,	/* 20 (abs: 01126) */
	HB_P_MESSAGE, 36, 0,	/* CONSTRUCTORCALL */
	HB_P_PUSHSTATIC, 1, 0,	/* S_OCLASS */
	HB_P_PUSHLOCALNEAR, 1,	/* OCLASSINSTANCE */
	HB_P_PUSHSYMNEAR, 37,	/* HB_APARAMS */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_SENDSHORT, 2,
	HB_P_POP,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 01126) */
	HB_P_PUSHLOCALNEAR, 1,	/* OCLASSINSTANCE */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 01130 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TVBCONTROL_NEW )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 12,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 13,	/* SELF */
/* 00006 */ HB_P_BASELINE, 72, 0,	/* 72 */
	HB_P_PUSHLOCALNEAR, 3,	/* NWIDTH */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00019) */
	HB_P_PUSHBYTE, 60,	/* 60 */
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00021) */
	HB_P_PUSHLOCALNEAR, 3,	/* NWIDTH */
	HB_P_POPLOCALNEAR, 3,	/* NWIDTH */
	HB_P_PUSHLOCALNEAR, 4,	/* NHEIGHT */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 6,	/* 6 (abs: 00033) */
	HB_P_PUSHBYTE, 60,	/* 60 */
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00035) */
	HB_P_PUSHLOCALNEAR, 4,	/* NHEIGHT */
	HB_P_POPLOCALNEAR, 4,	/* NHEIGHT */
	HB_P_PUSHLOCALNEAR, 5,	/* OWND */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 9,	/* 9 (abs: 00050) */
	HB_P_PUSHSYMNEAR, 38,	/* GETWNDDEFAULT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00052) */
	HB_P_PUSHLOCALNEAR, 5,	/* OWND */
	HB_P_POPLOCALNEAR, 5,	/* OWND */
	HB_P_PUSHLOCALNEAR, 7,	/* CVBXCLASS */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 31,	/* 31 (abs: 00089) */
	HB_P_PUSHSYMNEAR, 39,	/* UPPER */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 40,	/* SUBSTR */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 6,	/* CVBXFILE */
	HB_P_ONE,
	HB_P_PUSHSYMNEAR, 41,	/* AT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 2,	/* 2 */
	'.', 0, 
	HB_P_PUSHLOCALNEAR, 6,	/* CVBXFILE */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00091) */
	HB_P_PUSHLOCALNEAR, 7,	/* CVBXCLASS */
	HB_P_POPLOCALNEAR, 7,	/* CVBXCLASS */
	HB_P_PUSHLOCALNEAR, 8,	/* AEVENTS */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00104) */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00106) */
	HB_P_PUSHLOCALNEAR, 8,	/* AEVENTS */
	HB_P_POPLOCALNEAR, 8,	/* AEVENTS */
	HB_P_PUSHLOCALNEAR, 11,	/* LPIXEL */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00117) */
	HB_P_FALSE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00119) */
	HB_P_PUSHLOCALNEAR, 11,	/* LPIXEL */
	HB_P_POPLOCALNEAR, 11,	/* LPIXEL */
	HB_P_PUSHLOCALNEAR, 12,	/* LDESIGN */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00130) */
	HB_P_FALSE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00132) */
	HB_P_PUSHLOCALNEAR, 12,	/* LDESIGN */
	HB_P_POPLOCALNEAR, 12,	/* LDESIGN */
	HB_P_MESSAGE, 42, 0,	/* _NTOP */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_PUSHLOCALNEAR, 1,	/* NROW */
	HB_P_PUSHLOCALNEAR, 11,	/* LPIXEL */
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00148) */
	HB_P_ONE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00150) */
	HB_P_PUSHBYTE, 15,	/* 15 */
	HB_P_MULT,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00154 */ HB_P_LINEOFFSET, 3,	/* 75 */
	HB_P_MESSAGE, 43, 0,	/* _NLEFT */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_PUSHLOCALNEAR, 2,	/* NCOL */
	HB_P_PUSHLOCALNEAR, 11,	/* LPIXEL */
	HB_P_JUMPFALSENEAR, 5,	/* 5 (abs: 00170) */
	HB_P_ONE,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00172) */
	HB_P_PUSHBYTE, 6,	/* 6 */
	HB_P_MULT,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00176 */ HB_P_LINEOFFSET, 4,	/* 76 */
	HB_P_MESSAGE, 44, 0,	/* _NBOTTOM */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_PUSHLOCALNEAR, 1,	/* NROW */
	HB_P_PUSHLOCALNEAR, 4,	/* NHEIGHT */
	HB_P_PLUS,
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00194 */ HB_P_LINEOFFSET, 5,	/* 77 */
	HB_P_MESSAGE, 45, 0,	/* _NRIGHT */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_PUSHLOCALNEAR, 2,	/* NCOL */
	HB_P_PUSHLOCALNEAR, 3,	/* NWIDTH */
	HB_P_PLUS,
	HB_P_ADDINT, 255, 255,	/* -1*/
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00212 */ HB_P_LINEOFFSET, 6,	/* 78 */
	HB_P_MESSAGE, 46, 0,	/* _OWND */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_PUSHLOCALNEAR, 5,	/* OWND */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00224 */ HB_P_LINEOFFSET, 7,	/* 79 */
	HB_P_MESSAGE, 47, 0,	/* _CCAPTION */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00237 */ HB_P_LINEOFFSET, 8,	/* 80 */
	HB_P_MESSAGE, 48, 0,	/* _NSTYLE */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_PUSHSYMNEAR, 49,	/* NOR */
	HB_P_PUSHNIL,
	HB_P_PUSHLONG, 0, 0, 0, 64,	/* 1073741824 */
	HB_P_PUSHLONG, 0, 0, 0, 16,	/* 268435456 */
	HB_P_PUSHLONG, 0, 0, 1, 0,	/* 65536 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00267 */ HB_P_LINEOFFSET, 9,	/* 81 */
	HB_P_MESSAGE, 50, 0,	/* _LDRAG */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_PUSHLOCALNEAR, 12,	/* LDESIGN */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00279 */ HB_P_LINEOFFSET, 10,	/* 82 */
	HB_P_MESSAGE, 51, 0,	/* _AEVENTS */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_PUSHLOCALNEAR, 8,	/* AEVENTS */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00291 */ HB_P_LINEOFFSET, 11,	/* 83 */
	HB_P_MESSAGE, 52, 0,	/* _BWHEN */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_PUSHLOCALNEAR, 9,	/* BWHEN */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00303 */ HB_P_LINEOFFSET, 12,	/* 84 */
	HB_P_MESSAGE, 53, 0,	/* _BVALID */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_PUSHLOCALNEAR, 10,	/* BVALID */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00315 */ HB_P_LINEOFFSET, 14,	/* 86 */
	HB_P_MESSAGE, 54, 0,	/* DEFAULT */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00325 */ HB_P_LINEOFFSET, 16,	/* 88 */
	HB_P_PUSHSYMNEAR, 55,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 18, 0,	/* HWND */
	HB_P_PUSHLOCALNEAR, 5,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_NOT,
	HB_P_JUMPFALSE, 204, 0,	/* 204 (abs: 00544) */
/* 00343 */ HB_P_LINEOFFSET, 17,	/* 89 */
	HB_P_PUSHSYMNEAR, 56,	/* FILE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 6,	/* CVBXFILE */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSE, 166, 0,	/* 166 (abs: 00518) */
/* 00355 */ HB_P_LINEOFFSET, 20,	/* 92 */
	HB_P_PUSHSYMNEAR, 55,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 57, 0,	/* _HCTL */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_PUSHSYMNEAR, 58,	/* VBXCREATE */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 18, 0,	/* HWND */
	HB_P_PUSHLOCALNEAR, 5,	/* OWND */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 59, 0,	/* GETNEWID */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 6,	/* CVBXFILE */
	HB_P_PUSHLOCALNEAR, 7,	/* CVBXCLASS */
	HB_P_MESSAGE, 60, 0,	/* CCAPTION */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 61, 0,	/* NSTYLE */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 62, 0,	/* NLEFT */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 63, 0,	/* NTOP */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 3,	/* NWIDTH */
	HB_P_PUSHLOCALNEAR, 4,	/* NHEIGHT */
	HB_P_ZERO,
	HB_P_FUNCTIONSHORT, 11,
	HB_P_SENDSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 39,	/* 39 (abs: 00464) */
/* 00427 */ HB_P_LINEOFFSET, 21,	/* 93 */
	HB_P_PUSHSYMNEAR, 64,	/* MSGALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 21,	/* 21 */
	'C', 'o', 'u', 'l', 'd', ' ', 'n', 'o', 't', ' ', 'c', 'r', 'e', 'a', 't', 'e', ' ', 'V', 'B', 'X', 0, 
	HB_P_DOSHORT, 1,
/* 00457 */ HB_P_LINEOFFSET, 22,	/* 94 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 54,	/* 54 (abs: 00516) */
	HB_P_MESSAGE, 65, 0,	/* _HWND */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_PUSHSYMNEAR, 66,	/* VBXGETHWND */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 13, 0,	/* HCTL */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00484 */ HB_P_LINEOFFSET, 25,	/* 97 */
	HB_P_MESSAGE, 67, 0,	/* LINK */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00494 */ HB_P_LINEOFFSET, 26,	/* 98 */
	HB_P_MESSAGE, 68, 0,	/* VBXINHERIT */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00504 */ HB_P_LINEOFFSET, 27,	/* 99 */
	HB_P_MESSAGE, 69, 0,	/* ADDCONTROL */
	HB_P_PUSHLOCALNEAR, 5,	/* OWND */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 26,	/* 26 (abs: 00542) */
/* 00518 */ HB_P_LINEOFFSET, 30,	/* 102 */
	HB_P_PUSHSYMNEAR, 64,	/* MSGALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 15,	/* 15 */
	'V', 'B', 'X', ' ', 'n', 'o', 't', ' ', 'f', 'o', 'u', 'n', 'd', '!', 0, 
	HB_P_DOSHORT, 1,
	HB_P_JUMPNEAR, 14,	/* 14 (abs: 00556) */
/* 00544 */ HB_P_LINEOFFSET, 33,	/* 105 */
	HB_P_MESSAGE, 70, 0,	/* DEFCONTROL */
	HB_P_PUSHLOCALNEAR, 5,	/* OWND */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00556 */ HB_P_LINEOFFSET, 36,	/* 108 */
	HB_P_PUSHLOCALNEAR, 12,	/* LDESIGN */
	HB_P_JUMPFALSENEAR, 14,	/* 14 (abs: 00574) */
/* 00562 */ HB_P_LINEOFFSET, 37,	/* 109 */
	HB_P_MESSAGE, 71, 0,	/* CHECKDOTS */
	HB_P_PUSHLOCALNEAR, 13,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00574) */
/* 00574 */ HB_P_LINEOFFSET, 40,	/* 112 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00579 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TVBCONTROL_REDEFINE )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 7,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 8,	/* SELF */
/* 00006 */ HB_P_BASELINE, 118, 0,	/* 118 */
	HB_P_PUSHLOCALNEAR, 5,	/* AEVENTS */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 7,	/* 7 (abs: 00020) */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00022) */
	HB_P_PUSHLOCALNEAR, 5,	/* AEVENTS */
	HB_P_POPLOCALNEAR, 5,	/* AEVENTS */
	HB_P_PUSHLOCALNEAR, 2,	/* OWND */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 9,	/* 9 (abs: 00037) */
	HB_P_PUSHSYMNEAR, 38,	/* GETWNDDEFAULT */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_JUMPNEAR, 4,	/* 4 (abs: 00039) */
	HB_P_PUSHLOCALNEAR, 2,	/* OWND */
	HB_P_POPLOCALNEAR, 2,	/* OWND */
	HB_P_MESSAGE, 72, 0,	/* _NID */
	HB_P_PUSHLOCALNEAR, 8,	/* SELF */
	HB_P_PUSHLOCALNEAR, 1,	/* NID */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00051 */ HB_P_LINEOFFSET, 3,	/* 121 */
	HB_P_MESSAGE, 46, 0,	/* _OWND */
	HB_P_PUSHLOCALNEAR, 8,	/* SELF */
	HB_P_PUSHLOCALNEAR, 2,	/* OWND */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00063 */ HB_P_LINEOFFSET, 4,	/* 122 */
	HB_P_MESSAGE, 57, 0,	/* _HCTL */
	HB_P_PUSHLOCALNEAR, 8,	/* SELF */
	HB_P_ZERO,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00074 */ HB_P_LINEOFFSET, 5,	/* 123 */
	HB_P_MESSAGE, 51, 0,	/* _AEVENTS */
	HB_P_PUSHLOCALNEAR, 8,	/* SELF */
	HB_P_PUSHLOCALNEAR, 5,	/* AEVENTS */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00086 */ HB_P_LINEOFFSET, 6,	/* 124 */
	HB_P_MESSAGE, 52, 0,	/* _BWHEN */
	HB_P_PUSHLOCALNEAR, 8,	/* SELF */
	HB_P_PUSHLOCALNEAR, 6,	/* BWHEN */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00098 */ HB_P_LINEOFFSET, 7,	/* 125 */
	HB_P_MESSAGE, 53, 0,	/* _BVALID */
	HB_P_PUSHLOCALNEAR, 8,	/* SELF */
	HB_P_PUSHLOCALNEAR, 7,	/* BVALID */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00110 */ HB_P_LINEOFFSET, 9,	/* 127 */
	HB_P_MESSAGE, 73, 0,	/* SETCOLOR */
	HB_P_PUSHLOCALNEAR, 8,	/* SELF */
	HB_P_PUSHLOCALNEAR, 3,	/* NCLRFORE */
	HB_P_PUSHLOCALNEAR, 4,	/* NCLRBACK */
	HB_P_SENDSHORT, 2,
	HB_P_POP,
/* 00124 */ HB_P_LINEOFFSET, 11,	/* 129 */
	HB_P_PUSHLOCALNEAR, 2,	/* OWND */
	HB_P_PUSHNIL,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 16,	/* 16 (abs: 00146) */
/* 00132 */ HB_P_LINEOFFSET, 12,	/* 130 */
	HB_P_MESSAGE, 70, 0,	/* DEFCONTROL */
	HB_P_PUSHLOCALNEAR, 2,	/* OWND */
	HB_P_PUSHLOCALNEAR, 8,	/* SELF */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00146) */
/* 00146 */ HB_P_LINEOFFSET, 15,	/* 133 */
	HB_P_MESSAGE, 54, 0,	/* DEFAULT */
	HB_P_PUSHLOCALNEAR, 8,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00156 */ HB_P_LINEOFFSET, 17,	/* 135 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00161 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TVBCONTROL_INITIATE )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 1,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 2,	/* SELF */
/* 00006 */ HB_P_BASELINE, 141, 0,	/* 141 */
	HB_P_MESSAGE, 74, 0,	/* INITIATE */
	HB_P_MESSAGE, 31, 0,	/* TCONTROL */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 1,	/* HDLG */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00024 */ HB_P_LINEOFFSET, 2,	/* 143 */
	HB_P_PUSHSYMNEAR, 55,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 57, 0,	/* _HCTL */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_PUSHSYMNEAR, 75,	/* VBXGETHCTL */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 18, 0,	/* HWND */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_SENDSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_JUMPFALSENEAR, 69,	/* 69 (abs: 00119) */
/* 00052 */ HB_P_LINEOFFSET, 3,	/* 144 */
	HB_P_PUSHSYMNEAR, 64,	/* MSGALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 36,	/* 36 */
	'E', 'r', 'r', 'o', 'r', ' ', 'i', 'n', 'i', 't', 'i', 'a', 'l', 'i', 'z', 'i', 'n', 'g', ' ', 'V', 'B', 'X', ' ', 'c', 'o', 'n', 't', 'r', 'o', 'l', ' ', 'I', 'D', ':', ' ', 0, 
	HB_P_PUSHSYMNEAR, 76,	/* STR */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 77, 0,	/* NID */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHBYTE, 4,	/* 4 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_PLUS,
	HB_P_DOSHORT, 1,
/* 00112 */ HB_P_LINEOFFSET, 4,	/* 145 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00119) */
/* 00119 */ HB_P_LINEOFFSET, 7,	/* 148 */
	HB_P_MESSAGE, 68, 0,	/* VBXINHERIT */
	HB_P_PUSHLOCALNEAR, 2,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POP,
/* 00129 */ HB_P_LINEOFFSET, 9,	/* 150 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00134 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TVBCONTROL_INITEVENTS )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 4, 0,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 1,	/* SELF */
/* 00006 */ HB_P_BASELINE, 158, 0,	/* 158 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPLOCALNEAR, 4,	/* AEVENTS */
/* 00014 */ HB_P_LINEOFFSET, 1,	/* 159 */
	HB_P_MESSAGE, 78, 0,	/* NGETEVENTS */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POPLOCALNEAR, 3,	/* NEVENTS */
/* 00025 */ HB_P_LINEOFFSET, 3,	/* 161 */
	HB_P_LOCALNEARSETINT, 2, 1, 0,	/* N 1*/
	HB_P_PUSHLOCALNEAR, 2,	/* N */
	HB_P_PUSHLOCALNEAR, 3,	/* NEVENTS */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 28,	/* 28 (abs: 00064) */
/* 00038 */ HB_P_LINEOFFSET, 4,	/* 162 */
	HB_P_PUSHSYMNEAR, 79,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 4,	/* AEVENTS */
	HB_P_MESSAGE, 80, 0,	/* GETEVENT */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_PUSHLOCALNEAR, 2,	/* N */
	HB_P_SENDSHORT, 1,
	HB_P_DOSHORT, 2,
/* 00056 */ HB_P_LINEOFFSET, 5,	/* 163 */
	HB_P_LOCALNEARADDINT, 2, 1, 0,	/* N 1*/
	HB_P_JUMPNEAR, 225,	/* -31 (abs: 00031) */
/* 00064 */ HB_P_LINEOFFSET, 6,	/* 164 */
	HB_P_MESSAGE, 81, 0,	/* _AEVENTNAMES */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_PUSHLOCALNEAR, 4,	/* AEVENTS */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00076 */ HB_P_LINEOFFSET, 8,	/* 166 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00081 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TVBCONTROL_AGETPROPS )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 4, 0,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 1,	/* SELF */
/* 00006 */ HB_P_BASELINE, 172, 0,	/* 172 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPLOCALNEAR, 2,	/* APROPS */
/* 00014 */ HB_P_LINEOFFSET, 1,	/* 173 */
	HB_P_MESSAGE, 82, 0,	/* NGETPROPS */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POPLOCALNEAR, 3,	/* NPROPS */
/* 00025 */ HB_P_LINEOFFSET, 4,	/* 176 */
	HB_P_LOCALNEARSETINT, 4, 1, 0,	/* N 1*/
	HB_P_PUSHLOCALNEAR, 4,	/* N */
	HB_P_PUSHLOCALNEAR, 3,	/* NPROPS */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 28,	/* 28 (abs: 00064) */
/* 00038 */ HB_P_LINEOFFSET, 5,	/* 177 */
	HB_P_PUSHSYMNEAR, 79,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 2,	/* APROPS */
	HB_P_MESSAGE, 83, 0,	/* CGETPROP */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_PUSHLOCALNEAR, 4,	/* N */
	HB_P_SENDSHORT, 1,
	HB_P_DOSHORT, 2,
/* 00056 */ HB_P_LINEOFFSET, 6,	/* 178 */
	HB_P_LOCALNEARADDINT, 4, 1, 0,	/* N 1*/
	HB_P_JUMPNEAR, 225,	/* -31 (abs: 00031) */
/* 00064 */ HB_P_LINEOFFSET, 8,	/* 180 */
	HB_P_PUSHLOCALNEAR, 2,	/* APROPS */
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00070 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TVBCONTROL_HANDLEEVENT )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 3,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 4,	/* SELF */
/* 00006 */ HB_P_BASELINE, 186, 0,	/* 186 */
	HB_P_PUSHLOCALNEAR, 1,	/* NMSG */
	HB_P_PUSHINT, 12, 8,	/* 2060 */
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 37,	/* 37 (abs: 00052) */
/* 00017 */ HB_P_LINEOFFSET, 4,	/* 190 */
	HB_P_MESSAGE, 84, 0,	/* VBXEVENT */
	HB_P_PUSHLOCALNEAR, 4,	/* SELF */
	HB_P_MESSAGE, 13, 0,	/* HCTL */
	HB_P_PUSHLOCALNEAR, 4,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_MESSAGE, 85, 0,	/* AEVENTS */
	HB_P_PUSHLOCALNEAR, 4,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 2,	/* NWPARAM */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_ARRAYPUSH,
	HB_P_PUSHLOCALNEAR, 3,	/* NLPARAM */
	HB_P_SENDSHORT, 3,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00052) */
/* 00052 */ HB_P_LINEOFFSET, 7,	/* 193 */
	HB_P_MESSAGE, 86, 0,	/* HANDLEEVENT */
	HB_P_MESSAGE, 31, 0,	/* TCONTROL */
	HB_P_PUSHLOCALNEAR, 4,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 1,	/* NMSG */
	HB_P_PUSHLOCALNEAR, 2,	/* NWPARAM */
	HB_P_PUSHLOCALNEAR, 3,	/* NLPARAM */
	HB_P_SENDSHORT, 3,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00074 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TVBCONTROL_DEFAULT )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 1, 0,	/* locals, params */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 1,	/* SELF */
/* 00006 */ HB_P_BASELINE, 199, 0,	/* 199 */
	HB_P_MESSAGE, 87, 0,	/* LREGISTERED */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 102,	/* 102 (abs: 00119) */
/* 00019 */ HB_P_LINEOFFSET, 4,	/* 203 */
	HB_P_PUSHSYMNEAR, 88,	/* VBXINIT */
	HB_P_PUSHNIL,
	HB_P_PUSHSYMNEAR, 89,	/* GETRESOURCES */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHSTRSHORT, 1,	/* 1 */
	0, 
	HB_P_FUNCTIONSHORT, 2,
	HB_P_NOT,
	HB_P_JUMPFALSENEAR, 44,	/* 44 (abs: 00079) */
/* 00037 */ HB_P_LINEOFFSET, 5,	/* 204 */
	HB_P_PUSHSYMNEAR, 64,	/* MSGALERT */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 26,	/* 26 */
	'V', 'B', 'X', ' ', 's', 'u', 'p', 'p', 'o', 'r', 't', ' ', 'n', 'o', 't', ' ', 'a', 'v', 'a', 'i', 'l', 'a', 'b', 'l', 'e', 0, 
	HB_P_DOSHORT, 1,
/* 00072 */ HB_P_LINEOFFSET, 6,	/* 205 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00079) */
/* 00079 */ HB_P_LINEOFFSET, 10,	/* 209 */
	HB_P_MESSAGE, 90, 0,	/* _LREGISTERED */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_PUSHSYMNEAR, 91,	/* REGISTERCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHSTRSHORT, 10,	/* 10 */
	'V', 'b', 'C', 'o', 'n', 't', 'r', 'o', 'l', 0, 
	HB_P_PUSHSYMNEAR, 49,	/* NOR */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_PUSHINT, 0, 64,	/* 16384 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00119) */
/* 00119 */ HB_P_LINEOFFSET, 13,	/* 212 */
	HB_P_MESSAGE, 92, 0,	/* _LVBX */
	HB_P_MESSAGE, 93, 0,	/* OWND */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_TRUE,
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00135 */ HB_P_LINEOFFSET, 15,	/* 214 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00140 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( TVBCONTROL_VBXINHERIT )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 10, 0,	/* locals, params */
	HB_P_SFRAME, 112, 0,	/* symbol (_INITSTATICS) */
	HB_P_PUSHSELF,
	HB_P_POPLOCALNEAR, 1,	/* SELF */
/* 00009 */ HB_P_BASELINE, 222, 0,	/* 222 */
	HB_P_MESSAGE, 82, 0,	/* NGETPROPS */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POPLOCALNEAR, 2,	/* NPROPS */
/* 00021 */ HB_P_LINEOFFSET, 1,	/* 223 */
	HB_P_MESSAGE, 78, 0,	/* NGETEVENTS */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_POPLOCALNEAR, 3,	/* NEVENTS */
/* 00032 */ HB_P_LINEOFFSET, 3,	/* 225 */
	HB_P_PUSHSYMNEAR, 94,	/* SET */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_TRUE,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_POPLOCALNEAR, 9,	/* LEXACT */
/* 00043 */ HB_P_LINEOFFSET, 4,	/* 226 */
	HB_P_ARRAYGEN, 0, 0,	/* 0 */
	HB_P_POPLOCALNEAR, 10,	/* APROPS */
/* 00050 */ HB_P_LINEOFFSET, 6,	/* 228 */
	HB_P_PUSHSTATIC, 2, 0,	/* OTVBCONTROL */
	HB_P_PUSHNIL,
	HB_P_EXACTLYEQUAL,
	HB_P_JUMPFALSENEAR, 14,	/* 14 (abs: 00071) */
/* 00059 */ HB_P_LINEOFFSET, 7,	/* 229 */
	HB_P_PUSHSYMNEAR, 0,	/* TVBCONTROL */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_POPSTATIC, 2, 0,	/* OTVBCONTROL */
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00071) */
/* 00071 */ HB_P_LINEOFFSET, 10,	/* 232 */
	HB_P_PUSHSYMNEAR, 95,	/* _OBJNEWCLS */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 96, 0,	/* GETNAME */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSTATIC, 2, 0,	/* OTVBCONTROL */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 4,	/* NCLASSH */
	HB_P_ZERO,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSE, 226, 0,	/* 226 (abs: 00319) */
/* 00096 */ HB_P_LINEOFFSET, 12,	/* 234 */
	HB_P_PUSHLOCALNEAR, 3,	/* NEVENTS */
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_JUMPFALSENEAR, 95,	/* 95 (abs: 00197) */
/* 00104 */ HB_P_LINEOFFSET, 14,	/* 236 */
	HB_P_MESSAGE, 4, 0,	/* ADDMULTICLSDATA */
	HB_P_PUSHVARIABLE, 97, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHNIL,
	HB_P_PUSHVARIABLE, 98, 0,	/* NSCOPE */
	HB_P_ADDINT, 32, 0,	/* 32*/
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'a', 'E', 'v', 'e', 'n', 't', 'N', 'a', 'm', 'e', 's', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_SENDSHORT, 5,
	HB_P_POP,
/* 00141 */ HB_P_LINEOFFSET, 16,	/* 238 */
	HB_P_PUSHSYMNEAR, 99,	/* ARRAY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* NEVENTS */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 7,	/* AEVENTS */
/* 00152 */ HB_P_LINEOFFSET, 18,	/* 240 */
	HB_P_LOCALNEARSETINT, 5, 1, 0,	/* N 1*/
	HB_P_PUSHLOCALNEAR, 5,	/* N */
	HB_P_PUSHLOCALNEAR, 3,	/* NEVENTS */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 32,	/* 32 (abs: 00195) */
/* 00165 */ HB_P_LINEOFFSET, 19,	/* 241 */
	HB_P_PUSHSYMNEAR, 39,	/* UPPER */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 80, 0,	/* GETEVENT */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_PUSHLOCALNEAR, 5,	/* N */
	HB_P_SENDSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHLOCALREF, 7, 0,	/* AEVENTS */
	HB_P_PUSHLOCALNEAR, 5,	/* N */
	HB_P_ARRAYPOP,
/* 00187 */ HB_P_LINEOFFSET, 20,	/* 242 */
	HB_P_LOCALNEARADDINT, 5, 1, 0,	/* N 1*/
	HB_P_JUMPNEAR, 221,	/* -35 (abs: 00158) */
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00197) */
/* 00197 */ HB_P_LINEOFFSET, 24,	/* 246 */
	HB_P_LOCALNEARSETINT, 5, 1, 0,	/* N 1*/
	HB_P_PUSHLOCALNEAR, 5,	/* N */
	HB_P_PUSHLOCALNEAR, 2,	/* NPROPS */
	HB_P_LESSEQUAL,
	HB_P_JUMPFALSENEAR, 39,	/* 39 (abs: 00247) */
/* 00210 */ HB_P_LINEOFFSET, 25,	/* 247 */
	HB_P_PUSHSYMNEAR, 39,	/* UPPER */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 100, 0,	/* GETPROPNAME */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_PUSHLOCALNEAR, 5,	/* N */
	HB_P_SENDSHORT, 1,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 6,	/* CNAME */
/* 00228 */ HB_P_LINEOFFSET, 27,	/* 249 */
	HB_P_PUSHSYMNEAR, 79,	/* AADD */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 10,	/* APROPS */
	HB_P_PUSHLOCALNEAR, 6,	/* CNAME */
	HB_P_DOSHORT, 2,
/* 00239 */ HB_P_LINEOFFSET, 39,	/* 261 */
	HB_P_LOCALNEARADDINT, 5, 1, 0,	/* N 1*/
	HB_P_JUMPNEAR, 214,	/* -42 (abs: 00203) */
/* 00247 */ HB_P_LINEOFFSET, 41,	/* 263 */
	HB_P_PUSHSYMNEAR, 101,	/* ASORT */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 10,	/* APROPS */
	HB_P_DOSHORT, 1,
/* 00256 */ HB_P_LINEOFFSET, 42,	/* 264 */
	HB_P_MESSAGE, 4, 0,	/* ADDMULTICLSDATA */
	HB_P_PUSHVARIABLE, 97, 0,	/* S_OCLASS */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 10,	/* APROPS */
	HB_P_PUSHVARIABLE, 98, 0,	/* NSCOPE */
	HB_P_ADDINT, 32, 0,	/* 32*/
	HB_P_PUSHSTRSHORT, 12,	/* 12 */
	'a', 'P', 'r', 'o', 'p', 'e', 'r', 't', 'i', 'e', 's', 0, 
	HB_P_ARRAYGEN, 1, 0,	/* 1 */
	HB_P_FALSE,
	HB_P_SENDSHORT, 5,
	HB_P_POP,
/* 00294 */ HB_P_LINEOFFSET, 44,	/* 266 */
	HB_P_PUSHSYMNEAR, 102,	/* SETCLSHANDLE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_PUSHLOCALNEAR, 4,	/* NCLASSH */
	HB_P_DOSHORT, 2,
/* 00305 */ HB_P_LINEOFFSET, 46,	/* 268 */
	HB_P_MESSAGE, 81, 0,	/* _AEVENTNAMES */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_PUSHLOCALNEAR, 7,	/* AEVENTS */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
	HB_P_JUMPNEAR, 36,	/* 36 (abs: 00353) */
/* 00319 */ HB_P_LINEOFFSET, 48,	/* 270 */
	HB_P_PUSHSYMNEAR, 103,	/* _CLASSHANDLE */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 96, 0,	/* GETNAME */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 4,	/* NCLASSH */
	HB_P_ZERO,
	HB_P_NOTEQUAL,
	HB_P_JUMPFALSENEAR, 15,	/* 15 (abs: 00353) */
/* 00340 */ HB_P_LINEOFFSET, 49,	/* 271 */
	HB_P_PUSHSYMNEAR, 102,	/* SETCLSHANDLE */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_PUSHLOCALNEAR, 4,	/* NCLASSH */
	HB_P_DOSHORT, 2,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00353) */
/* 00353 */ HB_P_LINEOFFSET, 52,	/* 274 */
	HB_P_PUSHSYMNEAR, 99,	/* ARRAY */
	HB_P_PUSHNIL,
	HB_P_PUSHLOCALNEAR, 3,	/* NEVENTS */
	HB_P_FUNCTIONSHORT, 1,
	HB_P_POPLOCALNEAR, 7,	/* AEVENTS */
/* 00364 */ HB_P_LINEOFFSET, 54,	/* 276 */
	HB_P_PUSHSYMNEAR, 55,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 85, 0,	/* AEVENTS */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_NOT,
	HB_P_JUMPFALSE, 117, 0,	/* 117 (abs: 00496) */
/* 00382 */ HB_P_LINEOFFSET, 55,	/* 277 */
	HB_P_LOCALNEARSETINT, 5, 1, 0,	/* N 1*/
	HB_P_PUSHLOCALNEAR, 5,	/* N */
	HB_P_PUSHSYMNEAR, 104,	/* LEN */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 85, 0,	/* AEVENTS */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_PUSHBYTE, 2,	/* 2 */
	HB_P_FORTEST,
	HB_P_JUMPFALSENEAR, 89,	/* 89 (abs: 00494) */
/* 00407 */ HB_P_LINEOFFSET, 57,	/* 279 */
	HB_P_PUSHSYMNEAR, 55,	/* EMPTY */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 85, 0,	/* AEVENTS */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 5,	/* N */
	HB_P_ARRAYPUSH,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_NOT,
	HB_P_DUPLICATE,
	HB_P_JUMPFALSENEAR, 35,	/* 35 (abs: 00461) */
	HB_P_PUSHSYMNEAR, 105,	/* ASCAN */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 106, 0,	/* AEVENTNAMES */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHSYMNEAR, 39,	/* UPPER */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 85, 0,	/* AEVENTS */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 5,	/* N */
	HB_P_ARRAYPUSH,
	HB_P_FUNCTIONSHORT, 1,
	HB_P_FUNCTIONSHORT, 2,
	HB_P_DUPLICATE,
	HB_P_POPLOCALNEAR, 8,	/* NAT */
	HB_P_ZERO,
	HB_P_GREATER,
	HB_P_AND,
	HB_P_JUMPFALSENEAR, 25,	/* 25 (abs: 00486) */
/* 00463 */ HB_P_LINEOFFSET, 58,	/* 280 */
	HB_P_MESSAGE, 85, 0,	/* AEVENTS */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 5,	/* N */
	HB_P_ADDINT, 1, 0,	/* 1*/
	HB_P_ARRAYPUSH,
	HB_P_PUSHLOCALREF, 7, 0,	/* AEVENTS */
	HB_P_PUSHLOCALNEAR, 8,	/* NAT */
	HB_P_ARRAYPOP,
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00486) */
/* 00486 */ HB_P_LINEOFFSET, 60,	/* 282 */
	HB_P_LOCALNEARADDINT, 5, 2, 0,	/* N 2*/
	HB_P_JUMPNEAR, 152,	/* -104 (abs: 00388) */
	HB_P_JUMPNEAR, 2,	/* 2 (abs: 00496) */
/* 00496 */ HB_P_LINEOFFSET, 63,	/* 285 */
	HB_P_MESSAGE, 51, 0,	/* _AEVENTS */
	HB_P_PUSHLOCALNEAR, 1,	/* SELF */
	HB_P_PUSHLOCALNEAR, 7,	/* AEVENTS */
	HB_P_SENDSHORT, 1,
	HB_P_POP,
/* 00508 */ HB_P_LINEOFFSET, 65,	/* 287 */
	HB_P_PUSHSYMNEAR, 94,	/* SET */
	HB_P_PUSHNIL,
	HB_P_ONE,
	HB_P_PUSHLOCALNEAR, 9,	/* LEXACT */
	HB_P_DOSHORT, 2,
/* 00518 */ HB_P_LINEOFFSET, 67,	/* 289 */
	HB_P_PUSHNIL,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00523 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( BGETPROP )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 0, 1,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 38, 1,	/* 294 */
	HB_P_PUSHBLOCK, 24, 0,	/* 24 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	1, 0,	/* N */
	HB_P_PUSHSYMNEAR, 25,	/* VBXGETPROP */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 13, 0,	/* HCTL */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_FUNCTIONSHORT, 2,
	HB_P_ENDBLOCK,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00032 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( BSETPROP )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 0, 1,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 43, 1,	/* 299 */
	HB_P_PUSHBLOCK, 26, 0,	/* 26 */
	2, 0,	/* number of local parameters (2) */
	1, 0,	/* number of local variables (1) */
	1, 0,	/* N */
	HB_P_PUSHSYMNEAR, 16,	/* VBXSETPROP */
	HB_P_PUSHNIL,
	HB_P_MESSAGE, 13, 0,	/* HCTL */
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_SENDSHORT, 0,
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_PUSHLOCALNEAR, 2,	/* codeblockvar2 */
	HB_P_FUNCTIONSHORT, 3,
	HB_P_ENDBLOCK,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00034 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

HB_FUNC_STATIC( BARRAYPROP )
{
   static const BYTE pcode[] =
   {
	HB_P_FRAME, 0, 1,	/* locals, params */
/* 00003 */ HB_P_BASELINE, 48, 1,	/* 304 */
	HB_P_PUSHBLOCK, 24, 0,	/* 24 */
	1, 0,	/* number of local parameters (1) */
	1, 0,	/* number of local variables (1) */
	1, 0,	/* N */
	HB_P_MESSAGE, 1, 0,	/* NEW */
	HB_P_PUSHSYMNEAR, 110,	/* TVBXARRAY */
	HB_P_PUSHNIL,
	HB_P_FUNCTIONSHORT, 0,
	HB_P_PUSHLOCALNEAR, 1,	/* codeblockvar1 */
	HB_P_PUSHLOCALNEAR, 255,	/* localvar1 */
	HB_P_SENDSHORT, 2,
	HB_P_ENDBLOCK,
	HB_P_RETVALUE,
	HB_P_ENDPROC
/* 00032 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

static HARBOUR hb_INITSTATICS( void )
{
   static const BYTE pcode[] =
   {
	HB_P_STATICS, 112, 0, 2, 0,	/* symbol (_INITSTATICS), 2 statics */
	HB_P_ENDPROC
/* 00006 */
   };

   hb_vmExecute( pcode, symbols, NULL );
}

